### ISSUE TITLE
.mergeFromTo doing octopus merge instead of expected merge

### ISSUE THREAD

**Issue by omixximo** [steveukx/git-js#1003]
Hello,

I was trying to use the command mergeFromTo to merge a branch allocated in a remote.

Example: origin/branchToMerge

Reading the documentation of the method I can see that:
```
/**
    * Merges from one branch to another, equivalent to running `git merge ${remote} ${branch}`, the `options` argument can
    * either be an array of additional parameters to pass to the command or null / omitted to be ignored.
    */
   mergeFromTo<E extends GitError>(
     remote: string,
      branch: string,
      options?: types.TaskOptions,
      callback?: types.SimpleGitTaskCallback<resp.MergeResult, E>
   )
```
So I would call the method like git.mergeFromTo('origin', 'branchToMerge').

**This is executing:** 'git merge origin branchToMerge'.
This is tries an octupus merge instead of a normal merge by documentation at least from version 2.33 or higher:
[git-merge doc 2.33](https://git-scm.com/docs/git-merge/2.33.0)
![image](https://github.com/steveukx/git-js/assets/72169119/501a8f1b-2679-4960-a0ad-ccca5a5ff215)

**Expecting to execute:** 'git merge origin/branchToMerge'.

**Comment by steveukx** [comment]
Hi, thank you for opening the issue. The mergeFromTo code has been in place for a long time, and doesn't look to be compatible with modern versions of git - as you rightly point out it will trigger an octopus merge.

I'll update the docs etc soon, until then please use the format 

git.merge(['origin/branch'])
