### ISSUE TITLE
Checkout a single file from latest commit

### ISSUE THREAD

**Issue by iambibhas** [steveukx/git-js#101]
How can I accomplish `git checkout -- <filename>`? Or rather `git checkout <filename>`? The `checkout()` method doesn't seem to accept file name.

**Comment by steveukx** [comment]
You can do this from version `1.42.0` using:

```
simpleGit()
   .checkout(['--', 'filename'], function (err, data) { ... })
```

If you would like to add a custom function for this as a pull request, you can use the existing checkoutBranch function for an example of how it would be implemented.

**Comment by KostyaTretyak** [comment]
> You can do this from version `1.42.0`

But with array of files, seems not working

**Comment by KostyaTretyak** [comment]
I'm confused, if I passing an array of string values, everything works as expected:

```js
simpleGit()
   .checkout( ['master', '--'].concat( ['one', 'two', 'three'] ) )
```

But if I pass a variable with array is not working:

```js
var arr = ['one', 'two', 'three'];

simpleGit()
   .checkout( ['master', '--'].concat(arr) )
```

Says just:
> Switched to branch 'master'

**Comment by KostyaTretyak** [comment]
Now I found time to explore this confusion. Unexpected behavior occurs when I chain:

```js
var arr = [];

simpleGit()
// here some chain ... where set arr = ['one', 'two', 'three'];
  .checkout( ['master', '--', ...arr] )
```

In this case checkout gets empty array, without waiting for `arr = ['one', 'two', 'three'];`.  I can resolve it with the Promise, but it can be called unexpected behavior.

**Comment by steveukx** [comment]
Hi, thank you for looking into this.
In order to better diagnose the problem, please can you create a failing test case using one of the [integration tests](https://github.com/steveukx/git-js/tree/master/test/integration) as an example.

**Comment by KostyaTretyak** [comment]
Sorry, but I do not know how to use or create these tests. But it seems that `.checkout ()` gets copy the array, not the original.
