### ISSUE TITLE
Diff with another branch

### ISSUE THREAD

**Issue by juanf** [steveukx/git-js#102]
Hi, I'm trying to get a diff from another branch and I'm not sure if this is the correct way:

`simpleGit.diff(['HEAD remotes/origin/branch_name --name-only'], function (err, diff)...`

This is the error I get:

> fatal: ambiguous argument 'HEAD remotes/origin/bugfixing_v1 --name-only': unknown revision or path not in the working tree.
> Use '--' to separate paths from revisions, like this:
> 'git <command> [<revision>...] -- [<file>...]'

Works fine when running from the command line.
Is it the right way to do it or maybe a bug?

Thank you.

**Comment by steveukx** [comment]
The `simple-git#diff` command passes the items of the `options` array as arguments to the git binary, to pass multiple arguments you just need to supply them in separate items in the array:

```
simpleGit.diff(['HEAD', 'remotes/origin/branch_name', '--name-only'], function (err, diff)...
```

**Comment by juanf** [comment]
Thank you Steve, I tried that before but I must have been doing something wrong, it works great.
