### ISSUE TITLE
Support for Promises?

### ISSUE THREAD

**Issue by lukehorvat** [steveukx/git-js#103]
Given that there is a `.then` method, it seems to imply that a Promise is returned, but that's not actually the case. So if you want a Promise, you have to crudely wrap it:

``` js
let promise = new Promise(resolve => {
  simpleGit(dir)
    .add('./*')
    .commit('New')
    .push('origin', 'master')
    .then(resolve);
});
```

So could support be added for Promises? One big benefit is that consumers could then use `.catch` for errors.

**Comment by laurynas-karvelis** [comment]
First of all, thank you for the energy, work, and overall, the existence of this project.

However, please, please, add support for promises, native or bluebird.
Logging should be consumer manageable rather than simple-git trying to be opinionated.
Errors passed into the then() handler should be constructed as new Error instead of plain strings. 

That would improve people's lives so much!

**Comment by chovy** [comment]
you can wrap it in a promise yourself.

```
    return new Promise((resolve, reject) => {
      simpleGit.status(function(err, result){
        if (err) return reject(err);
        resolve(result);
      });
    });
```

**Comment by coderas** [comment]
Yeah, but when you are handling "status then fetch then pull then tags", it's all a bit of callback hell.

incidentally, we have a promise chain that resolves after we get the tags, but the code still isn't pretty, so we can get on with the next step, in our case preparing some files and committing them.

**Comment by EvNaverniouk** [comment]
Looks like the latest `1.54.0` version is sort of promise-y, but a bit weird.

This works:

```
simpleGit.revparse(['HEAD'])
   .then((response) => {
      console.log(response);
   });
```

But the `response` is empty. The data doesn't get passed down. You have to do:

```
let response;
simpleGit.revparse(['HEAD'], (err, res) => { response = res; })
   .then(() => {
      console.log(response);
   });
```

Which is... unfortunate.

**Comment by laurynas-karvelis** [comment]
+1

**Comment by steveukx** [comment]
As the existing interface of `simple-git` chains one operation after the next, it isn't readily obvious which step needs to return a promise - every step can add a `.then` block in the chain run arbitrarily added functions specific points in the set of tasks to be run.

The most configurable way to use `simple-git` as part of a promise chain is to wrap it:

```
.then(() => new Promise(done => {
  git().fetch(done);
}))
```

As of version `1.54.0`, an experimental alternative is available:

```
const simple_git = require('simple-git/promise');
const git = simple_git();

  // some promise chain
  .then(() => git.fetch())
  .then(() => git.tags())
  .then(tags => {
    // tags is the tags list from git.tags();
  }
```

While it is in beta, any feedback is appreciated.

**Comment by bumpmann** [comment]
that's perfect, i came to the same (but crappy as i wrapped your lib) solution before i read this issue:

```javascript
function getArgs(func) {
	var args = func.toString().match(/function\s?.*?\(([^)]*)\)/)[1]

	return args.split(',').map(function(arg) {
		return arg.replace(/\/\*.*\*\//, '').trim()
	}).filter(arg => arg)
}

let _git = require('simple-git')
function git(...gitArgs) {
	let repo = _git.apply(_git, gitArgs)
	for (let k in repo) {
		let method = repo[k]
		if (typeof method == 'function') {
			let args = getArgs(method)
			if (args.length && args[args.length - 1] == 'then') {
				repo[k] = (...args) => {
					return new Promise((accept, reject) => {
						args.push(function(err, ...thenArgs) {
							if (err) {
								reject(err)
							} else {
								accept.apply(null, thenArgs)
							}
						})
						method.apply(repo, args)
					})
				}
			}
		}
	}
	return repo
}
```

**Comment by brianmhunt** [comment]
The canonical way for a thenable to support conversion to promises (per the [Promises spec](https://promisesaplus.com/)) is to wrap it in `Promise.resolve` i.e.

```javascript
Promise.resolve(simpleGit.command())
   .then(/* ... */)
   .catch(/* ... */)
```

The `simpleGit.then` function ought to accept two function-arguments, the first called when simpleGit succeeds, the second when it fails.

Proper support for the `then` function will alleviate the need for any further development to support Promises.

It looks like around https://github.com/steveukx/git-js/blob/master/src/git.js#L1030 it should be something like this (I haven't checked, but it looks right):

```javascript
Git.prototype.then = function (success, fail) {
      this._run([], function (err, data) {
         if (err) {
           fail(err)
         } else {
           success(data);
         }
      });
      return this;
}
```

**Comment by halfcrazy** [comment]
The existing then usage is really weird. Please support Promise a* spec.

**Comment by latobibor** [comment]
We had to go with the promise wrapping, after days of thinking why we have weird inconsistency issues. If you give people a `then` then they expect it would work as a Promise, right?

**Comment by steveukx** [comment]
As the library already had `.then` before Promises were readily available elsewhere, switching it to be a promise will be a breaking change. I'll move to a new major version in the near future, until then you can use the promise enabled version:

```
const simpleGit = require('simple-git/promise');
const git = simpleGit(__dirname);

git.pull()
  .then(pullSummary => ...)
  .catch(err => ...)
```

**Comment by latobibor** [comment]
Thanks @steveukx for the heads up! This is great news!

**Comment by OmgImAlexis** [comment]
I'm getting different return values between the promise and callback versions. Is this a bug or expected behaviour?

```js
const git = require('simple-git/promise');
git(cwd()).push('bree', 'master').then((err, data) => console.log({err, data}));
// { err: '', data: undefined }
```

```js
const git = require('simple-git');
git(cwd()).push('bree', 'master', (err, data) => console.log({err, data}));
// { err: null, data: '' }
```

**Comment by steveukx** [comment]
@OmgImAlexis as promises resolve/reject with a single argument this is expected behaviour, you need to use a `.catch` block in order to see the errors:

```
const git = require('simple-git/promise');
git(cwd())
   .push('bree', 'master')
   .then(data => console.log({data}))
   .catch(err => console.error({err});
```

**Comment by OmgImAlexis** [comment]
Oh I completely forgot about that.

**Comment by FireController1847** [comment]
@steveukx Is the plan to KEEP simple-git/promise, as well as keeping it updated, or is it slowly going to be phased out in favor of .exec? If so, what's the plan for async/await support with .exec? I'm just not sure I understand how this .exec stuff works, as it's not really shown nor stated that it will work with async/await.

**Comment by steveukx** [comment]
@FireController1847 for backward compatibility the `simple-git/promise` require will be maintained after the next major release, I've added an example of how to use async/await to the readme for you in https://github.com/steveukx/git-js#async-await-with-simple-gitpromise

**Comment by FireController1847** [comment]
Awesome, thanks.

**Comment by ccoenen** [comment]
If one were to start a fresh project right now, (seeing that 2.0 will bring changes to the API) what would be the best way to start?

**Comment by steveukx** [comment]
Hi, for new projects I would recommend using the import simple-git/promise
and pay care to not be generating any errors as the preliminary releases of
version 2 that comes with promises by default and removes some of the
argument overloading available in earlier versions.

If you think there are any gaps in the API that won't cover your current
use case, please add them to this issue / create new issues for them so
they can go on the backlog.

Thanks, Steve

**Comment by clarsen** [comment]
After struggling to get a clone/add/commit/push sequence to work reliably, I found this git veneer that does seem to provide promises (or at least you can await them in async functions) https://github.com/JarvusInnovations/git-client  https://www.npmjs.com/package/git-client

Not very widely used, and I don't think it does method chaining, but I was able to get stuff working in a few minutes.
