### ISSUE TITLE
Passing options to pull doesn't work

### ISSUE THREAD

**Issue by istanishev** [steveukx/git-js#106]
Options are set *after* the remote and branch which makes them invalid.

**Sample:**
.pull('origin', 'master', {"--rebase" : true }, callback)

**Output:**
error: unknown option `rebase'

**Comment by steveukx** [comment]
Hi, for detail on how to supply values in the options arguments in `.pull`, check out the https://github.com/steveukx/git-js#how-to-specify-options section of the readme. Only items that have a string value in the options object are included in the command output.

I'll add an explicit example in for this shortly.
