### ISSUE TITLE
some git examples?

### ISSUE THREAD

**Issue by chovy** [steveukx/git-js#109]
Can someone tell me how to do the following with git-js?

```
git checkout -b <branch-name>
git checkout master
git branch -d <branch-name>
```

I think it would be cool to have a wiki or a list of common git commands and the git-js equivalents.

**Comment by chovy** [comment]
I added a PR to delete a local branch. Takes care of `git branch -d <branch-name>`
https://github.com/steveukx/git-js/pull/110

**Comment by steveukx** [comment]
Resolved with the PR:

```
git()
  .checkoutLocalBranch('branch-name')
  .checkout('master')
  .deleteLocalBranch('branch-name')
  .then(function () {
    // done.
  })
```

Worth noting that the generic `.checkout` function can take an array of input arguments, so you can do `.checkout(['-b', 'branch-name'])` if you prefer.
