### ISSUE TITLE
addConfig issue with GIT_SSH_COMMAND / core.sshCommand

### ISSUE THREAD

**Issue by Hyperblaster** [steveukx/git-js#111]
I'm using the addConfig function to try and implement a private SSH key to use when pulling from the git repository like below

```
git()
.addConfig('core.sshCommand', 'ssh -i ' + sshPrivateKey, console.log)
```

In this example console.log simply returns (null, '');

Is there anyway to check if this actually runs properly? Or is there a way to view a verbose list of the commands that the pipeline runs?

**Comment by chovy** [comment]
Does this work?

```
const sshCommand = process.env.GIT_SSH_COMMAND;
git()
.addConfig('core.sshCommand', sshCommand, console.log)
```

**Comment by Hyperblaster** [comment]
Unfortunately not.

It just logs out (null '')

**Comment by chovy** [comment]
i don't think the handler function gets passed anything. Is it actually using your ssh command?

That `core.sshCommand` looks correct to me.

**Comment by Hyperblaster** [comment]
Here is my code in it's entirety if it helps.

```
var cloneOptions = [
                '--depth', '1',
                '-v',
            ]

            //Git Config
            var sshCommand = 'ssh -i ' + sshPrivateKeyPath + ' -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null';

            //Clone the directory
            git()
                .addConfig('core.sshCommand', sshCommand, function(err, data) {
                    console.log('Configuration set', err, data, configString)
                })
                .clone(repo.url, directory, cloneOptions, function(err, data) {
                    if (err) {
                        console.log('Git Clone error', err, data)
                        return deployError(err);
                    } else {
                        console.log('clone success', data);
                    }
                })
                .revparse(['--short', 'HEAD'], function(err, revisionID) {
                    if (err) {
                        console.log('Git Revision error', err)
                        return deployError(err);
                    } else {
                        console.log('Git Latest revision', revisionID)
                        //Update the current commit id
                        commitID = revisionID.replace(/\n$/, "");
                    }
                })
                .then(function(err, data) {
                    if (err) {
                        console.log('Git pipeline error')
                        return deployError(err);
                    } else {
                        console.log('Git pipeline success')
                        return cloneSuccess();
                    }
                });
```

**Comment by chovy** [comment]
put a breakpoint here: https://github.com/steveukx/git-js/blob/master/src/git.js#L448

and see if there are any args passed to the handler.

also i would use the env variable.

**Comment by Hyperblaster** [comment]
As in the above code, process.env.GIT_SSH_COMMAND returns undefined.

So maybe i should try 

process.env.GIT_SSH_COMMAND = 'my command';

then run my pipeline? Maybe addConfig doesn't actually work

**Comment by Hyperblaster** [comment]
I was able to get it to work correctly by using this before my pipeline
`process.env.GIT_SSH_COMMAND = sshCommand;`
 instead of
`.addConfig('core.sshCommand', sshCommand)`

My guess is that addConfig doesn't work. Or i was obviously using it wrong? perhaps it might be worth checking it or adding an example in the documentation?

**Comment by steveukx** [comment]
The `data` returned from `addConfig` will always be empty - the `git config` command doesn't print anything to `stdout`. You can add another `addConfig` block that retrieves the value once it has been set by using:

```
git()
  .addConfig('core.sshCommand', 'somevalue', function (err, data) {
  })
  .addConfig('--get', 'core.sshCommand', function (err, data) {
    if (err) throw "Did not set the core.sshCommand config value";
    else console.log("core.sshCommand set to ", data);
  })
```

The git docs show that the `core.sshCommand` value has the same format as the `process.env.GIT_SSH_COMMAND` value, not that it sets the environment variable, so it wouldn't be the case that you can read from the env variable after setting the git config.

It is possible that `core.sshCommand` doesn't work when run as a `--local` configuration - I'd need to test that.

**Comment by chovy** [comment]
You need to set the environment variable `GIT_SSH_COMMAND` in `~/.bashrc`  to do it the way I suggested.
