### ISSUE TITLE
Latest tag is incorrect

### ISSUE THREAD

**Issue by el-davo** [steveukx/git-js#114]
Hi

Ive been using the example you have for getting the latest tag 

```
require('simple-git')(__dirname + '/some-repo')
         .pull()
         .tags(function(err, tags) {
            console.log("Latest available tag: %s", tags.latest);
         });
```

However when i bump the major version it incorrectly reports that the previous version is the latest when i run the function again.

here is the output from the tags

```
TagList {
  latest: 'v0.6.2',
  all:
   [ 'v1.0.0',
     'v0.0.1',
     'v0.0.2',
     'v0.0.3',
     'v0.0.4',
     'v0.0.5',
     'v0.0.6',
     'v0.0.7',
     'v0.1.0',
     'v0.2.0',
     'v0.3.0',
     'v0.4.0',
     'v0.5.0',
     'v0.6.0',
     'v0.6.1',
     'v0.6.2' ] }
```

Am not sure if this is meant to happen. But to me the latest here would be version v1.0.0 and not v0.6.2

Any help appreciated

**Comment by steveukx** [comment]
Hi, parsing the tag version numbers wasn't taking account of the `v` prefix. A new version `1.51.0`  is on npm now that will take care of that for you.

**Comment by el-davo** [comment]
Awesome, thanks!

**Comment by glin7976** [comment]
Hi, is this fixed? I'm still facing the incorrect latest tag issue.
