### ISSUE TITLE
branche(args, callback) does not return a correct summary

### ISSUE THREAD

**Issue by harmoniemand** [steveukx/git-js#118]
I am trying to read all branches. In my opinion this code should do the trick. But it does not.

    var simpleGit = require('simple-git')( __dirname );
    simpleGit.branch(["-a"], function (err, summary) {
        if (err) {
            console.error(err);
            return;
        }
        console.log(JSON.stringify(summary));
    });

**Comment by steveukx** [comment]
Hi

Using `.branch` without any options will automatically request all branches.

To use the options and see full data in the summary response, please ensure you include the `-v` option.
