### ISSUE TITLE
Object has no method 'clone'

### ISSUE THREAD

**Issue by shaharsol** [steveukx/git-js#125]
Here's a code sample:

```
var simpleGit = require('simple-git')
simpleGit.clone(cloneUrl,dir,function(err){
	callback(err)
})
```

I'm getting this error:

```
				simpleGit.clone(cloneUrl,dir,function(err){
				          ^
TypeError: Object function (baseDir) {
    return new Git(baseDir || process.cwd(), ChildProcess, Buffer);
} has no method 'clone'
```

What am I doing wrong?

**Comment by steveukx** [comment]
Hi, the returned value of the `require` is a function that allows you to set the base directory before then using the git instance. Check out the [examples](https://github.com/steveukx/git-js#examples) section in the readme for examples of how to instantiate git and start chaining methods to it.

```
var simpleGit = require('simple-git')(/* base directory here, defaults to current directory */)
simpleGit.clone(cloneUrl,dir,function(err){
    callback(err)
})
```
