### ISSUE TITLE
about some problems of using simple-git

### ISSUE THREAD

**Issue by misshy** [steveukx/git-js#126]

**Comment by misshy** [comment]
1.how to realize git revert          
2.support show clone progress percent?

**Comment by vitya1** [comment]
Hi, @misshy 
1. You can use git reset instead of revert.
2. I suppose you should use piping to a terminal to show commands process if you don't see progress by default

**Comment by steveukx** [comment]
Hi, [git-revert](https://git-scm.com/docs/git-revert) support has been added in version 1.55.0 on npm now.

For viewing progress output, please follow the instructions for `piping to the console for long running tasks` in the readme.
