### ISSUE TITLE
Callback never called when using more than one command in parallel

### ISSUE THREAD

**Issue by bumpmann** [steveukx/git-js#136]
Hello, i need your help for this bug

I m not sure why but:

```
let nrepo = git(path);
nrepo.status((err,res) => { console.log('nstatus', err, res) })
nrepo.status((err,res) => { console.log('nstatus_x', err, res) })
setTimeout(() => { nrepo.status((err,res) => { console.log('nstatus_y', err, res) }) }, 1000)
```

I can see `nstatus`, `nstatus_y` but not `nstatus_x`.

with promises, this is really annoying because the equivalent is:
```
let orepo = git(path); // with simple-git/promise
orepo.status().then(() => {
    console.log('status1 -> then');
}).catch((e) => {
    console.log('status1 -> catch');
})
orepo.status().then(() => {
    console.log('status1_x -> then');
}).catch((e) => {
    console.log('status1_x -> catch');
})
```
and `status1_x` is never displayed so it breaks the promise chain.

I tested with an empty repository (not initialized) so it logged `fatal: Not a git repository (or any of the parent directories): .git` but only for those which received the callback

**Comment by steveukx** [comment]
Hi, which operating system are you using? On Mac OS, both of these test cases work as expected (ie: all logs are printed). As `simple-git` uses the currently installed `git` binary - are you able to run multiple git processes concurrently as direct children of the main process?

**Comment by bumpmann** [comment]
In an empty folder I did npm init / npm install simple-git / create a file index.js with only
```javascript
let git = require('simple-git')
let nrepo = git(process.cwd());
let nrepo2 = git(process.cwd());
nrepo.status((err,res) => { console.log('nstatus', err, res) })
nrepo2.status((err,res) => { console.log('nstatus2', err, res) })
nrepo.status((err,res) => { console.log('nstatus_x', err, res) })
setTimeout(() => { nrepo.status((err,res) => { console.log('nstatus_y', err, res) }) }, 1000)
```
on win7 x64, node 6.5.0, git version 2.9.2.windows.1

I can also see `nstatus2` in this test, so I guess this means that it can run multiple git processes concurrently.

but i think it's not specific to windows, a friend on mac had the same error (i ll give you more infos on his version)

**Comment by bumpmann** [comment]
As a workaround i wrapped all my calls with
```javascript
let waitChain : Promise<any> = Promise.resolve()
function waitAndSend(fn):Promise<any> {
	return new Promise((accept, reject) => {
		waitChain = waitChain.then(() => {
			return fn().then((res) => {
				accept(res)
			}).catch((err) => {
				reject(err)
			})
		})
	})
}
```

but that's not a solution ^^

**Comment by bumpmann** [comment]
I could reproduce on mac with `git version 2.8.4 (Apple Git-73)`

**Comment by steveukx** [comment]
I'm still not able to make this fail - there's now an integration test bundle that covers your use case that is passing for me on `git version 1.9.3 (Apple Git-50)` and also on travis.

Please can you try running the tests locally with `grunt test` / modify the `test-parallel-requests.js` script to more accurately represent how you're using simple-git.

**Comment by bumpmann** [comment]
Okay, so the error appears only when there is no git repo initialized (your tests passes, because of .init() in the setUp)

Moreover, if a .status does not call its callback, a done() is missing and the test returns:
```
>> Incomplete tests/setups/teardowns:
>> test 0 [ 'test' ]
Fatal error: A test was missing test.done(), so nodeunit exploded. Sorry!
```

So here is my test/integration/test-parallel-error-requests.js:
```javascript
'use strict';

const Test = require('./include/runner');

const setUp = (context) => {
   return Promise.resolve()
};

const test = (context, assert) => {
   let first = context.git(context.root);

   let results = [];
   let promises = [
      new Promise(done => {
         const timeout = setTimeout(() => {
            assert.ok(false, "Should have been in first callback");
            done();
         },1000);
         first.status(err => {
            clearTimeout(timeout);
            results.push('first');
            assert.notEqual(err, null, 'Should be an error');
            done();
         });
      }),
      new Promise(done => {
         const timeout = setTimeout(() => {
            assert.ok(false, "Should have been in second callback");
            done();
         },1000);
         first.status(err => {
            clearTimeout(timeout);
            results.push('second');
            assert.notEqual(err, null, 'Should be an error');
            done();
         });
      })
   ];

   return new Promise(function (done) {
      const assertAllProcessesCompleted = () => {
         assert.equal(
            results.sort().join(' '),
            'first second',
            'Should have handled each process errors'
         );
         done();
      };

      const timeout = setTimeout(assertAllProcessesCompleted, 2000);

      Promise.all(promises).then(() => {
         clearTimeout(timeout);
         assertAllProcessesCompleted();
         done();
      });
   });
};

module.exports = new Test(setUp, test);
```

which gives me: (i didn't used .silent() for now)
```
E:\git-js>set TMPDIR=E:\tmp\

E:\git-js>grunt test
Running "nodeunit:unit" (nodeunit) task
Testing test-branch.js.........OK
Testing test-clean.js.......OK
Testing test-commands.jsSOME ERROR
.............................................Git#submoduleUpdate: args should be
 supplied as an array of individual arguments
...Git#submoduleInit: args should be supplied as an array of individual argument
s
............OK
Testing test-fetch.js........OK
Testing test-git.js..OK
Testing test-log.js..Git#log: supplying to or from as strings is now deprecated,
 switch to an options configuration object
......OK
Testing test-pull.js.....OK
Testing test-push.js.....OK
Testing test-rebase.js...OK
Testing test-revert.js...OK
Testing test-stash.js...OK
Testing test-status.js.......OK
Testing test-tags.js....OK
>> 323 assertions passed (422ms)

Running "nodeunit:integration" (nodeunit) task
Testing test-parallel-error-requests.jsfatal: Not a git repository (or any of th
e parent directories): .git

F
>> test
>> Message: Should have been in second callback
>> Error: false == true
>> at Timeout.setTimeout (test\integration\test-parallel-error-requests.js:28:20
)
>> at tryOnTimeout (timers.js:232:11)
>> at Timer.listOnTimeout (timers.js:202:5)

>> test
>> Message: Should have handled each process errors
>> Error: 'first' == 'first second'
>> at assertAllProcessesCompleted (test\integration\test-parallel-error-requests
.js:42:17)
>> at Promise.all.then (test\integration\test-parallel-error-requests.js:54:10)

Testing test-parallel-requests.js.OK
Warning: 2/8 assertions failed (2142ms) Use --force to continue.

Aborted due to warnings.
```

I ve the error on win & mac with the versions from precent posts, it looks like placing the test context in /tmp/... is a good test because i could reproduce it on my mac.

**Comment by steveukx** [comment]
Thanks for the update, I see the issue now - this is caused by the onward chain of calls being terminated when `simple-git` encounters an error. 

The expected behaviour is that when using the standard (ie: non-promise) API, the first step in the chain that encounters an error calls its callback with that error and all steps that had been scheduled to run after that step are removed from the queue.

From your original query:

```
nrepo.status((err,res) => { console.log('nstatus', err, res) })
nrepo2.status((err,res) => { console.log('nstatus2', err, res) })
nrepo.status((err,res) => { console.log('nstatus_x', err, res) })
setTimeout(() => { nrepo.status((err,res) => { console.log('nstatus_y', err, res) }) }, 1000)
```

The first two `nrepo` calls are in a single chain, meaning that the first `nstatus` exception will prevent the `nstatus_x` from ever having been executed.

The `setTimeout` at the end of the block waits sufficient time to have had the `nrepo` queue cleared before it adds another `.status` to the queue. As the queue was empty at that point, it is executed and therefore the `nstatus_y` does get called with a new error.

These are both covered in the new [test-broken-chains](https://github.com/steveukx/git-js/blob/master/test/integration/test-broken-chains.js) script.

**Comment by bumpmann** [comment]
btw, shouldn't the expected behaviour for the non-promise api be:

call both callbacks on errors:
```javascript
nrepo.status((err,res) => { console.log('nstatus', err, res) })
nrepo.status((err,res) => { console.log('nstatus_x', err, res) })
```

call only first callback on error:
```javascript
nrepo.status((err,res) => { console.log('nstatus', err, res) })
     .status((err,res) => { console.log('nstatus_x', err, res) })
```

i guess that means managing multiple queues / shedules though i m a bit off-topic

**Comment by steveukx** [comment]
So far all examples for the Promise wrapped version have ensured that the simple-git instance only ever has a single item in the queue (ie `git.fn().then(() => git.anotherFn())`). The internal chain handling in the Promise wrapped version doesn't cater for the use as a chain (ie: `git.fn(); git.anotherFn().then(....)`).

I've started to look at this in #144, the fix will be to allow for an optional setting to error all steps in the forthcoming chain in the standard API that the promise wrapped one will use to error all as-yet not run chained steps.

I'll probably get to this done in the next week or so - if you need something before then, please do submit a PR.
