### ISSUE TITLE
Expose _run through promise

### ISSUE THREAD

**Issue by shellscape** [steveukx/git-js#139]
I'd like to request that access to the `_run` method for executing complex git commands be made available when requiring `simple-git/promise`.

**Comment by steveukx** [comment]
Hi, the aim of the library is to provide more readable versions of the various git command line functions so that the response can be parsed in a uniform / functional way. Which command is it you're trying to run that doesn't have a bespoke wrapper already?

**Comment by shellscape** [comment]
That may be, but you've also unintentionally made it an excellent and reliable lib to run raw git commands and easily handle raw output as well 😄  Certainly there's room for an "advanced" subsection of users? We're leveraging this lib to run:

```bash
diff-tree
diff
config
fetch
push
ls-remote
```

The list goes on. While some of those have helper methods, we're using additional inline options which are outside of the helper method's capabilities, so we utilize `_run`. Our primary use is in tooling pipelines (gulp, et al.). I'm also using it in projects like https://github.com/shellscape/travis-target/blob/master/index.js#L19

I can't see a need to create helper methods for the commands we're using that don't have convenience methods already, or refactor for advanced command config, because `_run` works so well for us. Exposing `_run` as public would still ring true to the lib; providing a simple and easy method to interact with git, only that the one method would dole out raw output.

**Comment by steveukx** [comment]
Makes sense - you should now be able to use `git.raw` with either an array of arguments or an [options object](https://github.com/steveukx/git-js#how-to-specify-options) from version 1.63.0 onwards.

**Comment by shellscape** [comment]
Outstanding. Thank you for adding this 🎉
