### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by pronebird** [steveukx/git-js#141]
What do you do if any of this fails?

```js
repo.init(false)
   .addRemote('origin', 'git@github.com/foobar.git')
          .checkoutLocalBranch('master')
```

I tried catch from promises but there is none.

I think it would be great to use async/await, seems like cleaner way to handle errors:

https://medium.com/@bluepnume/learn-about-promises-before-you-start-using-async-await-eb148164a9c8#.uqo2fbh3y

**Comment by steveukx** [comment]
Each step in the set of chained functions has a function callback as the final argument that can receive an error message - in the example above it would be:

```
const git = require('simple-git');
const baseDir = 'some/path';
const repo = git(baseDir);

function errorHandler (step) {
  return function (err) {
    if (err) console.error(`Error using ${step}`, err); 
  };
}

repo.init(false, errorHandler('init'))
   .addRemote('origin', 'git@github.com/foobar.git', errorHandler('addRemote'))
   .checkoutLocalBranch('master', errorHandler('checkoutLocalBranch'));
```

You should also be able to catch errors when building a promise chain using the experimental Promise based api:

```
const git = require('simple-git/promise');
const baseDir = 'some/path';
const repo = git(baseDir);


repo.init(false)
.then(() => repo.addRemote('origin', 'git@github.com/foobar.git'))
.then(() => repo.checkoutLocalBranch('master'))
.catch((err) => handleException(err));
```

**Comment by pronebird** [comment]
Thanks @steveukx! Need to check but I think last time i tried catch wasn't available

**Comment by pronebird** [comment]
Oh just noticed /promise branch.
