### ISSUE TITLE
.log doesn't parse commits with tags containing ";" very well

### ISSUE THREAD

**Issue by ipanasenko** [steveukx/git-js#146]
Hi!

So, I have this commit, which has tag "RC;.;1.63.0" on it. When logging this commit, I get following:

```
ListLogLine {
  hash: 'COMMIT_SHA',
  date: '2016-11-22 23:32:27 +0000',
  message: '"COMMIT NAME" (tag: RC',
  author_name: '.',
  author_email: '1.63.0)' }
```

Notice that author name and email is corrupted and part of tag is displayed instead

Package version 1.63.0

P.S. Same versions of your module and mine are just coincidence :)

**Comment by steveukx** [comment]
Hi. The default splitter in the `git.log` command is a semi-colon. If you use semi-colons in your commit messages though, you can switch it to use another character by setting the `options.splitter` value, for example:

```
git.log({ splitter: '*' }, (err, log) => {
});
```

**Comment by ipanasenko** [comment]
@steveukx thanks! Did not think about that
