### ISSUE TITLE
How to set username and password?

### ISSUE THREAD

**Issue by blackshade91** [steveukx/git-js#147]
Is it possibile to set username and password for different repo?

**Comment by steveukx** [comment]
As the library just wraps the standard git binary - how to set authentication credentials is largely up to you. I would recommend checking out the [gitcredentials](https://git-scm.com/docs/gitcredentials) documentation for using credentials in a specific repo, or perhaps setting access tokens using a [.netrc](https://gist.github.com/technoweenie/1072829)

**Comment by blackshade91** [comment]
How to set authentication credentials locally and not for global user with the plugin?

**Comment by steveukx** [comment]
As this is a wrapper library for the git binary, you can pass almost anything through to it you need and it will use the same configuration as if you were using `git` commands directly in that working directory. Perhaps look at http://stackoverflow.com/questions/10054318/how-to-provide-username-and-password-when-run-git-clone-gitremote-git for setting the authentication details in the remote address.
