### ISSUE TITLE
.pull sends no summary of results?

### ISSUE THREAD

**Issue by marcusjwhelan** [steveukx/git-js#150]
I am working on a project to auto update when there are any changes to the master branch. The users clients should ping the back end and see if there any updates. I use simple-git and .pull and check the same as your example but they are always empty. No changes are ever shown but it still pulls.

**Comment by steveukx** [comment]
From your description, it appears you are using `pull` on the server with multiple clients that can all be checking for updates. If the server uses `pull`, its working branch will be updated with all remote changes and the `PullSummary` will contain the changes made. When another client pings your server, if the server calls `pull` again when there haven't yet been updates made on the remote, the response will be empty.

If you are using multiple clients, you can have them send the commit hash of their head in the request and then on the server use a combination of `.pull` to ensure the server's copy is up to date then `.diff(['client-commit-hash'], function (diffSummary) { ... })`

**Comment by marcusjwhelan** [comment]
Hello Steve

Actually what our team is doing currently is a little different but for now
it's how we have it set up. We have one server running a website that
gathers and displays data for managers and admins, but this server also is
the mother database.

The clients are actually complete websites with a mongodb server and nodejs
app running on their personal laptops. They are pulling from a centralized
github repo. So if I make a change to that github repo all the clients will
be pinging that repo and their branch will update but that will not update
all the other remote repos, that just would be impossible.

Above is how it should work although it seems that when the client which is
a client/server pings the github repo it never has any
changes/deletions/insertions in the changes object of the .pull. Although
it will still pull down the new code. We were trying to set a variable to
true when there were any changes/deletions/insertions in the changes object
of .pull.

Since the functionality of that item was not working as we viewed from your
docs I ended up using .fetch and .tag to compare the repo's tag and the
clients current package.json version. If they do not match the variable is
set. This currently works.

**Comment by sspilleman** [comment]
Ik have the same issue... The repo is refresed, but the result object doesn't show any changes/deletions/inserts etc.. The PullSumary is always empty 👎 

Any updates to this?

**Comment by CanRau** [comment]
same here, pull summary always empty even though it has merged

i'm using promise version

**Comment by brilvio** [comment]
Same here but the pull summary is only empty when adding or deleting a file, if I change a file it works.

**Comment by brilvio** [comment]
I found the error, I will be doing a pull request to fix it.
