### ISSUE TITLE
git.status not actually returning anything

### ISSUE THREAD

**Issue by tcaer** [steveukx/git-js#153]
Hi, I am not sure how to get the actual status of the git repository.

Here is my code: 
```
git.status(function(res) {

});
```
Res is returned as null, what am I supposed to do?

Thanks

**Comment by steveukx** [comment]
Hi, in order to check this for you - please ensure you are using the latest release (currently 1.65.0).

What is the output from running `git status --porcelain -b` in a terminal in that working directory?

**Comment by morlauth** [comment]
@steveukx The terminal returns:
```
## master
M git/repo.js
```
git/repo.js is a file which I had changed since the previous commit.

Thanks

**Comment by CliffS** [comment]
I think you need:

    git.status(function(err, res) {
        if (err) {
            throw err;
        }
        // result will be in res now
    });

**Comment by luftywiranda13** [comment]
@tcaer try [g-status](https://github.com/luftywiranda13/g-status) if you want to get a _ready to consume_ `git status` result 😃 

It utilizes `simple-git` under the hood
