### ISSUE TITLE
how to get the new file added or not in specific folder?

### ISSUE THREAD

**Issue by thangam105** [steveukx/git-js#154]
I want to get the exist file different summary and also get the new file summary.

**Note:** 
.diffSummary(options, handlerFn) i have used it for different file. It is not shown the new files.

How to get this?

Please suggest to it.

Regards,
Thangavel E

**Comment by steveukx** [comment]
Hi, by "new files" do you mean files that have not yet been added / committed? If so, have you tried `.status(handlerFn)` - it will return you an instance of the [StatusSummary](https://github.com/steveukx/git-js/blob/master/src/responses/StatusSummary.js) listing all files that are different to those currently checked in to HEAD.
