### ISSUE TITLE
How to see changed files in commit?

### ISSUE THREAD

**Issue by argoroots** [steveukx/git-js#155]

**Comment by steveukx** [comment]
There are many options listed in http://stackoverflow.com/questions/424071/how-to-list-all-the-files-in-a-commit

One of which can be implemented as:

```
git.show(['--stat', '--online', 'HEAD'], function (err, data) {
  if (err) throw new Error(err);

  var output = data.trim().split('\n');
  var summary = output.shift().split(' ');
  var detail = output.pop().split(', ');
  var files = output.map(function (line) {
    return /^(.+)\s+\|\s+(\d+)\s+[+\-]+$/.exec(line.trim());
  });
});
```

> disclaimer: this is composed without having tested it, it's just to give you the idea.

**Comment by chrisdothtml** [comment]
@steveukx Any interest in adding support for optionally using the `diffSummary` return format for `stat`?
