### ISSUE TITLE
Assuming UTF-8 output

### ISSUE THREAD

**Issue by owengage** [steveukx/git-js#156]
Hi there, I've found your library very useful, thank you.

I've got a clumsily modified version (not on github) where you can return the Buffer object from stdout rather than have it converted to a UTF-8 string.

My use case is extracting image files (or general files) from git using `cat-file`. This doesn't work because the conversion to UTF-8 mangles the bytes for images.

I've played around a bit and I could make it an option that is passed into the initial git object, something like this:

```javascript
git('repo/path', { outputFormat: 'Buffer' }).catFile(...);
```

But it feels very unnatural and is a second layer of options that I don't like very much. Do you have any input or ideas? I'd happily make a PR but was wondering what direction you'd like the code to take before I did anything.

**Comment by steveukx** [comment]
I was looking to add support for this with a separate end-point for:

```
git().catFileRaw((err, buffer) => {});
```

Where the data is returned as the actual buffer as opposed to the full content switched to the utf8 string. Would that help?

**Comment by owengage** [comment]
That would work perfectly.
