### ISSUE TITLE
API supports git archive?

### ISSUE THREAD

**Issue by vongohren** [steveukx/git-js#158]
The title says the most, but i basically want to use the archive function to fetch out a specific file from a specific repo and in a specific branch, in a nodemodule

**Comment by benftwc** [comment]
Hello, I don't think so. But can be a nice idea to implement it, I need it too, I'll do it I think then PR ;)

**Comment by steveukx** [comment]
Hi, you might find what you need with either the `.catFile` or `.binaryCatFile` methods.

There is an example of using the binary version (which returns the binary-safe Buffer rather than UTF8 string) in the tests at https://github.com/steveukx/git-js/blob/master/test/unit/test-catfile.js#L70

**Comment by vongohren** [comment]
Im closing because im not followin this up anymore
