### ISSUE TITLE
hide errors from git

### ISSUE THREAD

**Issue by jmls** [steveukx/git-js#161]
I am trying to init a repo, so am doing this

```
git = require('simple-git')(repoPath);
git.status((err,status) => {
                    if (err) {
                        console.log("creating git repo for ",id);
                        git.init();
                    }
                });
```

whilst this works, I get an ugly `fatal: Not a git repository (or any of the parent directories): .git` on the console which I would rather not see

As this looks like a standard git message, Is it possible to hide these messages ?

Alternatively, is there an option to determine if a folder is a valid git repo or not (rather than getting involved with `fs.stat` or the like ?

**Comment by steveukx** [comment]
Have you tried using the `.silent(isSilent)` method? 

`git.silent(isSilent)` sets whether the console should be used for logging errors, by default this will be set to silent when the `NODE_ENV` environment variable contains the string `prod`.

**Comment by ShiHaoLin** [comment]
There is no.

**Comment by jmls** [comment]
@steveukx : nope, I missed that one .. sorry. Will give it a go

**Comment by jmls** [comment]
works like a charm. thanks.

**Comment by ShiHaoLin** [comment]
I will only a little English. ‘simple-git’   To understand a little bit.
