### ISSUE TITLE
typescript typings

### ISSUE THREAD

**Issue by stephenlautier** [steveukx/git-js#162]
Hi,
Are you willing to accept TypeScript typings within the repo itself?

This will make it more convenient for typescript users (and [suggested by typescript](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package)) to provide typings with the repository itself, rather than another repo (such as [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)).

I will be happy to create typing for this library myself if you agree.

Thanks!

**Comment by steveukx** [comment]
Hi, I don't use TS on this project at the moment, but happy to have the d.ts files available. Please feel free to open a pull request!
