### ISSUE TITLE
Change remote origins.

### ISSUE THREAD

**Issue by Craigzyc** [steveukx/git-js#165]
Im trying to change the remote origins to add in the username and token. 
Is there any way to do this as when I try .addRemote i get fatal: remote origin already exists rather than overwriting it

**Comment by steveukx** [comment]
Hi, there isn't a command in this library's API that will do this for you directly, however you can make use of the `simpleGit.raw` method to run any valid git command, for example:

```
const remoteName = 'origin';
const remoteUrl = '... the new remote url ...';
const simple = require('simple-git')(repoDir);

simple.raw(['remote', 'set-url', remoteName, remoteUrl], (err, data) => {
  if (err) console.error('SetUrl failed: ', err);
  else console.log('Done!');
});
```

A good tutorial on changing the URL of a remote is https://help.github.com/articles/changing-a-remote-s-url/
