### ISSUE TITLE
Tags aren't sorted

### ISSUE THREAD

**Issue by adatta02** [steveukx/git-js#167]
I noticed you guys closed https://github.com/steveukx/git-js/issues/114 but "tags" is still returning the tags in a "sorted" not chronological order. That's causing "tags.latest" to be incorrect in some instances.

On newer versions of git, it looks like it's possible to pass '--sort=-creatordate' which causes them to sort by their creation date. Not sure what git targets you're trying to support but updating the call to be 

```
   /**
    * List all tags
    *
    * @param {Function} [then]
    */
   Git.prototype.tags = function (then) {
      return this.tag(['-l', '--sort=-creatordate'], Git._responseHandler(then, 'TagList'));
   };
```

Seems to work.

**Comment by steveukx** [comment]
Hi

The sorting and `tags.latest` was added to sort by semantic versioning, if there is now an option to specify the sort order, I'll remove the library sorting when that option is provided.

**Comment by steveukx** [comment]
As of Git version 2.7 you can use the `--sort` option in [git tag](https://git-scm.com/docs/git-tag/2.7.0), I've amended the `git.tags` function to accept an [options object](https://github.com/steveukx/git-js#how-to-specify-options), if the options include the `--sort` option, the existing default behaviour of sorting by semantic versioning will be removed. It's worth noting though that if you are using an older version of git, the command will fail as it is an unsupported option.

**Comment by adatta02** [comment]
Awesome - thanks!
