### ISSUE TITLE
Option for `deleteLocalBranch` to force delete

### ISSUE THREAD

**Issue by maxhallinan** [steveukx/git-js#169]
Is this library still maintained? All open pull requests are from 2016 and seem to be dormant.

If the maintainer(s) are still accepting PRs, I'm interested in contributing to the `deleteLocalBranch` method. I'm using this library to delete local branches but I need to force delete them. I can do this using  the `.branch` method: `.branch(['-D', 'branchName'], handlerFn)`. The problem is that `.branch` will only call the `handlerFn` with `DeleteBranchSummary` if `'-d'` is found in the options array. At the moment, my workaround is to use `['-d', '-D', 'branchName']`. At the very least, [this condition](https://github.com/steveukx/git-js/blob/master/src/git.js#L525) should recognize `--delete` and `-D`. 

In addition, it's confusing that `deleteLocalBranch` does not support force deletes. In general, the design of this method confuses me. Why is it limited to deleting local branches and why doesn't it support force deletes? In both ways, it defines an operation whose narrowness seems arbitrary and unnecessary. It would be relatively easy to add support for both remote and force deletes by adding an options argument and generalizing to `deleteBranch`. 

If the maintainer(s) agree and are still accepting pull requests, I'd be happy to open a PR that addresses one or both of these thoughts. Let me know!

**Comment by steveukx** [comment]
Hi, this does sound like a useful addition, please feel free to add a pull request.

**Comment by maxhallinan** [comment]
Sorry for the delayed response! I've been traveling. Working on this now.

**Comment by maxhallinan** [comment]
#177 adds support for all of the git-branch delete options.

Adding `deleteBranch` or changing `deleteLocalBranch` to support a force delete option are both breaking changes. I'm happy to add one or the other but want to make sure you're onboard with a major version bump. If so, it'd be good to discuss the API for either of these choices before implementing it just to make sure we're on the same page.

Thanks for your time!
