### ISSUE TITLE
Conflicts after pull

### ISSUE THREAD

**Issue by Deuchnord** [steveukx/git-js#172]
Is there any way to deal with conflicts after a `git pull`? I don't see anything for this purpose in the documentation.

I'd like to do something like this:

```js
conflicts = git.getConflictedFiles();
```

which would return a list of objects containing the content both my and their files with conflicts (if any):

```js
[
   {
      mine: "content of my version",
      theirs: "content of their version"
   }
]
```

Is it possible with the current version of this library?

**Comment by steveukx** [comment]
Hi, there isn't anything specific for conflict resolution in the api at the moment. 

You should be able to get to the list of files by using `git.diff(['--diff-filter=U'], (err, data) => { /* data is the raw data from the git diff command */ })`. See [here](https://git-scm.com/docs/git-diff#git-diff---diff-filterACDMRTUXB82308203) for `diff-filter` options.

You could then use `git.show(..)` to get the file contents at `HEAD` and `HEAD^1`.

**Comment by Deuchnord** [comment]
Thanks for your answer, I'll check that :)
