### ISSUE TITLE
Is there a plan to distribute typings via `npm install @types/simple-git`

### ISSUE THREAD

**Issue by another-guy** [steveukx/git-js#173]

**Comment by steveukx** [comment]
I'd not planned it, but that would be useful - I'll add it to the backlog, or feel free to create a pull request if you need it done sooner.

**Comment by karfau** [comment]
Since you have the types as part of your release, you don't need to split it up.
For me doing `import git from 'simple-git/promise';` worked just fine.

**Comment by karfau** [comment]
@another-guy I updated my earlier answer since it contained an error.

Does this answer your question or do you still think it makes sense to have the types in `@types/simple-git`?

**Comment by another-guy** [comment]
@karfau yes it does, but the time line for this issue was so long, I've decided not to use `git-js` at all.
