### ISSUE TITLE
submoduleAdd with Branch

### ISSUE THREAD

**Issue by alexandruluca** [steveukx/git-js#178]
Please consider refactoring your Git::submoduleAdd method to allow setting up a branch for the submodule

Something like this

```javascript
/**
 * Add a submodule with branch
 *
 * @param {string} repo
 * @param {string} path
 * @param {string} branch
 * @param {Function} [then]
 */
Git.prototype.submoduleAdd = function (repo, path, branch, then) {
	return this._run(['submodule', 'add', '-b', branch, repo, path], function (err) {
		then && then(err);
	});
};
```

**Comment by steveukx** [comment]
This can currently be achieved by using the basic `.submodule` method:

```
git.subModule(['add', '-b', branch, repo, path], (err, response) => {
});
```

If you would open a pull request to add this to `submoduleAdd` while maintaining backward compatibility, please feel free.

**Comment by alexandruluca** [comment]
Thanks for the feedback! Not needed then
