### ISSUE TITLE
how to input password use node?

### ISSUE THREAD

**Issue by zhaopengme** [steveukx/git-js#181]
I use code.
```
var simpleGit = require('simple-git')();

simpleGit
    .clone('https://bitbucket.org/dapengme/zhaopengme.git', '~/test', function (err, data) {
        console.log(err);
        console.log(data);
    })
```
how to input password use node?

thanks!
![image](https://cloud.githubusercontent.com/assets/1415418/26477956/b4598fbe-41fb-11e7-87a2-e409d483ab47.png)

**Comment by steveukx** [comment]
This library doesn't provide any api specific to authentication at present - you may find the answers to #147 and #171 of use for examples of how to set auth parameters in either the URL of the remote repo or references for how to set up gitcredentials.

**Comment by zhaopengme** [comment]
thanks. @giper45 Solved the problem.
