### ISSUE TITLE
How to force to delete a branch  "git branch -D branchName" ??? 

### ISSUE THREAD

**Issue by kevingamboa17** [steveukx/git-js#182]
First of all, thank you so much for your work, it's pretty awesome.

but i have a question.
How can i force to delete a branch, normally, i would do  
```git branch -D branchName```

but i don't know how to do it here.
thanks.

**Comment by steveukx** [comment]
You can pass an array of commands to the `.branch` method to force delete the branch:

```
const git = require('simple-git');
git(repoDir)
  .branch(['-D', 'branch-name'], (err, deleteSummary) => {
    // 
  });
```

When deleting a branch the response will be an instance of [BranchDeleteSummary](https://github.com/steveukx/git-js/blob/master/src/responses/BranchDeleteSummary.js)

**Comment by kevingamboa17** [comment]
Thank you, you helped me a lot ;)
