### ISSUE TITLE
how to kill git process?

### ISSUE THREAD

**Issue by zhaopengme** [steveukx/git-js#183]
as the picture shows. when I push to github, I want warning someone ,use web alert,and want kill  git process. 

and `console.log('hello');` can not print.

![image](https://cloud.githubusercontent.com/assets/1415418/26762410/7a9a54d6-4974-11e7-8125-3436e1819042.png)

**Comment by steveukx** [comment]
Apologies for the delay - the library doesn't currently handle authentication requests in this way, but there are a couple of options available:

- Use an [authenticated URL](https://github.com/steveukx/git-js#authentication) for the remote
- Check for output in the stdout and respond with the password on stdin (not something I have done, but "should" work).

If you have created a workaround already, please do consider making a pull request.

**Comment by zhaopengme** [comment]
ok.thinks!
and now I use nodegit to solve .

**Comment by mittalyashu** [comment]
Does this package have any option to kill the git process? _(just curious to know)_
