### ISSUE TITLE
How to pass password for git on cloning a repo?

### ISSUE THREAD

**Issue by ckoo7** [steveukx/git-js#185]
Is this functionality available here? Can I get help please?

**Comment by steveukx** [comment]
You may find #171 useful - you can add the username and password as part of the URL of the remote repo. To avoid logging them you can also make use of `.silent(true)` which will avoid all output to `stdout` from the library.

**Comment by test-as-main-owner** [comment]
Using `.silent(true)` would also suppress progress output, right? Progress output in git is done via `stderr`, so maybe not.
