### ISSUE TITLE
git config --get

### ISSUE THREAD

**Issue by GammaNu** [steveukx/git-js#186]
Hi, i would like to know who will be credit for the commit with a `git config --get user.name`
and `git config --get user.email`
it was not directly possible in 2015 : https://github.com/steveukx/git-js/issues/62

is-it now ?

**Comment by steveukx** [comment]
You can achieve this by using the `raw()` api to pass any arbitrary arguments to the git command - details of which are in https://github.com/steveukx/git-js#complex-requests

```
const git = require('simple-git');
const command = 'config --get user.name'.split(' ');

git().raw(command, (err, data) => { });
```

**Comment by GammaNu** [comment]
perfect ! Thank you !

**Comment by TechQuery** [comment]
@steveukx Why not add a `git.getConfig(name)` method?

**Comment by steveukx** [comment]
As of version 2.3.0 you can now make use of [`git.listConfig()`](https://github.com/steveukx/git-js#git-config) to get the current git configuration, other config apis are to follow.
