### ISSUE TITLE
how to know a file which has been added to index but no to be commited

### ISSUE THREAD

**Issue by dandingol03** [steveukx/git-js#187]
Hi,Team
&nbsp;&nbsp;when i use terminal to add some changed file to index,i find that there is no way to distribute the added file and the modified files from `git(cwd).status` api.
&nbsp;&nbsp;For example,i make some changes in `"App/components/Coach.js`,and add it to index.However,it appeared in the modified array .Here is a snapshot:

![image](https://user-images.githubusercontent.com/13013579/27510266-b8f0a50c-593f-11e7-9ac3-d435537cf553.png)
&nbsp;&nbsp;So how can i distribute the added file from modified files which are not added.
&nbsp;&nbsp;Thanks for your time.

**Comment by luftywiranda13** [comment]
@dandingol03 try [g-status](https://github.com/luftywiranda13/g-status) if you want to get a _ready to consume_ `git status` result 😃 

It utilizes `simple-git` under the hood
