### ISSUE TITLE
Get branches merged to master

### ISSUE THREAD

**Issue by anlesk** [steveukx/git-js#194]
Hi guys,

Is it possible to get list of all remote branches that are merged to master?
I can do that with `git.raw`:
`git.raw(['branch', '-r', '--merged', 'master'], callback);`

But is it possible to do so with `git.branch`?
I've tried `git.branch(['--merged', 'master'], callback);` but with no success.

**Comment by steveukx** [comment]
The [BranchSummary](https://github.com/steveukx/git-js/blob/master/src/responses/BranchSummary.js) parser used in the response to `git.branch` expects the verbose format, try:

```
git.branch(['-v', '-r', '--merged', 'master'], (err, branchSummary) => {
  // branchSummary is the instance of BranchSummary
});
```

**Comment by anlesk** [comment]
@steveukx Thanks alot! Works as a charm!
