### ISSUE TITLE
Check whether current directory is within a repository

### ISSUE THREAD

**Issue by dannycjones** [steveukx/git-js#195]
I'm wondering what the best way to check that you are currently within a git repository is?

My current approach is like the code below (using `simple-git/promise`), which I use a `.then()` on:

```javascript
const git = require('simple-git/promise');

function checkInRepo() {
    return new Promise((resolve, reject) => {
        return git.silent(true).raw(['rev-parse', '--is-inside-work-tree']).then(() => resolve(true), () => resolve(false));
    });
}

checkInRepo().then(inRepo => {
    console.log('This directory is in a repo:', inRepo);
});
```

https://github.com/dannycjones/git-chauthor/blob/9c47d3f538c35f92869adb1bac115478bb94712d/bin/chauthor.js#L58-L62

Perhaps there is demand for a method to check if current working directory is a repo? `#isRepo()`?

**Comment by steveukx** [comment]
This is a good suggestion, thanks. I think something similar should be incorporated to the start of each chain to ensure the working directory is / is not already a git managed repo.

If you would like to do a pull request, please do, otherwise I should have time to put something together in the next week or so.

**Comment by dannycjones** [comment]
Unfortunately I do not have time this month 😭 but I'll stay up to date with this issue.

Would the idea be to have the methods throw if it isn't a repo? (And perhaps a method to check that it is a repo first so there isn't a need for a catch?)

```javascript
const git = require('simple-git/promise');

if (simpleGit.isRepo()) {
    git.diff().then(someFuncAboutDiffs).catch(someErrFunc);
} else {
    git.init().then(someOtherFunc).catch(someErrFunc);
}
```
