### ISSUE TITLE
Git clone for empty repo throws error???

### ISSUE THREAD

**Issue by jimitpatel65** [steveukx/git-js#199]
1) I was using simple-git clone  since on year and cloning the empty repo was not an issue.
2) Since last two days my job is failing git clone for empty repo. (For :- v1.76.0)
3) On further investigation I found that some updates went in recently causing which is causing the failure.
4) I downgraded the version to v1.75.0 and everything works as expected and it clones the empty repo without throwing error.

**For v1.76.0 empty repo.**
Eg:-  simpleGit.clone(projectDetails.ssh_url_to_repo, [projectDetails.projectUniqueName], function (error, update) {
Error is defined.
}

**For v1.75.0 empty repo.**
Eg:- simpleGit.clone(projectDetails.ssh_url_to_repo, [projectDetails.projectUniqueName], function (error, update) {
Error is undefined.
}

Can you help??

**Comment by yashha** [comment]
I don't know if it is related to this here, but my clone callback is not working.
https://runkit.com/yashha/clonecallback

**Comment by steveukx** [comment]
Hi, I will add support for this way of using `.clone` - the documentation for the method in the readme requires that it is called with `clone(repoPath, localPath, optionalOptionsArray, optionalHandlerFunction)`. If you change your command to be as follows you should find that it works as expected:

```
simpleGit.clone(projectDetails.ssh_url_to_repo, projectDetails.projectUniqueName, function (error, update) {
  // ...
})
```
