### ISSUE TITLE
Errors that produce no output are not thrown

### ISSUE THREAD

**Issue by dbushong** [steveukx/git-js#204]
This line: https://github.com/steveukx/git-js/blob/master/src/git.js#L1288 requires that `stdErr.length` be non-zero, **in addition** to `exitCode` being non-zero.

This means that, e.g., if you get a conflict during a `git merge`, which puts its output onto stdout, that you will not see that as an error.

**Comment by steveukx** [comment]
There was no handling for the "unclean" exit code `1`. `git merge` now has a parser that checks for conflicts and routes to the error path accordingly.

I've covered the merge responses that I can think of, if there are other cases not covered in the tests, please feel free to create a pull request with either a fix or failing tests.
