### ISSUE TITLE
How to use clone with '-b' option

### ISSUE THREAD

**Issue by Seonghyup** [steveukx/git-js#205]
When using git clone with -b(--branch) option, cloning branch after -b option.
But I passed {'-b' : 'branch_name'} object as parameter of clone method, it doesn't work.
How can I use -b option when cloning?

**Comment by steveukx** [comment]
The readme covers this with:

> clone a remote repo at repoPath to a local directory at localPath (can be omitted to use the default of a directory with the same name as the repo name) with an optional array of additional arguments to include between git clone and the trailing repo local arguments

So to use the branch option, you should use:

```
git.clone(REPO_PATH, ['--branch', BRANCH_NAME], (err, result) => {
 // ...
});
```

For consistency this should accept the normal options object as well, I'll add that in to a release soon. If you would like to update the library for yourself though, please feel free to do a pull request.

**Comment by karfau** [comment]
Yes, I also stumbled over this today, `git.clone` only supports options as an array, not as an object.
And I can verify that is does work when using an array like in the example from @steveukx .

PR #240 makes sure all jsdocs are correct regarding what kind of options they support.
So I think this issue could be closed.
