### ISSUE TITLE
examples in readme: then vs exec

### ISSUE THREAD

**Issue by larshp** [steveukx/git-js#211]
Hi,
The examples in https://github.com/steveukx/git-js/blob/master/readme.md use the `then` function, but this is deprecated, and instead the `exec` function should be used

I guess the first Authentication example is okay as it uses `simple-git/promise`? But the Examples part use `simple-git`

**Comment by steveukx** [comment]
Well spotted - as you say, the auth example uses the promise wrapped version whereas all the others don't. They're updated now.
