### ISSUE TITLE
Using Github Personal access tokens to push the changes

### ISSUE THREAD

**Issue by DharanBro** [steveukx/git-js#217]
Do we have any way to use the token instead of URL with username and password during the push operation?

**Comment by steveukx** [comment]
Apologies for the delayed response - `simple-git` uses the standard `git` binary and therefore can use any authentication method you would ordinarily use for automatic auth (currently manually typing the username and password is not supported).

The answer to #147 may be of use to you, setting up either [gitcredentials](https://git-scm.com/docs/gitcredentials) or a [.netrc](https://gist.github.com/technoweenie/1072829)

**Comment by cwtuan** [comment]
private_token can be used as password. Example:
`git clone http://username:private_token@git_domain/group/project`.

I have tested it in gitlab.

**Comment by namdien177** [comment]
> private_token can be used as password. Example:
> `git clone http://username:private_token@git_domain/group/project.git`
> 
> But, how about `push`?

The principle should be the same, you can fetch and push with provided remote like that.
