### ISSUE TITLE
Can Simple-Git do "ls-tree"?

### ISSUE THREAD

**Issue by godhand4826** [steveukx/git-js#219]
Is Simple-Git package can do the git ls-tree command?
something like:
```
git ls-tree -r --name-only $REV
```
(PS:$REV is hash or branch)
I want to list all the track files in the specific version.

**Comment by steveukx** [comment]
There isn't a custom handler for it, but you can use the `.raw` function:

```
const git = require('simple-git/promise');
git().raw(['ls-tree', '-r', '--name-only', $REV])
   .then(response => console.log('Raw data from git command: ', response)
   .catch(error => console.error(error);
```

**Comment by godhand4826** [comment]
I'm just searching for "ls-files" and "ls-tree" in the document and fund nothing. XD
Thanks for helping me<3

**Comment by steveukx** [comment]
No problem

**Comment by michael-ts** [comment]
This approach spits this warning to the console:

    Git#then is deprecated after version 1.72 and will be removed in version 2.x
    Please switch to using Git#exec to run arbitrary functions as part of the command chain.

I'm not sure what I need to do to make this warning go away.

**Comment by michael-ts** [comment]
Also, I don't know if this is related, but the response is always *undefined* making the call useless.

**Comment by steveukx** [comment]
The `.then` method shows this warning to inform you to use `.exec` instead when you have required in `simple-git`, to avoid confusion with a promise based interface.

To use promises, switch to including `simple-git/promise` as used in my example above.
