### ISSUE TITLE
ssh options of StrictHostKeyChecking=no, how can I do?

### ISSUE THREAD

**Issue by Chalin-Shi** [steveukx/git-js#221]
If I want to set `ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no`

Then for example:
`git.status(options)` 
maybe equal to 
`ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no git status`

How can I do?

**Comment by steveukx** [comment]
You should be able to use the `customBinary` option, from the readme:

> .customBinary(gitPath) - sets the command to use to reference git, allows for using a git binary not available on the path environment variable

```
const git = require('simple-git');
git()
  .customBinary('ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no git')
  .status(options, (err, result) => { ... });
```

I've not tested using a custom binary that contains spaces though, if you have problems you may need to [change the way the child processes are spawned](https://github.com/steveukx/git-js/blob/172af0a6929e5bd26d83db93b50ca0a840e71b03/src/git.js#L1287). If you do, please submit a pull request or add some detail to this issue so I can fix it.

**Comment by Chalin-Shi** [comment]
Thank you.

**Comment by Chalin-Shi** [comment]
I use like this:
`const git = git().customBinary('GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git')`
But have an error:
```shell
{"_baseDir":"/Users/shichenglin/Desktop/office/cluster","_runCache":[],"ChildProcess":{},"_command":"GIT_SSH_COMMAND=\"ssh -o StrictHostKeyChecking=no\" git"}
Error: spawn GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by steveukx** [comment]
Unfortunately the `customBinary` option won't work as it needs to be the binary itself - I will make a change to support passing environment variables through to the child process shortly.

**Comment by Chalin-Shi** [comment]
Good job.
