### ISSUE TITLE
What about git clone with SSH 

### ISSUE THREAD

**Issue by mariano-calandra-xp** [steveukx/git-js#223]
I tried to look at the example, but I haven't see nothing clear.

Does this functionality miss?

**Comment by steveukx** [comment]
As this is just a wrapper of the standard `git` binary, you can use any supported remote path:

```
// https
git().clone('https://github.com/steveukx/git-js.git', (err, result) => { });

// git ssh
git().clone('git@github.com:steveukx/git-js.git', (err, result) => { });
```

There is currently no support for authentication that requires user input, so if you are using SSH and haven't yet accepted the ssh key for that host the clone will fail. You should make sure that when using the terminal / a command prompt you can clone with SSH without needing to enter any other details.

**Comment by YikaJ** [comment]
@steveukx When I try to clone a repo with `ssh://` prefix , it fails in git-js.
```
ssh://git@github.com:8080/steveukx/git-js.git
```

I got this error
```
Couldn't find remote ref refs/heads/undefined
```

It works in my iTerm2, so I try to use `git.raw(['clone', url])`, I got the same error.
