### ISSUE TITLE
Failed taking global config after version upgrade

### ISSUE THREAD

**Issue by KnightNoder** [steveukx/git-js#225]
After the version upgrade, when committing files , error pops up saying the user identity is found.
**
Please tell me who you are

Although, local and global user email is already set.

**Comment by steveukx** [comment]
Hi, a few questions...

- Is this after upgrading `git` or upgrading the `simple-git` library? 
- Which versions have you gone from and to?
- If you manually run `git commit -m "commit message"`  in the terminal, what output do you see?

**Comment by KnightNoder** [comment]
It is after the upgrade of simple-git from 1.79.0 to 1.83.0

Its working when commiting manually.

**Comment by steveukx** [comment]
Thank you for letting me know - the new `.env` method was replacing the default `process.env` properties for the child process. It's now resolved and available as version `1.84.0` on npm.

**Comment by KnightNoder** [comment]
Thanks you :+1:
