### ISSUE TITLE
When use in docker, git commit throw an error

### ISSUE THREAD

**Issue by chalince** [steveukx/git-js#228]
I am very strange.

When use in docker, git commit throw an error:
```shell
"*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: unable to auto-detect email address (got 'root@6c7eab544bc5.(none)')
"
```
But ehhh, I am already write the `git config` command in the Dockerfile.
So I run ` git config -l`, the result like this: 
```shell
[root@6c7eab544bc5 ~]# git config -l
user.email=web@aaa.com
user.name=web
```
Can you tell me why? Thanks.

PS: My version is 1.84, and I also test in 1.85

**Comment by steveukx** [comment]
To see the config that would be used when you're running through `simple-git` please run:

```
const gitP = require('simple-git/promise');

gitP().raw(['config', '-l']).then(data => console.log(data));
```

(switch out my `gitP()` above for however you construct your `simple-git` instances to ensure you are using the same environment variables, also you should ensure the script is being run as the same user as the commit script would normally run as).

**Comment by douglas-gibbons** [comment]
A way around the issue is to add this to your Dockerfile (substituting USER/DOMAIN.COM/USERNAME as required).

RUN git config --global user.email "USER@DOMAIN.COM" && git config --global user.name "USERNAME"

**Comment by auto-store** [comment]
would like a way around this without adding to Dockerfile. If many different users are pulling the image then pushing to different repositories, it isn't too suitable
