### ISSUE TITLE
TypeError .cwd() is not a function

### ISSUE THREAD

**Issue by bliu13** [steveukx/git-js#230]
`
const simpleGit = require('simple-git/promise');

simpleGit.cwd('./test').add('*')
    .then(function(data) {
      console.log(data);
    })
    .catch(function(err) {
      console.log(err);
    });
`

I am trying to use .cwd() based on what the documentation is saying, but the node is complaining about cwd not being a function.

**Comment by steveukx** [comment]
To set the working directory, you need to have first called the `simpleGit` function. The easiest way would be to just set the working directory as you first call it:

```
const gitP = require('simple-git/promise');

gitP('./test').add('*')
  .then(data => console.log(data))
  .catch(err => console.error(err));
```

The alternative would be to use the promise chain:

```
const gitP = require('simple-git/promise');
const git = gitP();

git.cwd('./test')
  .then(() => git.add('*'))
  .then(data => console.log(data))
  .catch(err => console.error(err));
```

**Comment by bliu13** [comment]
This is exactly what I needed. I was a little unsure whether how I was able to use cwd() but this clears it up. Thank you.
