### ISSUE TITLE
Parsing issue with multi line commit message

### ISSUE THREAD

**Issue by drschwabe** [steveukx/git-js#231]
Issue with author_name happening on certain commits: 

Here's what simple git  returns as the commit object: 
```javascript
{
  "hash": "a7b15d22b051bc1683953f7e4948c1e55cb54537",
  "date": "2018-01-05 20:47:33 +0900",
  "message": "Minor tweak to latest campaign test",
  "author_name": " use custom tape branch with t._isOnly property",
  "author_email": "Derrick Schwabe"
}
```
( `author_name`  and `author_email` are incorrect) Here's the plain text for this commit from git log: 
```
commit a7b15d22b051bc1683953f7e4948c1e55cb54537
Author: Derrick Schwabe <admin@nerdbusiness.com>
Date:   Fri Jan 5 20:47:33 2018 +0900

    Minor tweak to latest campaign test; use custom tape branch with t._isOnly property
    
    -remove link attr if campaign successful

commit a63b8106efbe1016e43028f279a727c7f3051555
....```

From about 78 commits on this particular repo this issue happens on 6 of them.   
Any more details needed just lmk !

**Comment by steveukx** [comment]
Thank you for the detail... please can you also let me know which command you're using to get to the commit log.

**Comment by drschwabe** [comment]
Ah, just pinpointed the issue more specifically it happens whenever a semicolon is used in the first line of a commit ! 

All of those other 5 commits have semicolons in the first line.  

semicolons can be fun :)

**Comment by steveukx** [comment]
That would do it... you can supply a custom splitter in the options argument though:

    git.log({ splitter: '::' }, (err, log) => {});

**Comment by drschwabe** [comment]
Right on thanks !

**Comment by garyking** [comment]
Thanks, I had the same problem with semicolons in the commit message. The solution fixed it. May I ask how this works, and if it works, then why is this not the default setting? I assume it causes other problems if enabled, and if so, what are those? Thanks!
