### ISSUE TITLE
Clone specified branch

### ISSUE THREAD

**Issue by ElectroDr3am** [steveukx/git-js#239]
Is it possible to clone specified branch of remote repo using promices?

**Comment by steveukx** [comment]
You can supply arbitrary arguments with the `options` array:

```
const REPO_PATH = 'https://path-to.git';
const gitP = require('simple-git/promise');
const git = gitP();

git.clone(REPO_PATH, ['-b', 'some-branch'])
  .then(result => { ... })
```

**Comment by joepagan** [comment]
@steveukx it would be create if you could update your docs, which suggest that you would need to nest multiple arrays here...

What you have said above (and I have just found that works):
```js
git.clone('remote-repo', 'local-path' ['-b', 'some-branch'])
```

From your docs:
```js
.clone(repoPath, [localPath, [options]], [handlerFn])
```

I would have thought this would mean I would need the following which resulted in strange behaviour for me:
```js
git.clone('remote-repo', ['local-path' ['-b', 'some-branch']])
```
