### ISSUE TITLE
Use of Git-Js with Electron

### ISSUE THREAD

**Issue by Akin909** [steveukx/git-js#241]
Firstly thanks for the awesome package, compared with alternatives `git-js` is so easy to use, supports promises and has types! ✨ 

I'm currently looking to try and integrate the package into an electron project [`Oni.vim`](https://github.com/onivim/oni)  in onivim/oni#1310 but (caveat here this could/ is very likely related to my misunderstanding re electron) but when using the package in development it works perfectly and I'm able to accomplish what I intend however when I build and create a packaged version of the application and for example call `git(workingDir).diffSummary()` I just get the original `Git` object back, I've been banging my head against the wall with this issue but from the source code it seems that `git-js` works as a wrapper around `child_process` git commands which if I implement myself in the project work without issue.

This might not exactly be the best place for an Issue ?electron repo but I wonder if there's any potential reason for the observed behaviour i.e. why return the original object and not execute the command, what might result in that, I've tried specifying a `.customBinary('explicit/path/to/my/local/git)` which unfortunately made no difference. Another difference between my attempts to replicate similar functionality just using child process is that I've used `exec` which I see has been switched out for `spawn` in git-js.

Any info would be super helpful (again apologies if this is more electron related than a specific issue of this package)

**Comment by steveukx** [comment]
Hi, depending on how you create the git object, you will either get the instance or a promise back so you can chain commands together:

```
const workingDir = __dirname;
const git = require('simple-git');

git(workingDir).diffSummary((err, diff) => {
  // diff is an instance of the DiffSummary
});
```

Alternatively use promises:

```
const workingDir = __dirname;
const gitP = require('simple-git/promise');

gitP(workingDir).diffSummary()
  .then((diff) => {
    // diff is an instance of the DiffSummary
  })
  .catch((err) => {  });
```

**Comment by micnil** [comment]
@Akin909 was your issue ever resolved? I was looking for alternatives for NodeGit to run in an electron app, but if this doesn't work in a packaged electron app, then maybe it's no point in trying?

**Comment by Akin909** [comment]
@micnil I think my issue could very well be with how I'm importing the package tbh haven't had much time to tinker with it further, maybe give it a try as I can't see any reason why it wouldn't/didn't work

**Comment by Akin909** [comment]
@steveukx, I've done some debugging I think I'm getting different results once I build because of [this](https://github.com/steveukx/git-js/blob/0770825ba9c111ce0affc353c7b3514aee01a7ef/promise.js#L59) line in `promise.js`, not entirely sure what the regex is checking  for (seems to check that what is returned is *not* a promise otherwise it just returns the api)but I think I'm hitting that as I've tried the callback based version of the methods and those work fine, not sure if the built and minified version of our code is generating different async code output than expected.

I tried calling the require and passing it a dir separately rather than awaiting the whole thing in line like `await git(dir).diffSummary()` but tbh that just seems to fail entirely

**Comment by Akin909** [comment]
Just wanted to leave a resolution note here for anyone who stumbles on this. Turns out the project's webpack config was actually bundling the dependencies and minifying it all which was mangling the functionality, added it to our externals in our webpack config to prevent that which resolved the issue. e.g.

```js
externals: {
	"simple-git/promise": "require('simple-git/promise')"
}
```
