### ISSUE TITLE
Git reset a single file

### ISSUE THREAD

**Issue by mwpowellhtx** [steveukx/git-js#244]
``.reset`` in its current form may work for me, but it would be more precise if I could specify a single file.

**Comment by steveukx** [comment]
From the docs:

> resets the repository, the optional first argument can either be an array of options supported by the git reset command or one of the string constants...

Based on this, you can call `.reset(['--hard', 'commitish'])` or any other set of parameters you'd normally use with the [git reset](https://git-scm.com/docs/git-reset) command.

**Comment by mwpowellhtx** [comment]
@steveukx Thanks, will try that.
