### ISSUE TITLE
git.tag not working or may be asynchronous

### ISSUE THREAD

**Issue by mwpowellhtx** [steveukx/git-js#245]
I've got a set of tags, literally:

```
$ git tag
1.4.1
```

However, ``tags.latest`` is reporting undefined. Or at least my expectation that the callback be evaluated prior to return. But it seems to be running asynchronously...

```JavaScript
var tag;
git.tags((err, tags) => {
    if (err) { throw err; }
    console.log(tag = tags.latest);
});
console.log(tag || "no tag was found.");
```

Do I follow it on with a chained ``.then(...)``, or along these lines?

**Comment by mwpowellhtx** [comment]
The problem for me is that I cannot use the ``await suchAndSuch()`` approach because my environment only supports language level ECMAScript 5. Is there a way I can safely wait for the scheduled operation to complete?

**Comment by steveukx** [comment]
Hi

All functions in this api are asynchronous, they either take a callback as the final argument (as shown in your extract above) or return a promise (when you've required it as `simple-git/promise`).

Examples of both versions can be found in the readme.

**Comment by mwpowellhtx** [comment]
@steveukx Okay. Since I provided a callback, shouldn't that be evaluated before the function returns? From my usage in the above case, I am receiving *"no tag was found."*, not the tag I expected.

**Comment by steveukx** [comment]
By the nature of asynchronous programming, the callback can be called at any point in the future, the next line however will be called synchronously following the call.

In the context of this library, please expect all callbacks to be called asynchronously rather than synchronously.

**Comment by mwpowellhtx** [comment]
@steveukx Yes, I realize that about async calls.

So the question remains, how can I string together invoking ``git.tags`` in such a way that it blocks? *ECMAScript 5* is my constraint so keywords like await are not available.

Potentially, I dig into the issue of migrating away from Visual Studio 2015 for this purpose toward an Eclipse based solution, ostensibly, but that is beyond the scope of these issue(s).

**Comment by steveukx** [comment]
How do you handle other asynchronous calls  - for example `setTimeout` or anything that uses promises? The use of callback functions is ES5, and has no need for ES6 or async/await.

**Comment by mwpowellhtx** [comment]
In this instance, I think the boundary of your async state is broken and needs to be the callback. In other words, block until the callback is handled. Otherwise the result is meaningless, indeed useless, *undefined*, to the caller, as I demonstrated in the above snippet.

**Comment by mwpowellhtx** [comment]
I will also add, based on your test cases, you do not see this issue because your assertions happen ***WITHIN THE CALLBACK***. I challenge you to pull those assertions outside the ``git.tags`` call in order to expose the issue more abruptly to your tests.

**Comment by steveukx** [comment]
The API for this library is not intended to be synchronous, so assertions made outside of the callback aren't applicable to the library's use case.

With respect, perhaps you would be better suited finding a library that runs the child process synchronously rather than asynchronously.

To conclude these discussions - I do have a test case set for the next release that will cater for binary files in the response to a diff summary. If you're still using the library when the next release is published, you should find that to be a suitable solution for #243

**Comment by mwpowellhtx** [comment]
@steveukx Fair enough. I decided to run with a package called [crc2json](http://www.npmjs.com/package/crc2json) instead on the front end of whether I am copying a new package or updating an existing package, as contrasted with chasing my tail feathers (or yours) over ``git+tag`` or ``git+diff`` changes are detected. So far so good. Even with that the asynchronous model takes a bit of getting used to without formal ES support.
