### ISSUE TITLE
git.commit not working followed by git.tag

### ISSUE THREAD

**Issue by mwpowellhtx** [steveukx/git-js#246]
I'm sorry to pile on like this, but ``git.commit`` is not working, followed closely by ``git.tag``.

```JavaScript
var commitAndTagPackage = () => {
    var pkg = json.sync(".../path/to/my/package.json");
    var version = pkg.version;
    console.log("committing package: " + version);
    git.commit("publishing package version " + version,
        err => {
            if (err) {
                throw err;
            }
            console.log("tagging package: " + version);
            git.tag([version, "--force"], err => {
                if (err) {
                    throw err;
                }
            });
        });
};
```

I commented out the ``git.tag``, and the ``git.commit`` still did not work. This is all happening after I set the *working directory* appropriately.

I added the file(s) that I wanted to commit and then it seemed to work. So for whatever reason the parent call wasn't gathering the files quite right.

``git.tag`` after that works fine.

**Comment by steveukx** [comment]
Hi, please can you elaborate on "did not work" - does it throw an error?

If you haven't added any files to be committed, git will return something similar to this:

```
git commit -m "commit message"
On branch master
Untracked files:
	some-file-name.ext

nothing added to commit but untracked files present
``` 

In this case when you use simple-git's `commit` you will get a `CommitSummary` instance back that reports zero changes, try changing to:

```js
var commitAndTagPackage = () => {
    var pkg = json.sync(".../path/to/my/package.json");
    var version = pkg.version;
    console.log("committing package: " + version);
    git.commit("publishing package version " + version,
        (err, commitSummary) => {

            if (err) throw err;  

            if (!commitSummary.changes) throw new Error('No tracked files were found to be committed');

...
```

**Comment by mwpowellhtx** [comment]
I ended up refactoring some bits of my Gulp tasks in order to leverage the subsequent calls from within the respective callbacks, and this seems to have resolved the issue. Sorry for the confusion.
