### ISSUE TITLE
Should fail if git not found

### ISSUE THREAD

**Issue by romski** [steveukx/git-js#248]
Feature request

Git is a requirement to using simple-git - simple-git should fail quickly when git is not available.

Thanks

**Comment by miracle7** [comment]
Holy crap thank you for leaving this comment, I spent a full 20 minutes trying to debug why this wasn't working, turns out I only had SourceTree embedded git on this machine!

**Comment by steveukx** [comment]
Hi, if `git` is unavailable, you should see every command you run fail and show an error along the lines of `spawn git ENOENT` in the error string.

I've added a note to the readme for the next release that mentions this - if you think it needs to be made more clear please submit a PR.
