### ISSUE TITLE
Create TypeScript definitions

### ISSUE THREAD

**Issue by jamestharpe** [steveukx/git-js#249]
I'm using simple-git in a TypeScript project and it would be great to have the TypeScript definitions available via NPM (e.g. `npm install @types/simple-git`).

**Comment by seanhealy** [comment]
The project already has initial built in typings for the promise side of things. As added here: 
https://github.com/steveukx/git-js/pull/163/

However, they don't seem to be quite complete as I'm seeing the following methods missing from them:
- `reset`
- `clean`
- `commit`
- `raw`

**Comment by JoshMcCullough** [comment]
Those exist in the TS definition now.
