### ISSUE TITLE
clean() does not allow d or x options

### ISSUE THREAD

**Issue by jamestharpe** [steveukx/git-js#251]
I need to run simpleGit.clean("fdx") (`git clean -fdx`) but it throws an error:

>  Git clean mode parameter ("n" or "f") is required

The `-d` and `-x` options should be supported.

**Comment by steveukx** [comment]
Hi, you can use these with the options array parameter:

```
simpleGit.clean('f', ['-d', '-x'], (err) => { ... });
```

I will do an update shortly that allows options other than the `n` and `f` options in the mode though.
