### ISSUE TITLE
Type definition in TypeScript 2

### ISSUE THREAD

**Issue by miyatin0212** [steveukx/git-js#256]
Hi. I tried this library and would like to ask you a question.
(I have already solved my problem, so this is not emergency.)

## Situation

- TypeScript 2.6.2
- simple-git 1.92.0
- Visual Studio Code
- Windows 10

## Problem

I installed simple-git on my application, Then I wrote some code like the following.

```
import * as simplegit from 'simple-git';

let git = simplegit('./');
```

In this code, Visual Studio Code doesn't suggest me the completion. After viewing this repository, I noticed that simple-git does not have the definition for the normal interface (e.g. interface with callbacks like `git.checkIsRepo(b => { /* .. */ })` ), but have for the promise interface!

So I tried the following code and confirmed the auto-completion works.

```
import * as simplegit from 'simple-git/promise';
```

## Question

- Why the type definition of the promise one has been already implemented in advance of the normal one?
- Type definition for the normal interface will come in the future?

Sorry for my poor English. regards.

**Comment by viceice** [comment]
I think this can be closed, as the types are included now
