### ISSUE TITLE
How to get the progress of the clone？

### ISSUE THREAD

**Issue by flftfqwxf** [steveukx/git-js#265]
my code:

    
```
  const git = require('simple-git/promise');
    git().outputHandler((command, stdout, stderr) => {
            stdout.pipe(process.stdout);
            stderr.pipe(process.stderr);
        }).clone(post.projectPath, importPath, ['--depth=2', '--verbose']).then((val) => {
            console.log('clone done');
            return 'clone done';
        }).catch((e) => ctx.error(e, 500))
```

The console output:
```
POST git-upload-pack (171 bytes)
POST git-upload-pack (180 bytes)
```
But, command line run this command:

`git clone http://xxx/Web/xxx.git --verbose --depth=2
`
It's output:

```
POST git-upload-pack (171 bytes)
POST git-upload-pack (180 bytes)
remote: Counting objects: 383, done.
remote: Compressing objects: 100% (364/364), done.
Receiving objects:  16% (62/383), 3.29 MiB | 831.00 KiB/s    

```

How to get the progress?
Like this:

```
remote: Counting objects: 383, done.
remote: Compressing objects: 100% (364/364), done.
Receiving objects:  16% (62/383), 3.29 MiB | 831.00 KiB/s    
```

**Comment by KevinLeigh** [comment]
Hey @flftfqwxf @patrickalima98 

Currently I use below to display clone progress ->

```
const simpleGit = require('simple-git/promise');

const git = simpleGit(folderPath).outputHandler((command, stdout, stderr) => {
  stderr.on('data', (data) => {
    if (data) {
      process.stdout.clearLine();
      process.stdout.cursorTo();
      process.stdout.write(data.toString('utf8'));
    }
  });
});

try {
  await git.clone(cloneUrl, ['--progress', '--verbose'])
} catch(e) {
  // handle clone error
}
``` 

Above method should update existing progress and not display a new line per progress update.

**Comment by mittalyashu** [comment]
I am getting data something like this in console, which is not really helpful.

![image](https://user-images.githubusercontent.com/29014463/56639323-0eba7280-668e-11e9-824b-a71cbb605000.png)

When we try `console.log(data)`, it output the data in some kind of numbers.

![image](https://user-images.githubusercontent.com/29014463/56639395-34e01280-668e-11e9-921f-68cca53b8ffc.png)

Is there any other way to get the progress of the clone?

**Comment by steveukx** [comment]
Hi, you can now configure `simple-git` with a `progress` handler to receive progress updates on any `git` operation that supports them - https://github.com/steveukx/git-js#progress-events

If you have any problems using the new api, please do open another issue.
