### ISSUE TITLE
.branch() returns wrong list

### ISSUE THREAD

**Issue by SteveyPugs** [steveukx/git-js#266]
When running the command its returning removed local branches that are no longer on remote as well.

**Comment by steveukx** [comment]
Hi, please can you supply the code you're using to generate the list of branches and the output you see if you run that same command via a console/terminal window?

**Comment by SteveyPugs** [comment]
Here is the sample of the code.
```
var simpleGit = require('simple-git')(GIT_REPOSITORY);
simpleGit.branch(function(err, brances){
	if(err) console.log(err);
	else console.log(brances.all)// brings back remote branches already deleted
});
```
Example List
```
GIT_REPOSITORY
[ 'develop',
  'master',
  'remotes/origin/feature/1',
  'remotes/origin/feature/2',
  'remotes/origin/feature/3' ]
```
In the above list develop, master and feature/3 all exist in the remote. feature/1 and feature/2 do not. I have done fetches and prunes to make sure its clean too.

**Comment by steveukx** [comment]
Running `git.branch` with no arguments will under the covers run `git branch -av`. If you run this directly in terminal / the command line, do you see the same result?

**Comment by SteveyPugs** [comment]
@steveukx this is what I thought it was doing. I can tell you, in fact, I do not get that list. I get a list like:

```
develop
master
remotes/origin/feature/3
```

That list is showing the proper list vs. the incorrect one which I sent before.

**Comment by SteveyPugs** [comment]
I get 
```
develop
master
remotes/origin/feature/3
```

Mind you I am using windows so its cmd

**Comment by SteveyPugs** [comment]
The issue still persists in 8.11.4.
