### ISSUE TITLE
Having trouble pushing changes

### ISSUE THREAD

**Issue by Rambou362** [steveukx/git-js#267]
Hi, I'm having trouble pushing changes to a repo.
This is what I have:
```js
const git = require("simple-git");
const remote = `https://${username}:${password}@github.com/Rambou362/test`;
 git("test").push(remote, ["-u", "origin", "master"]);
```

I get this problem instead:
```log
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin master
```

I hope someone can help me out. Thanks in advance.

**Comment by steveukx** [comment]
Hi

There are two accepted forms for using `git.push` - either `git.push(remote, branch, [options, [callback]])` or `git.push([options, [calback]])`.

Try switching to:

```
const git = require("simple-git");
const remote = `https://${username}:${password}@github.com/Rambou362/test`;

git("test").push([remote, -u", "origin", "master"], (err, result) => {
  err && console.error(err);
  err || console.log('done: ', result));
});
```

From the look of your error message, you may also need to configure (once) a default branch for your repo - you can currently do that with the `git.raw` method, for example:

```
git.raw(['config', '--global', 'push.default', 'simple'], (err, done) => {});
```

**Comment by balvinder294** [comment]
hey i am also having same issue , i am adding like this my local git configuration, but it is stll asking for the same 
`        simpleGitPromise
            .addConfig('user.email',`${userEmail}`)
            .addConfig('user.name',`${nameOfUser}`)`

`*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect e-mail address (got 'balvinder@balvinder-Lenovo-ideapad-320-15ISK.(none)')`
