### ISSUE TITLE
TypeError: Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by ricardotulio** [steveukx/git-js#272]
## Context
When git function is called passing an non-existent directory, the following error is trowed:

```
TypeError: Cannot read property 'constructor' of undefined
```

## Expected behavior
I guess this error could be encapsulated by message that explain directory don't exists.

## Steps to reproduce
Add 'simple-git' as project dependency and try to run the following snippet:

```js
const git = require('simple-git/promise')
const nonexistentDir = '/null/'

git(nonexistentDir) // TypeError: Cannot read property 'constructor' of undefined
```

## Technical info
Node version: v10.1.0

**package.json:**

```
{
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.4",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2015": "^6.24.1",
    "eslint": "^4.19.1",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-jest": "^21.15.2",
    "jest": "^22.4.4"
  },
  "dependencies": {
    "bluebird": "^3.5.1",
    "ramda": "^0.25.0",
    "simple-git": "^1.95.0"
  }
```

**Comment by steveukx** [comment]
Hi, thank you for opening the issue - this looks to be the same issue some other people are having so have opened a general issue as #279. Please watch that space for updates

**Comment by aleung** [comment]
@steveukx Don't feel it's same issue as #279. I don't use babel and got this error on node.js 9 without using babel.

Read source of `promise.js`, the issue is because `git` is still undefined while error is caught. 

``` js
   try {
      git = require('./src')(baseDir);
   }
   catch (e) {
      chain = Promise.reject(e);
      // `git` is still undefined
   }

   return Object.keys(git.constructor.prototype).reduce(function (api, fn) {
                   // ^^^^^^^^^^^^^^^ error
      // ...
   }, {});
```

**Comment by xu8511831** [comment]
I have the same problem. I also don't think it's the same issue as [#279](https://github.com/steveukx/git-js/issues/279) .

**Comment by peterhuson** [comment]
Yeah this is not the same issue as #279, @aleung describes it above. It would be helpful to throw the below error [here](https://github.com/steveukx/git-js/blob/05dfa57c7d343afdb0c3fbab69e0039cef6c7ae1/src/index.js#L11) rather than an unclear error:
`throw new Error("Cannot use simple-git on a directory that does not exist.");`
