### ISSUE TITLE
Also track .staged files

### ISSUE THREAD

**Issue by rhalff** [steveukx/git-js#277]
I'm currently using git-js to add some modified files to git.

I would like to be able to retrieve the status before I do this and ensure no files are staged yet,
currently this does not seem possible.

When I run the command manually I do notice it could be possible to also track the staged files,
because those are the M's which are not indented with a space.

```bash
$ git status --porcelain -b -u
## master...origin/master
 M package-lock.json
 M package.json
 M packages/chix-flow/src/sandbox/node.ts
M  packages/chix-loader-fs/package.json <------- staged
 M packages/chix-loader-remote/package-lock.json
M  packages/chix-loader-remote/package.json <--- staged
 M packages/chix-runtime/package.json
 M tools/getDependenciesList.ts
 M tools/loadPackages.ts
 M tools/updateDeps.ts
?? tools/getDependencies.ts
?? tools/getDependencyList.ts
?? tools/releaseAll.ts
?? typings/semversion/index.d.ts
?? yarn.lock
```
Ideally I would like to get access to a `.staged` property on the returned status object.

The main problem at the moment is the status codes are trimed and the status code information is not passed on to the handlers.

**Comment by steveukx** [comment]
Hi, thank you for the PR - this is now available on npm as 1.96.0
