### ISSUE TITLE
is "git reflog" supported ?

### ISSUE THREAD

**Issue by engmagdy87** [steveukx/git-js#280]
is `git reflog --date=local <branch-name>`  supported ?

**Comment by lashower** [comment]
Unfortunately, I ran a grep on the code and did not see any references to reflog.

**Comment by steveukx** [comment]
Good to know! If ever you do find a git command (or series of arguments that you can't see how to add with one of the provided methods of this library) you can always use `git.raw(...)` to run any arbitrary git command - see https://github.com/steveukx/git-js#complex-requests

I'll close for now, but please feel free to make a pull request to add it as a new feature of the library.
