### ISSUE TITLE
Starting with 1.95 types are broken again

### ISSUE THREAD

**Issue by vladbarosan** [steveukx/git-js#282]
after updating to 1.95 the TS types are broken again.

**Comment by lashower** [comment]
I am using these commands with 1.96 with no issues.
```
var promise = git(directory).pull(null).then(git(directory).submoduleUpdate.bind(null,['--init','--recursive']));

git(directory).status().then(result => {
	result.success = true;
	result.name = repo.substring(repo.lastIndexOf('/')+1,repo.lastIndexOf('.'));
	result.dir = directory;
	result.branch = result.current;
	result.url = repo;
	git(directory).log().then(logDetail => {
		result.date = logDetail.latest.date;
		console.log(result);
	}).catch(err => {
		console.log(result);
	});
});
```

Maybe update to 1.96 or send some logs or examples of your issue.

**Comment by steveukx** [comment]
As the library isn't currently written in TS, they can get out of synch. Which interfaces are not working for you?

**Comment by aendrew** [comment]
Oh also btw types are also broken in TS 3.x 😩 

`ReadableStream` is now `NodeJS.ReadableStream`. Keeping these up-to-date is like playing whack-a-mole, I'm sure...
