### ISSUE TITLE
log from non-ancestor lists symmetric difference - should list simple difference

### ISSUE THREAD

**Issue by csemrau** [steveukx/git-js#286]
We are trying to get a list of commits that are part of a feature branch, but not yet part of the master branch. Using `git log master..feature` yields those commits, regardless of whether the master branch contains additional commits. Is it possible with simple-git?

The simple-git `log` command logs a commit range given by `opt.from + "..." + opt.to`, with 3 dots. This produces the symmetric difference, containing all commits from `from` not in `to` together with all commits from `to` not in `from`.

I expect to get a log of all commits in `to` that are not also in `from`, which you would get when giving the range with only 2 dots, `opt.from + ".." + opt.to`.

In the current implementation, that makes `from` and `to` interchangeable and yields unexpected results whenever `from` is not an ancestor of `to`.

As an example, take the following history:

    A --- B --- C (master)
     \     \
      \     \-- D (feature)
       \    
        \-- E

The command `git log master..feature` lists only `D`, because that is the only commit that is in the history of `feature` and not also in the history of `master`. Similarly, `git log master..feature` lists only `C`, the only commit on `master` that's not yet in `feature`.

Whereas `git log master...feature` lists both `C` and `D`, because these two commits are not common to both (like `A` and `B`) or absent from both (like `E`). This is also the result of the simple-git `log` call with `{from:'master', to:'feature'}`.

**Comment by Guobacai** [comment]
This feature is useful in some cases. Is there any plan on adding this feature?

**Comment by csemrau** [comment]
We had worked around this by not providing `from` and `to` as options, but by providing the `from..to` expression as an option, like this.

        // This is a hack - simpleGit will just append
        // the keys of the `options` object to the command
        // if the value is not of type string (or equal to some special keys)
        const options = {
            ...
        };
        // We therefore just construct the path-spec as a special key
        const pathSpec = `${fromHash}..${toHash}`;
        options[pathSpec] = null;
        this.git.log(options, ...);

I still think it's a bug that simple-git returns the symmetric difference instead of the simple difference. If backwards compatibility is an issue, maybe a new option `symmetric` with default value `true` could be added. To get the simple difference, one would then provide options `{ from: ..., to: ..., symmetric: false }`.

**Comment by Guobacai** [comment]
Thanks @csemrau 
It seems like adding "symmetric" is not that hard.

**Comment by steveukx** [comment]
You can add extra command line arguments using the usual [how-to-specify-options](https://github.com/steveukx/git-js#how-to-specify-options). There is now a test is [test-log.js](https://github.com/steveukx/git-js/blob/master/test/unit/test-log.js#L271) that shows how to add the options in.

If you would like to have a new custom option for setting some properties, please feel free to modify [git.js](https://github.com/steveukx/git-js/blob/master/src/git.js#L1257-L1260) accordingly and open a PR.

If you would like for this to go on the backlog for my input, please can you add a test in `test-log.js` that shows how you want to supply arguments to the function, and the expected command line output.

**Comment by steveukx** [comment]
Fixes in #352 are now in NPM as version 1.113.0
