### ISSUE TITLE
Possibly broken typings for branch command

### ISSUE THREAD

**Issue by nwalters512** [steveukx/git-js#292]
`branch` is typed as having a required argument, but it seems to function just fine without one. Are these typings intentional? Otherwise, I'd be happy to submit a PR updating the types to make the argument optional.

```ts
branch(options: string[] | Options): Promise<BranchSummary>;
```

**Comment by steveukx** [comment]
Apologies this went unnoticed for so long - the definitions were updated in 1.132.0, and for all versions 2.0.0 onwards.
