### ISSUE TITLE
Get full commit message

### ISSUE THREAD

**Issue by garyking** [steveukx/git-js#299]
Is there any way to get the full commit message, including all lines, rather than just the first, using this package? Could this otherwise be added?

**Comment by steveukx** [comment]
In order to look into this for you, please can you add which command are you using at the moment along the output of the `simple-git` command and the equivalent when run on the console / terminal. Thanks.

**Comment by garyking** [comment]
The command I'm using: `.log({ master: null, splitter: '::' })`

The output of the above command:

```
ListLogLine {
    hash: 'd47c6433928a504da3c6363b3f9f7b2707846b04',
    date: '2018-09-10 02:17:58 -0400',
    message: 'Use wait-on for waiting for the bundle HTML file',
    author_name: 'Gary King',
    author_email: 'email@gmail.com' },
```

The output from `git log master` in Bash:

```
commit d47c6433928a504da3c6363b3f9f7b2707846b04
Author: Gary King <email@gmail.com>
Date:   Mon Sep 10 02:17:58 2018 -0400

    Use wait-on for waiting for the bundle HTML file

    To be created by Webpack
```

**Comment by sn0opr** [comment]
Up this is usefull

**Comment by dschep** [comment]
another option is to use `git.raw(['show', '--format=%B'])`

**Comment by steveukx** [comment]
Apologies for the lack of reply before... it was always possible to get the multi-line body by passing a custom format ([example](https://github.com/steveukx/git-js/blob/v1.119.0/test/unit/test-log.js#L77)), but it is now supported as an option to the `git.log` method (an example of which is in the [test](https://github.com/steveukx/git-js/blob/v1.119.0/test/unit/test-log.js#L32)).

```
const log = await gitP.log({ multiLine: true });

console.log(log.latest.message) // the subject of the commit, always a single line
console.log(log.latest.body) // the body of the commit, can include carriage returns when multiLine is true

```
