### ISSUE TITLE
`stashList` only returns the first stashed item

### ISSUE THREAD

**Issue by garyking** [steveukx/git-js#300]
In a simple test, `stashList` only returns the first stashed item.

I'm calling it with `.stashList()`. 

`git stash list` in Bash returns:

```
stash@{0}: On master: another change to test
stash@{1}: On master: changes to test
stash@{2}: On master: a
```

Yet this package's method returns:

```
ListLogSummary {
  all:
   [ ListLogLine {
       hash: '87657f9cb7fc3e102822134f848d76c1cb9d515b',
       date: '2018-09-10 15:01:59 -0400',
       message: 'On master: another change to test (refs/stash)',
       author_name: 'Gary King',
       author_email: 'email@gmail.com\n27d0367c373a1f2ca17841af67e9c32b0d7c35c2' } ],
  latest:
   ListLogLine {
     hash: '87657f9cb7fc3e102822134f848d76c1cb9d515b',
     date: '2018-09-10 15:01:59 -0400',
     message: 'On master: another change to test (refs/stash)',
     author_name: 'Gary King',
     author_email: 'email@gmail.com\n27d0367c373a1f2ca17841af67e9c32b0d7c35c2' },
  total: 1 }
```

Also is there any way to remove the ` (refs/stash)` and `\n27d0367c373a1f2ca17841af67e9c32b0d7c35c2` from the `author_email`? I used `\n` as a splitter which worked. The `27d` hash is from the next stash.

If I run the command from [this line](https://github.com/steveukx/git-js/blob/05dfa57c7d343afdb0c3fbab69e0039cef6c7ae1/src/git.js#L165) like so: `git stash list --pretty=format:'%H %ai %s%d %aN %ae'`, then I get:

```
87657f9cb7fc3e102822134f848d76c1cb9d515b 2018-09-10 15:01:59 -0400 On master: another change to test (refs/stash) Gary King email@gmail.com
27d0367c373a1f2ca17841af67e9c32b0d7c35c2 2018-09-10 15:01:34 -0400 On master: changes to test Gary King email@gmail.com
02fdcc0284f3f9d82b532cf2a95990ed75b6e7f2 2018-09-10 14:59:55 -0400 On master: a Gary King email@gmail.com
```

**Comment by steveukx** [comment]
Thank you for the detail - there was a bug in how the command was built up before being passed to the parser. A fix has been merged and will be published to npm today
