### ISSUE TITLE
How to properly use with Typescript?

### ISSUE THREAD

**Issue by JoshMcCullough** [steveukx/git-js#306]
Using v1.100.0, can you show how to properly import and use simple-git with Typescript? I can import it as `import simplegit from "simple-git"`, which correctly points to `typings/promise/index.d.ts`, however, the `main` property in `package.json` points to `./src/index.js` which is incorrect, since the typings are based on `./promise.js`. So TS compiles okay, but when running and executing, e.g. `git(<path>).status().then(...)`, it is executing `Git.prototype.then` instead of the `then` on the promise returned from the async version of `status()`.

That's a mouthful, I know, TL;DR need to point to the async wrapper for TSD to work.

**Comment by steveukx** [comment]
Thank you for opening this... you should now find you can use:

```
import * as simplegit from 'simple-git/promise';

const git = simplegit();
git.status().then((status: StatusSummary) => { ... })
```

I've pushed a change [1.102.0](https://www.npmjs.com/package/simple-git/v/1.102.0) that moves the d.ts file to the correct location. Please let me know if you have further issues.

**Comment by JoshMcCullough** [comment]
Thanks, will give it a go.
