### ISSUE TITLE
Enhancements to PullSummary

### ISSUE THREAD

**Issue by davidmerfield** [steveukx/git-js#308]
Thank you for working on this library. I've been using it in production on [Blot](http://blot.im/) with decent results.

It would be useful to see renamed files in ```PullSummary```. As it stands, this library only shows the rename in the ```files``` property of ```PullSummary``` as a string which looks like: ```a.txt => b.txt```. Because long paths in ```files```  are truncated by Git, that string is not particularly useful.

I have tried a number of flags and strategies to get changes git considers renames into the ```created``` and ```deleted``` properties of PullSummary. None of these attempts worked.:
- The first I tried was ```git.addConfig('merge.renames', 'false', function(err){ ... })``` before pulling. 
- Fetching then merging with ```{'--strategy=recursive': true, '-Xno-renames': true}``` instead of pulling. Neither of these techniques affected the PullSummary.

Will try to get a pull request going to amend the ```deleted``` and ```created``` properties of ```PullSummary```.

**Comment by davidmerfield** [comment]
Ah, it now transpires that the full paths of updated files are not included in ```PullSummary``` either. So my current strategy to get useful information about a particular pull is to do this: 

```
git.raw(['rev-parse', 'HEAD'], function(err, beforePull){
  git.pull(function handlePull (err) {
    git.raw(['rev-parse', 'HEAD'], function(err, afterPull){
      git.raw(['diff', '--name-status', '--no-renames', beforePull + '..' + afterPull], function(err, res){
        var added = [];
        var modified = [];
        var deleted = [];
        
        res.split('\n').forEach(function(line){
          if (line[1] !== '\t') return;
          if (line[0] === 'A') {
             added.push(line.slice(2));
          } else if (line[0] === 'M' ) {
            modified.push(line.slice(2));
          } else if (line[0] === 'D') {
            deleted.push(line.slice(2));
          } else {
             debug('Nothing found for line:', line);
          }
... 
```

**Comment by geosp** [comment]
I was having an issue where the paths were truncated in the pull summary. My work around looks like this:

```js
          await git.fetch()
          let diffInfo = await git.diff([
            '--stat=1000',
            'feature/proposed_structure...origin/feature/proposed_structure',
          ])
          await git.pull()
          let pullInfo = PullSummary.parse(diffInfo)
          let { files } = pullInfo
```
This works because the stats option in diff increases the default of 80 characters for the file path to whatever the option specifies. This yields the expected results. Looks like all the code needed to fix my issue is already there. 
@davidmerfield @steveukx Do you have any opinion regarding what we need to do? I want to submit a PR for my issue and would like your feedback. My fix will be to convert the pull command to a fetch, diff, and the a pull returning the parse pull info from the diff since the option is not available from the pull. 

Thank you for your time.

**Comment by steveukx** [comment]
Apologies for not having replied to this sooner... from your code sample it appears that you would achieve the same result by using the `git.diffSummary(...)` method (which has its line length set to 4096):

```typescript
const summary = await git.diffSummary(['feature/proposed_structure...origin/feature/proposed_structure']);
```
