### ISSUE TITLE
code execution vulnerability

### ISSUE THREAD

**Issue by Gottox** [steveukx/git-js#31]
This module should not be used with any user input as it is very easy to inject code:

```
~/src/git-js(master ✗) node -e "require('./src/git.js')('.').add('\";echo HELLO WORLD > foo\"')"
~/src/git-js(master ✗) cat foo 
HELLO WORLD
~/src/git-js(master ✗) 
```

**Comment by steveukx** [comment]
Good call, switched over to `ChildProcess.spawn` for argument escaping, if you notice anything broken in release `1.0.0`, feel free to submit a pull request.
