### ISSUE TITLE
Question - specify SSH key

### ISSUE THREAD

**Issue by margeson** [steveukx/git-js#311]
First, thank you for this contribution.

I would like to use this module with a Lambda function.

Any idea on how I can specify an SSH Key?

Right now, I have the contents of an SSH key stored in a VAR that's populated by a secure method.

**Comment by chris-altamimi** [comment]
Did you find your answer? Please don't just close issues that you've resolved without context. Thank you

**Comment by bmitchinson** [comment]
https://github.com/steveukx/git-js/issues/710
