### ISSUE TITLE
error in promise.d.ts

### ISSUE THREAD

**Issue by jerch** [steveukx/git-js#312]
Using the promise interfaces for typescript throws an error:

```
> tsc

node_modules/simple-git/promise.d.ts:245:12 - error TS2371: A parameter initializer is only allowed in a function or constructor implementation.

245       init(bare = false): Promise<void>;
               ~~~~~~~~~~~~
```

Maybe line 245 should just be `init(bare: boolean): Promise<void>;` ?

**Comment by steveukx** [comment]
This is now resolved by #310 and #315, available as version 1.103.0 on npm
