### ISSUE TITLE
Handler function for most of the API?

### ISSUE THREAD

**Issue by murtuzasyed** [steveukx/git-js#313]
I'm just curious regarding the purpose of the callback/handlerFn. Is there any scenarios where they can be used? I use the callback for mergeFromTo where I'm doing push after the merge within the callback.

**Comment by steveukx** [comment]
If you're using `simple-git` the trailing function in each step of the chain is optional and if present will be called with `function (err, data ) { ... }` where err is any error that was thrown by attempting to run the command and data is either the string returned by running the git command or the parsed response where you are using a method that has a parser.

If you are using `simple-git/promise` then there are no trailing functions, each method returns a promise either rejected with an error or resolved with the data (see above).

If you paste in some code I should be able to help further.
