### ISSUE TITLE
boolean promise in `checkIsRepo` gets rejected

### ISSUE THREAD

**Issue by jerch** [steveukx/git-js#314]
Calling `checkIsRepo` returns a `Promise<boolean>` according to the interface definition.

Current behavior: If the folder in question is not a within a git repo the promise gets rejected.

Expected behavior: Imho this promise should resolve non repo folders to `false` (its an expected result and should therefore resolve, I'd reject here only on unexpected errors).

**Comment by steveukx** [comment]
To look into this for you, please include the output of running the following in the working directory you run `simple-git` in:

```
git rev-parse --is-inside-work-tree
```

(If you are using a custom binary, replace `git` with whichever binary you have configured `simple-git` to use).

You should find that the command prints either `true` for a directory contained within a `git` root, or something similar to `fatal: not a git repository (or any of the parent directories): .git` when not in a directory contained within a git root.

Either of those responses resolves the promise with a boolean. Any other error will reject the promise as it is indicative of some other kind of error.

**Comment by jerch** [comment]
Yupp I get this fatal message when trying with a non repo folder, but localized in german - maybe thats the reason? Here is the message:
`fatal: Kein Git-Repository (oder irgendeines der Elternverzeichnisse): .git`

**Comment by steveukx** [comment]
Thank you for providing the text - this is now added as a test for the failure case and is available on npm as 1.1.04.0

**Comment by jerch** [comment]
Thx alot, works! :+1: 

Not sure if you will run into localization hell, once other stumble over this. Maybe this needs an upstream fix to git itself to get a simple `true|false` from the switch?
