### ISSUE TITLE
problem detecting git branch (simpleGit(dir).branchLocal())

### ISSUE THREAD

**Issue by Ardeshir81** [steveukx/git-js#317]
HI!
there is a problem in:

```
simpleGit(dir).branchLocal((err,branch)=>{
  branch
});
```

it just detects the branch sometimes :)

![image](https://user-images.githubusercontent.com/5755214/46671603-0e6ef400-cbe2-11e8-9a84-f423f884aa87.png)

this does the reproduction:
https://gist.github.com/Ardeshir81/7d387a4205be0f685d7a435766f266d4

**Comment by steveukx** [comment]
Hi, thank you for the bug report.

There is currently a non-deterministic bug in the example as you run two asynchronous tasks in a single promise, resolving whenever the first has completed so it isn’t certain that both directories will have been set up before the test runs:

https://gist.github.com/Ardeshir81/7d387a4205be0f685d7a435766f266d4#file-reproduce-bug-js-L29

I can look at this later in the week, but you may find it useful to use the integration test section of this repo to set up the two repos before running the tests against them, for example 
https://github.com/steveukx/git-js/blob/master/test/integration/test-parallel-requests.js#L6

**Comment by Ardeshir81** [comment]
Alright! Thanks for the feedback. I will get into what you told me tomorrow, but I just add this that:
- as it is logging my console.log, and actually calling my callback, so I expect it to have finished the job of getting local branch. Yep I agree with you that the asynchronous thing is misleading me/us from the root cause, and also I did lots of `git init|add|commit` stuff and it makes it more weird. The real use case I was into was that I had six repositories and I wanted to check if all of them are in the same branch, and noted that the last one (and only the last one, even if I changed the order of my repos to check, still the last one) was empty about 80% of the times I executed the code. there was no Promise, no commit, init, etc... stuff. just a for loop (which I share the code tomorrow). In my case at work, if I added something like this at the end of the file, the problem would be solved:
```
setTimeout(()=>{},10);
```

Strange!
Thanks for caring!
I will also dig more if I could at work!

keep up the good work :+1:

**Comment by Ardeshir81** [comment]
P.S: I also solved the problem of two asynchronous promises:
https://gist.github.com/Ardeshir81/7d387a4205be0f685d7a435766f266d4

now the `only the last one scenario ` occurs : )

**Comment by Ardeshir81** [comment]
Hey there!
Here the piece of code I tolja `bout:

![image](https://user-images.githubusercontent.com/5755214/46734542-69672080-cca0-11e8-8d8a-c9c969647a53.png)

Notes:
- the async/await thing is due I `utils.promisify`ed your branchLocal function. It is the same with the callback thing
- If I remove that setTimeout, I get that 80% of the time, last branch is empty bug, but if the timeout is there, everything's just fine.

Thanks!

**Comment by steveukx** [comment]
I've added [integration tests](https://github.com/steveukx/git-js/blob/integration-test-concurrent-commands/test/integration/test-concurrent-commands.js#L40-L49) to the project to cover this scenario. Unfortunately it's showing me that the `ChildProcess` returns no data for "some" commands when there are many concurrent spawned processes (ie: the test occasionally passes, but usually fails on command 5 or above).

One way to work around this for now would be to use a chain instead of running them all concurrently:

```
const dirs = ['first', 'second'];
const branches = await dirs.reduce((chain, dir) => {

return chain.then((branches) => {
  branches.push(await git(dir).branchLocal());
});

}, Promise.resolve([]));

// branches is now an array of BranchSummary instances

```

(Nb: code not checked for syntax errors etc, but so you get the idea)

**Comment by Ardeshir81** [comment]
Yep! Thanks for the care & also for workaround. It is less **delay**atic than my timeout :)

BTW, I would consider this issue as closed (or `almost` resolved), but I've got a question if you would take the time ^ _ ^
To be honest, some concept & some pieces of code of your [comment](https://github.com/steveukx/git-js/issues/317#issuecomment-428549633) & your [commit](https://github.com/steveukx/git-js/commit/103e507f6d24564ed9b9c7c663e73f50a367aafc) was beyond my knowledge & my ability to understand :) and I have this doubt that: are you suggesting this may be a bug/bad behavior of `childProcess`?

**Comment by steveukx** [comment]
Spawning "many" (in my testing it was anything over 6) child processes cause the exit & close events to return in the wrong order.

Please retry with version 1.105.0 which should resolve this issue. If it persists, please can you follow the pattern in [test-concurrent-commands](https://github.com/steveukx/git-js/blob/master/test/integration/test-concurrent-commands.js) to create a failing test case.
