### ISSUE TITLE
Request: Add option for silent errors

### ISSUE THREAD

**Issue by shellscape** [steveukx/git-js#32]
Great module, we're using it with great success.

I'd like to request a small feature addition - the ability to silence the error output to console. We're using this in an environment where we're curating our console output very carefully to deliver a clean experience for our build tools. We're already catching the errors that are thrown should there be an error in the git child process, so we don't need the extraneous console output.

This line here is the culprit: https://github.com/steveukx/git-js/blob/master/src/git.js#L627

Cheers

**Comment by steveukx** [comment]
Good call - warnings were already being removed in a production environment, the error message is now too. To ensure nothing gets printed through `console.error`, set the environment variable `NODE_ENV` to `prod` or `production`. Available in [npm](https://www.npmjs.com/package/simple-git) as version 1.1.0

**Comment by shellscape** [comment]
@steveukx much appreciate the quick action on this, however there's a problem with that approach. we're using this module within a development environment as a compliment to our build tools. setting the node env to production isn't correct for that scenario, and could cause issues within other modules looking to that envar. This module is heavily suited to be used in build tools, which is most definitely a development environment.

**Comment by steveukx** [comment]
As far as I've seen, using NODE_ENV with the value production is fairly standard practice, so I'm planning on keeping that for consistency between the warning and error level logs. 

Before I merge this in, would you like to have a look at https://github.com/steveukx/git-js/compare/master...silence to see if that gives you the functionality you're after?

**Comment by shellscape** [comment]
that pretty much nails it. thank you for implementing this!

**Comment by steveukx** [comment]
No worries, published as 1.2.0 on [npm](https://www.npmjs.com/package/simple-git)
