### ISSUE TITLE
Support for options on ".tags()"

### ISSUE THREAD

**Issue by lghamie** [steveukx/git-js#322]
I'd like to be able to use "-n" for example, to get the annotated tag message.

Thanks!

**Comment by steveukx** [comment]
Sorry for the (very) slow reply, but for completeness... the method was changed to be `git.tag([options, [callback]])` back in [1.70.0](https://github.com/steveukx/git-js/releases/tag/1.70.0) with the optional `options` argument supplied in the format documented in https://github.com/steveukx/git-js#how-to-specify-options
