### ISSUE TITLE
Does this lib support --amend option?

### ISSUE THREAD

**Issue by mrdulin** [steveukx/git-js#323]
I read the docs, but don't find any information about how to use `--amend` option.

```bash
git commit --amend -m 'new comment'
```

How do I use `--amend` option? thanks

**Comment by steveukx** [comment]
You can add arbitrary options using a trailing options argument (in the docs https://github.com/steveukx/git-js#how-to-specify-options):

```
git.commit('new comment', {'--amend': null}, (err, summary) => { ... })
```

**Comment by mrdulin** [comment]
@steveukx Thanks.
