### ISSUE TITLE
Can't create an instance of SimpleGit in Typescript

### ISSUE THREAD

**Issue by Kareylo** [steveukx/git-js#324]
Hi,
As I'm trying to get simple-git working with typescript, I try to clone a repository if my baseDir doesn't exists

If dir exists and trying to fetch and pull, everything's alright

Here my code :

```ts
import { existsSync } from 'fs-extra'
import simplegit from 'simple-git/promise'

export class GitService {
  private git: simplegit.SimpleGit
  private readonly path: string
  private readonly repo: string

  constructor () {
    this.path = process.env.GIT_PATH
    this.repo = process.env.GIT_REPO

    if (!existsSync(this.path)) {
      simplegit().silent(true).clone(this.repo, this.path).catch()
    }

    this.git = simplegit(this.path).silent(true)
  }

  public async getLastVersion () {
    await this.git.fetch()
    return this.git.pull('origin', 'master')
  }

  public getPath (): string {
    return this.path
  }
}
```

While trying to get instance of simplegit to make my clone, I get this error : 
```
projectPath\node_modules\simple-git\promise.js:58
   return Object.keys(git.constructor.prototype).reduce(function (api, fn) {
                          ^
TypeError: Cannot read property 'constructor' of undefined
    at Object.module.exports [as default] (projectPath\node_modules\simple-git\promise.js:58:27)
    at new GitService (projectPath\src\services\GitService.ts:17:25)
    at new Bot (projectPath\src\Bot.ts:30:23)
    at Object.<anonymous> (projectPath\src\index.ts:22:13)
    at Module._compile (module.js:652:30)
    at Module.m._compile (projectPath\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (projectPath\node_modules\ts-node\src\index.ts:442:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

Any idea how I can resolve this problem ?

**Comment by Ore4444** [comment]
This is the way I made it work

```
import simplegit, {SimpleGit} from 'simple-git/promise'

export class GitService {
  private git: SimpleGit
}
```

Of course, you need to have in your tsconfig.json

```
{
    "esModuleInterop"             : true,
    "allowSyntheticDefaultImports": true,
}
```

**Comment by Steven4294** [comment]
does not work for me

**Comment by Steven4294** [comment]
```
error TS2503: Cannot find namespace 'NodeJS'.
node_modules/simple-git/promise.d.ts
```

**Comment by brianwestphal** [comment]
seems you need to do something like:
```
import simplegit, { SimpleGit } from 'simple-git/promise';
…
const git: SimpleGit = simplegit();
…
git.cwd(GIT_WORKING_DIR);
```

**Comment by YikaJ** [comment]
it works for me
```
import simpleGit from 'simple-git/promise';
```

**Comment by sittingbool** [comment]
For me running `npm i simple-git` installs the typedef woth a package.json that says on _from `git+https://github.com/types/simple-git.git` which is a different repo

**Comment by sittingbool** [comment]
Okay that actually happend when you tried to additionally install @types/simple-git despite gettting an error. What fixed it was a `npm un simple-git --save` and then reinstall just the `simple-git` but weird...

**Comment by basickarl** [comment]
`import { default as simpleGit, SimpleGit } from 'simple-git/promise';`
Error:
`default not found in 'simple-git/promise'eslint(import/named)`

**Comment by basickarl** [comment]
Jesus fucking schrist, restarted VSCode, now it works... TypeScript and VSCode, not the most stable of products...

**Comment by steveukx** [comment]
You can import the constructor and types from `simple-git/promise` using:

```
import gitP, { SimpleGit } from 'simple-git/promise';

export const run = async () => {
    const git: SimpleGit = gitP();
    console.log('This is', (await git.checkIsRepo()) ? '' : ' not', ' a git repo.');
};
```

Which works in my current test script based on:

```
"dependencies": {
  "@types/node": "^13.7.7",
  "simple-git": "^1.131.0",
  "typescript": "^3.8.3"
}
```

**Comment by sudhagar10** [comment]
The above snippet works. But I am getting lint failure, `error  No default export found in imported module "simple-git/promise"  import/default`

**Comment by steveukx** [comment]
In order to look into that for you, please include your import statement as well as the error. Thanks

**Comment by josecelano** [comment]
I'm using ESLint and I was getting this error: 

```
SimpleGit not found in 'simple-git'           import/named
```

- eslint 8.8.0
- simple-git 3.1.1

I solved it by replacing:

```
import simpleGit, {SimpleGit} from 'simple-git'
```

by:

```
import simpleGit from 'simple-git'
import {SimpleGit} from 'simple-git/typings'
```

**Comment by steveukx** [comment]
As this has been added to an issue relating to a different major release of the library, please can you create a new issue and include the version of TypeScript are you using? Thanks

**Comment by josecelano** [comment]
> As this has been added to an issue relating to a different major release of the library, please can you create a new issue and include the version of TypeScript are you using? Thanks

@steveukx I'm not going to create the issue for the time being. I've created a [new repo](https://github.com/josecelano/simple-git-and-eslint) from scratch in order to try to reproduce the error I was not able to reproduce it with the same `typescript`, `eslint` and `simple-git` versions.

**Comment by josecelano** [comment]
Finally, I found the solution. It was a missing plugin in the [ESLint configuration](https://github.com/josecelano/simple-git-and-eslint/blob/main/README.md#how-to-fix) (`"plugin:import/typescript"`).
