### ISSUE TITLE
missing options for rm method

### ISSUE THREAD

**Issue by ole3021** [steveukx/git-js#326]
During the remove process, i may want to remove a folder and all nested files of it. 

so i may execute `rm -r xxxxxx`. but from the API there is no options for me to add `-r` as parameter for the `rm` command. could you please add it, or there are other way can remove a folder and all files under of it?

**Comment by steveukx** [comment]
Hi, the `rm` methods need a little work to make them more in line with the more modern parts of the library, until that's done you can use the `raw` api instead:

```
// with async:await
const gitP = require('simple-git/promise');
await gitP(workingDir).raw(['rm', '-r', ...files]);

// without callbacks
const git = require('simple-git');
git(workingDir).raw(['rm', '-r', ...files], (err, data) => { ... });
```

**Comment by ole3021** [comment]
that's fine. and hope it can be in the lib soon.  Thx for your help. Love this lib.
