### ISSUE TITLE
How to login as another user and using that user as author in commit message 

### ISSUE THREAD

**Issue by cwtuan** [steveukx/git-js#328]
```
       const simpleGit = require('simple-git/promise');
       // Using platformAccount
        const remote = `http://${platformAccount}:${platformPassword}@${repo}`;
        const git = simpleGit();
        yield git.clone(remote);
        yield git.merge([ '--no-ff',`origin/${source_branch}`]);
        yield git.push(remote); // git push by using platformAccount in remote 
```

I clone repo and push to remote by using `platformAccount`, but when I see the merged commit message on gitlab, the commit user isn't the platformAccount but my local git account.

Tested in v1.107.0.

**Comment by steveukx** [comment]
Any action performed through `simple-git` use the standard git configuration for the user you run the `simple-git` process as, meaning that if you run the `node` script as your user (eg: from terminal / command prompt without having used sudo to run as another user) you will by default be using your own `git config` which has your `user.email` and `user.name` values.

There are a few options detailed in https://stackoverflow.com/questions/4220416/can-i-specify-multiple-users-for-myself-in-gitconfig for either using `git config set ...` in the newly cloned repo, or using templates to automatically set the user details after checkout https://github.com/DrVanScott/git-clone-init

**Comment by cwtuan** [comment]
`git.addConfig` works for me. Thanks!
