### ISSUE TITLE
Passing standard input to raw

### ISSUE THREAD

**Issue by GelaniNijraj** [steveukx/git-js#332]
Is there some way to pass input to the command executed by `.raw` through stdin?

Couldn't find anything in the documentation. Thanks!

**Comment by steveukx** [comment]
Are you looking for `outputHandler` - eg: https://github.com/steveukx/git-js#piping-to-the-console-for-long-running-tasks

**Comment by steveukx** [comment]
Sorry for the super-slow reply btw

**Comment by dmsnell** [comment]
thanks for the quick response @steveukx - I'm using the `...stdIn` pattern now, which I actually only discovered after posting my comment and before seeing yours.
