### ISSUE TITLE
Options are not working in git.show() 

### ISSUE THREAD

**Issue by mittalyashu** [steveukx/git-js#338]
```
const author = await git(this.repo).show([hash], {
				"--format": "%an %n %ae"
			})
```

I have tried passing different options `"--format": "%an %n %ae"`, but every time I get the same output.

I have followed as it is mentioned in the `readme.md`.

![image](https://user-images.githubusercontent.com/29014463/54518904-5b25da80-498b-11e9-8d71-6ceb64d7337e.png)

**Comment by Dar0n** [comment]
Hey @mittalyashu !
Try this passing all options as an array:
`await this.git.show([hash + '^', `--pretty=format:%H`, '--quiet'])`

**Comment by mittalyashu** [comment]
Yeah, passing all the option in the array works, thanks.
