### ISSUE TITLE
Commit on top of a bare repo

### ISSUE THREAD

**Issue by saoudrizwan** [steveukx/git-js#339]
I'd like to host bare repos on my server, and add files to these bare repos without cloning first. It seems this is possible: https://stackoverflow.com/questions/9670302/commit-directly-to-a-bare-repository

Any idea how I could accomplish something like this with simple-git?

**Comment by saoudrizwan** [comment]
If this isn't possible, is there any way I can convert a bare repo to a working directory, make my commits, then convert back to a bare repo?

**Comment by willstott101** [comment]
You can execute the plumbing commands you need using `SimpleGit.raw(...)`.

And example from that SO post might be:
```javascript
myGit.raw(["update-index", "--add", "--cacheinfo 100644", blobOID, fileName])
```
