### ISSUE TITLE
Can I provide a user and password ?

### ISSUE THREAD

**Issue by wiseflat** [steveukx/git-js#34]
Hi,
I am looking for a project like yours.
I would like to clone and pull a private git repository.
Can I provide a user/password with your api ?

**Comment by steveukx** [comment]
It depends on how you intend to do your authentication, you may find these pages useful:

https://confluence.atlassian.com/plugins/servlet/mobile#content/view/282989712

https://help.github.com/articles/creating-an-access-token-for-command-line-use/

Both of these cover how you would configure your environment to pass authentication tails to the remote repo when using git command line tools which is library uses internally.

**Comment by steveukx** [comment]
No further comments so closing this for now.
