### ISSUE TITLE
git-worktree api missing

### ISSUE THREAD

**Issue by HoldYourWaffle** [steveukx/git-js#340]
As far as I can tell there are currently no bindings for [git-worktree](https://git-scm.com/docs/git-worktree).

Have I just not found it or is this not yet implemented? If so, will it be added in the future?

**Comment by steveukx** [comment]
it's not part of the API at the moment, but please feel free to either add a PR to include it, or use the `raw(args[], then)` interface to run an arbitrary command as documented in [complex requests](https://github.com/steveukx/git-js#complex-requests)
