### ISSUE TITLE
feature request: git subtree

### ISSUE THREAD

**Issue by alfonsodev** [steveukx/git-js#341]
Thanks for this package!  
would you be interested to add support for `git subtree` ?

**Comment by steveukx** [comment]
You're welcome :)

Which API are you looking to use? `simple-git` wraps the regular `git` binary - there is no `subtree` in https://git-scm.com/docs

**Comment by bbenoist** [comment]
@steveukx 
* [`subtree` merge strategy](https://git-scm.com/docs/merge-strategies#Documentation/merge-strategies.txt-subtree)
* [subtree concept doc](https://git-scm.com/book/en/v1/Git-Tools-Subtree-Merging)
* [`git subtree --help`](https://github.com/git/git/blob/master/contrib/subtree/git-subtree.txt)

**Comment by xmsz** [comment]
+1
