### ISSUE TITLE
UnhandledPromiseRejectionWarning if baseDir does not exist

### ISSUE THREAD

**Issue by Szellem** [steveukx/git-js#344]
In case of non-existing baseDir an error is thrown at https://github.com/steveukx/git-js/blob/d8dd36dd2bcccf297736718e936ce5c731fc6fb0/promise.js#L52

This error is caught at https://github.com/steveukx/git-js/blob/d8dd36dd2bcccf297736718e936ce5c731fc6fb0/promise.js#L54 and its rejection is appended to a promise chain.

This promise chain is never returned because https://github.com/steveukx/git-js/blob/d8dd36dd2bcccf297736718e936ce5c731fc6fb0/promise.js#L58 also fails with TypeError since git is undefined because of the first error.

So the first error cannot be handled by the client code because it doesn't have access to its promise chain.

**Comment by steveukx** [comment]
Thank you for all the detail. This is now resolved in version 1.112.0 on npm
