### ISSUE TITLE
SHA-1 returned by revparse has an unexpected trailing line end character

### ISSUE THREAD

**Issue by zedaizd** [steveukx/git-js#347]
Steps to reproduce:
```
let repoPath = "";
let repo = require("simple-git/promise")(repoPath);
repo.revparse(["HEAD"])
.then(result => {
    console.log(result.endsWith("\n")); // <----------true
});
```

versions:
node: 8.9.3
simple-git: 1.110.0
git: 2.15.0.windows.1
os: Windows 10 1809 build 17763.437

**Comment by steveukx** [comment]
Thank you for the detailed issue. This is now resolved and available for use in npm as version 1.111.0
