### ISSUE TITLE
Results of git-pull are unreliable

### ISSUE THREAD

**Issue by waddlesplash** [steveukx/git-js#35]
I've gotten `summary` strings with `changes: 100644` (obviously the mode, not the change), file listings with `...` in them, and missing additions/deletions.

Due to how Git formats the output of `pull` (even with `-v`), it might be worthwhile to manually abridge the results of `git diff <before-pull>...HEAD` instead of trying to parse the output of `pull`.

**Comment by steveukx** [comment]
So I can look into this - can you include an example of the results you are getting from the `git pull`?

**Comment by waddlesplash** [comment]
Yeah, actually I did a bit more investigation, and my hacky solution is just to record the hash of the commit before the pull and then run `git diff commit..HEAD --numstat`, as `numstat` is designed for machine consumption and has pretty much all of git-pull stats.

I'll try to come up with a reproducible testcase you can have shortly.

**Comment by steveukx** [comment]
Closing through inactivity, if you'd like to re-open please can you add a failing test case.
