### ISSUE TITLE
Could not fetch escaped ref list

### ISSUE THREAD

**Issue by rarkins** [steveukx/git-js#350]
No matter what I tried, I couldn't get the following to work with `git.fetch` or `git.raw`, so used `git` directly instead:

```js
    async function setBranchPrefix(branchPrefix) {
      const ref = `'refs/heads/${branchPrefix}*:refs/remotes/origin/${branchPrefix}*'`;
      const cmd = `git fetch --depth=2 origin ${ref}`;
      await exec(cmd, {
        cwd: config.localDir,
        shell: true,
      });
    }
```

It seems that the special `'` around the fetch refs was not being "passed through" correctly. Is this unsupported right now?

**Comment by steveukx** [comment]
Hi, I've added a test in `test-fetch.js` that shows how `git.fetch` works with a complex remote that has quotes in the value.

The quoted arguments documented in https://git-scm.com/docs/git-fetch#_pruning (for example) have quotes so the shell knows how to pass them to the git binary without interpreting the special characters in the strings themselves. In `simple-git`, the arguments are passed directly to the git binary in the child process, so they don't need to have quotes to identify them as strings.

To keep this issue open, please create a test based on https://github.com/steveukx/git-js/blob/master/test/unit/test-fetch.js#L27-L37 showing how you are using the library, and what you expect the git command to be, and what data you expect to have returned.

**Comment by rarkins** [comment]
@steveukx thanks for taking a look at this. I did some further reproducing and can confirm that passing the ref *without* the extra quotes does work. Passing it *with* quotes does not work.

Working:
```js
const fs = require('fs-extra');
const gitP = require('simple-git/promise');

const dir = '/tmp/clone1';

const git = gitP(dir).silent(true);

(async () => {
    await fs.remove(dir);
    await fs.ensureDir(dir);
    await git.clone('https://github.com/steveukx/git-js.git', '.', ['--depth=2']);
    var result = await git.branch(['--list', '--remote'])
    console.log(result.all)
    const branchPrefix = 'v2';
    const ref = `refs/heads/${branchPrefix}*:refs/remotes/origin/${branchPrefix}*`;
    await git.fetch(`origin`, ref, ['--depth=2']);
    result = await git.branch(['--list', '--remote'])
    console.log(result.all)
})();
```

Not working:
```js
const fs = require('fs-extra');
const gitP = require('simple-git/promise');

const dir = '/tmp/clone1';

const git = gitP(dir).silent(true);

(async () => {
    await fs.remove(dir);
    await fs.ensureDir(dir);
    await git.clone('https://github.com/steveukx/git-js.git', '.', ['--depth=2']);
    var result = await git.branch(['--list', '--remote'])
    console.log(result.all)
    const branchPrefix = 'v2';
    const ref = `'refs/heads/${branchPrefix}*:refs/remotes/origin/${branchPrefix}*'`;
    await git.fetch(`origin`, ref, ['--depth=2']);
    result = await git.branch(['--list', '--remote'])
    console.log(result.all)
})();
```

Note: the only line that changes is the `const ref =  ...` one.
