### ISSUE TITLE
Fetch error using typescript

### ISSUE THREAD

**Issue by DonsWayo** [steveukx/git-js#357]
Hi, the pull push and other methods work well, but fetch I get this error (using typescript). 

Cannot find module 'XXXX/responses/FetchSummary'
    at webpackEmptyContext (src sync:2)
    at requireResponseHandler (git.js:1592)
    at Git.<anonymous> (git.js:1560)
    at done (git.js:1435)
    at git.js:1460

call:

  const status = await git(TestConstants.TEST_PATH)
      .fetch()
      .then(data => {
        return data;
      });

**Comment by dvallin** [comment]
This has to do with Webpack not bundling dynamic dependencies in the form of
`require(variable)`
which happens in requireResponseHandler (git.js:1592)
As a workaround I downgraded back to 1.96.0 (you might want to actually bisect which version causes the issue)
Perhaps a dev can clarify whether this should be fixed or we should wait for 2.0?

**Comment by steveukx** [comment]
A `git bisect` would be really useful if you have one available.

As the 2.x branch will take me a while longer to have ready to release, there is a new version [1.118.0](https://npmjs.com/package/simple-git) available today that eagerly loads the response handlers, which should mean they are always available in the webpack bundle. 

If the new version doesn't fix this for you, please reopen the issue
