### ISSUE TITLE
is it possible to run ls-remote on a remote repo without cloning?

### ISSUE THREAD

**Issue by victorbadila** [steveukx/git-js#361]
In git you can do operations such as 
```git ls-remote --tags git@bitbucket.org:my-private-repo.git```
 which work without having the repo cloned, as long as git can connect to the source and pass the auth.
Is it possible in any way to do the same with this module?

**Comment by steveukx** [comment]
`simple-git` does require that you give it a valid directory when it is created (defaults to the current working directory), but that doesn't have to be a git working directory and in the case of `ls-remote` it doesn't need to be a clone of the remote you are listing:

```
// assuming async/await in simple-git/promise
const remotes = await git.listRemote(['--tags', 'git@bitbucket.org:my-private-repo.git'])

// assuming ES5 callback style
git.listRemote(['--tags', 'git@bitbucket.org:my-private-repo.git'], function (err, remotes) {
  // ...
});
```
