### ISSUE TITLE
textFileChange regex doesn't match new files without content

### ISSUE THREAD

**Issue by SeeThruHead** [steveukx/git-js#363]
```
   line = line.trim().match(/^(.+)\s+\|\s+(\d+)\s+([+\-]+)$/);
```
input from git diff
```
 eqw  | 0
 flkj | 1 +
 2 files changed, 1 insertion(+)
```
resulting diff summary:
```
DiffSummary {
  files:
   [ { file: 'flkj',
       changes: 1,
       insertions: 1,
       deletions: 0,
       binary: false } ],
  insertions: 1,
  deletions: 0 }
```

maybe something like this
```
^(.+)\s+\|\s+(\d+)\s+([+\-]+)?$
```

**Comment by steveukx** [comment]
To help with creating an integration test for this - how do you go about changing a file such that it has zero changes but is still in the diff? Thanks

**Comment by SeeThruHead** [comment]
unless i'm missing something here
`touch asdf; git add .`
should do it

**Comment by steveukx** [comment]
I thought the same, but both windows `git-bash` and mac os terminal versions of the git binary don't include files changed only by using `touch`:

```
abc $ git init
abc $ Initialized empty Git repository in /private/tmp/abc/.git/
abc $ touch def && echo 'hello' > abc
abc $ git add . && abc $ git commit -m 'initial'
[master (root-commit) c3375c1] initial
 2 files changed, 1 insertion(+)
 create mode 100644 abc
 create mode 100644 def
abc $ 
abc $ echo 'world' > abc
abc $ touch def
abc $ 
abc $ git diff --stat=4096
 abc | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
abc $ 
```

Are you using any other options in the command to include files changed with only their modified timestamp (ie: `touch`)

**Comment by SeeThruHead** [comment]
ok so here's a series of commands
same deal as before
2 new files, one empty
```
bash-3.2$ git add .
bash-3.2$ git diff --stat=4096
bash-3.2$ git diff --stat=4096 head
 bar | 1 +
 foo | 0
 2 files changed, 1 insertion(+)
bash-3.2$
```
my git diff --stat=4096 returns nothing (doesnt seem to default to HEAD)
but my git diff --stat=4096 HEAD returns what i've been seeing

**Comment by steveukx** [comment]
Confirmed that, thanks. If you would like to do a pull request I can have it merged for you, otherwise I will get a fix out for you later this week.
