### ISSUE TITLE
How to add all changes at once?

### ISSUE THREAD

**Issue by lhuangjs** [steveukx/git-js#366]
I want to add all changes at once. I used 
```
this.git.add('*')
        .commit('finish to initialize tuxi')
        .push('origin', 'master')
```
but there is a problem:
```
fatal: pathspec '*' did not match any files
```

**Comment by steveukx** [comment]
In order to look into this, please also include the output of running `git add *` in the terminal from the same working directory as you created the `simple-git` instance, also which version of `simple-git` you are using. Thanks
