### ISSUE TITLE
binaryFileChange regex doesn't match the binaryFiles

### ISSUE THREAD

**Issue by shilin8805** [steveukx/git-js#367]
`line = line.match(/^(.+) \| Bin ([0-9.]+) -> ([0-9.]+) ([a-z]+)$/);`

should be

`line = line.match(/^(.+) \|\s+Bin ([0-9.]+) -> ([0-9.]+) ([a-z]+)$/);`

input from git diff

`doc/_assets/image/client-qrcode1.png                                                     |                Bin 0 -> 9806 bytes`

actually there is more than one space between separator and Bin

**Comment by shilin8805** [comment]
[fixed by this pull request](https://github.com/steveukx/git-js/pull/368)
Merge it?

**Comment by steveukx** [comment]
Hi, thanks for this - merged and now available in [npm](npmjs.com/package/simple-git) as 1.117.0
