### ISSUE TITLE
Cannot find moudle StatusSummary after packaging with electron-builder

### ISSUE THREAD

**Issue by Symbolk** [steveukx/git-js#369]
I am using simple-git in an vue-electron-app, it works well in the development process. However, when I packaged it with electron-builder and started it, the console reported such an error:

```
Uncaught (in promise) Error: Cannot find module 'F:\workspace\dev\SmartCommit\vue-app\dist_electron\win-unpacked\resources\app.asar/responses/StatusSummary'
    at n (src sync:2)
    at a (git.js:1593)
    at s.<anonymous> (git.js:1561)
    at i (git.js:1436)
    at git.js:1461
    at processTicksAndRejections (internal/process/task_queues.js:86)
```

I found a related issue #241 , but the provided solution did not work for me.

Looking for any help!

**Comment by Symbolk** [comment]
@steveukx Sorry to bother, but maybe you have any idea about this problem?

**Comment by steveukx** [comment]
I think this may be related to the same issue as #357 - please can you try with the latest release 1.118.0 and let me know if you still have problems building.

**Comment by Symbolk** [comment]
> I think this may be related to the same issue as #357 - please can you try with the latest release 1.118.0 and let me know if you still have problems building.

Great! It solves my issue, loving this lib~
