### ISSUE TITLE
then() causes TypeError in node v0.10.29 and later

### ISSUE THREAD

**Issue by joel-airspring** [steveukx/git-js#37]
When you use a then() block, you'll get this error with node 0.10.29 and later:

    TypeError: Incorrect value of args option
        at Object.exports.spawn (child_process.js:725:11)
        at Git._schedule (/home/airspring/scratch/node_modules/simple-git/src/git.js:651:40)
        at process._tickCallback (node.js:442:13)

Platform: OSX
simple-git: 1.3.0

It works in:
> 0.10.26
0.10.27
0.10.28

It fails in:
> 0.10.29
0.10.30
0.10.31
0.10.33
0.10.38

I also tested on Linux, and it failed there too with node 0.10.26.
I did not not test node 0.12.x

I'm suspicious of my report since it means this problem has been undetected since node 0.10.29 was released about a year ago:  http://blog.nodejs.org/2014/06/16/node-v0-10-29-stable/  But it's easy to reproduce:

```javascript
if (process.argv.length < 3) {
	console.log('need a path to a git repo');
	process.exit(-1);
}

var path_to_repo = process.argv[2];
console.log('running git status for ' + path_to_repo);

require('simple-git')(path_to_repo)
     .status(function(err, status) {
     })
     .then(function() {
        console.log('status done.');
     });
```

Expected behavior:  'status done' prints out without any errors
Actual behavior:  message is not printed.  The error noted above is seen.

**Comment by steveukx** [comment]
Thanks for the detailed report! This should be resolved with:

    Git.prototype.then = function (then) {
       return typeof then === "function" ? this._run("echo ''", then) : this;
    };

I'll test and publish this evening for you.

**Comment by joel-airspring** [comment]
That change results in this error in the output:

    git: 'echo' is not a git command. See 'git --help'.
    
    Did you mean this?
	    fetch
    
    status done.

**Comment by steveukx** [comment]
That would be where the testing bit comes in ;) The intention is to re-use the existing behaviour in `_run` which is how this one was missed when the behaviour there was changed for r1.x
Failing the reuse of `_run`, it could just be changed to the new format in the `.then` function: `this._runCache.push([["echo", ""], then]);`

**Comment by joel-airspring** [comment]
Guess I was champing at the bit!

I'll wait until you have time to test, etc.

Thanks!
