### ISSUE TITLE
Get the root directory of the git repo

### ISSUE THREAD

**Issue by Symbolk** [steveukx/git-js#370]
Thanks for this nice lib. I found that with git('')._baseDir, it outputs the current working directory, but with git('').status(), the file paths in the output are all relative to the root directory of the repo, instead of the current working directory. This is little different with git-status command, which outputs the file paths relative to the current folder, as shown in the picture ("git s" is my alias for "git status"):

![image](https://user-images.githubusercontent.com/14107297/60500301-ac649a80-9cec-11e9-995b-bd86bedaed51.png)

My question: how to get the root directory of the git repo? Because I need it to get the absolute path of changed files.

**Comment by steveukx** [comment]
The easiest way to detect the directory root of a repo is to use rev-parse's [--show-toplevel](https://git-scm.com/docs/git-rev-parse#Documentation/git-rev-parse.txt---show-toplevel).

```
// assuming async/await in simple-git/promise
const topLevel = await git.revparse(['---show-toplevel'])

// assuming ES5 callback style
git.revparse(['--show-toplevel'], function (err, topLevel) {
  // ...
});
```

**Comment by Symbolk** [comment]
> The easiest way to detect the directory root of a repo is to use rev-parse's [--show-toplevel](https://git-scm.com/docs/git-rev-parse#Documentation/git-rev-parse.txt---show-toplevel).
> 
> ```
> // assuming async/await in simple-git/promise
> const topLevel = await git.revparse(['---show-toplevel'])
> 
> // assuming ES5 callback style
> git.revparse(['--show-toplevel'], function (err, topLevel) {
>   // ...
> });
> ```

Thanks for the reply.

The second way works fine, but the first way outputs not correctly. Here are the code and the output:

```js
const getRootPath = async repo_path => {
  const git = require('simple-git/promise')

  let topLevel = ''
  try {
    topLevel = await git(repo_path).revparse(['---show-toplevel'])
  } catch (e) {
    // handle the error
  }
  return topLevel
}

console.log('1' + git._baseDir)
git.revparse(['--show-toplevel'], function(err, topLevel) {
  if (err) {
    console.log(err)
  }
  console.log('2' + topLevel)
})
getRootPath('').then(rootPath => {
  console.log('3' + rootPath)
})
```
1F:\workspace\dev\SmartCommit\vue-app\src\components\utils
2F:/workspace/dev/SmartCommit
3---show-toplevel```

```

**Comment by steveukx** [comment]
Thank you for the update, I'll get a test in place for that shortly

**Comment by steveukx** [comment]
There is a typo in your test `---show-toplevel` should be `--show-toplevel`. I've added an integration test for this though so you can see it in action: https://github.com/steveukx/git-js/blob/master/test/integration/test-rev-parse.js#L28
