### ISSUE TITLE
What's the difference between "not_added" and "created" of StatusSmmary?

### ISSUE THREAD

**Issue by Symbolk** [steveukx/git-js#373]
I am trying to map the StatusSmmary with the output of original git-status. Most of the arrays are easy to understand, but I am confused between the  "not_added" and "created".

When I create a new file that is not tracked by git, it will appear in the "not_added" array, corresponding to the "Untracked files" of git-status. But under what condition that a file will appear in the "created" array?

**Comment by steveukx** [comment]
`created` is an array of any file that has the status `A` (see https://git-scm.com/docs/git-status#_short_format), in the table of meanings that equates to "added to index". `not_added` are status `??` which equates to a file that is untracked.
