### ISSUE TITLE
Log method parse the output wrong when there is a new line/empty line in the commit message

### ISSUE THREAD

**Issue by rymain** [steveukx/git-js#376]
The returned values are shifted by that new line

**Comment by steveukx** [comment]
Hi, please can you confirm the release version of the library you're using, and include a code extract showing how you're using the library and the output from the equivalent git command when run in terminal / Windows command prompt. Thanks

**Comment by steveukx** [comment]
There is now an integration test to cover the retrieval of multi-line comments in `git.log`. If you are still having problems, please also see the troubleshooting note https://github.com/steveukx/git-js#log-response-properties-are-out-of-order
