### ISSUE TITLE
git log --shortstat put stats in next line

### ISSUE THREAD

**Issue by kobbikobb** [steveukx/git-js#382]
The current implementation will put the shortstat after the separator f.x:
------------------------ >8 ------------------------
 1 file changed, 2 deletions(-)

git log --pretty="format:%H;%ai;%s;%D;%b;%aN;%ae------------------------ >8 ------------------------" --shortstat

This will result in a extra log line and the shortstat hash is shifted by one.

**Comment by steveukx** [comment]
Thank you for the detailed issue report - the log format now includes both start and end tokens so the diff stat / stat summary can also be parsed. The latest version [1.122.0](npmjs.com/package/simple-git) should now include a `diff` property in each `ListLogItem` where you had opted to add a stat in the command, for example:

```
// as part of an option object
git.log({ '--stat': '4096 });
git.log({ '--stat': null });
git.log({ '--shortstat': null });

// as part of an option array
git.log(['--stat=4096']);
git.log(['--stat']);
git.log(['--shortstat']);

```

**Comment by kobbikobb** [comment]
Sweet @steveukx , I will test it out, thank you :)

**Comment by kobbikobb** [comment]
Looking good, thank you :)
