### ISSUE TITLE
When using git log with shortstat, summary for lines of changes is not returned

### ISSUE THREAD

**Issue by kobbikobb** [steveukx/git-js#385]
git log --shortstat
2 files changed, 3 insertions(+), 4 deletions(-)

expected:
diff: {files: [], changes: 2, insertions: 3, deletions: 4}

actual:
diff: {files: [], insertions: 3, deletions: 4}

I have reproduced and solved the bug on my fork. Feel free to use whatever part of it or all :)

**Comment by steveukx** [comment]
Thank you for the detailed issue report.

As the git output uses `changed` rather than `changes` to represent this value, I've kept that name for the property. You will now see:

```
git log --shortstat
2 files changed, 3 insertions(+), 4 deletions(-)

diff: {files: [], changed: 2, insertions: 3, deletions: 4}
```
