### ISSUE TITLE
--allow-empty

### ISSUE THREAD

**Issue by EvanBurbidge** [steveukx/git-js#387]
When trying to retrigger some CI command on git would be nice if we could have access to the --allow-empty commit flag in order to be able to fire up an empty commit.

**Comment by steveukx** [comment]
You can add any supported option to the `commit` function using an options object (see [how-to-specify-options](https://github.com/steveukx/git-js#how-to-specify-options)

```
git.commit('message', { '--allow-empty': null }, (err, data) => { ... })
```
