### ISSUE TITLE
.log() should put option arguments before non-option arguments

### ISSUE THREAD

**Issue by radektheloner** [steveukx/git-js#389]
In some cases, the `.log()` function does not put option arguments before non-option arguments. In such case, the `git` command fails and thus the `.log()` function fails as well.

E. g. (a minimal although a little artificial reproducer), while being in a git repository, run following code:

```js
require('simple-git')().log({file: 'index.js', '--fixed-strings': true}, (err, log) => console.log(err));
```

The actual result is:
> fatal: option '--fixed-strings' must come before non-option arguments

The expected result is:
> `null`

Versions:
Fedora 30
nodejs 10.16.0
simple-git 1.124.0
git 2.21.0

**Comment by steveukx** [comment]
Hi, thanks for reporting this and apologies for the delay in getting back to you. The latest version `1.126.0` explicitly moves the `--follow` option to the end of the command.
