### ISSUE TITLE
How to format date in log()?

### ISSUE THREAD

**Issue by 4ndre4s** [steveukx/git-js#391]
```javascript
const simpleGitPromise = require("simple-git/promise");
let res = await simpleGitPromise(workingDirPath).log({"--date": "iso-strict"});
console.log(res);
```

>      date: '2019-08-23 09:36:10 +0200'

while 

```bash
git log --date=iso-strict
```
prints 

> ...
>  Date: 2019-08-23T09:36:10+02:00
> ...

which is exact ISO 8601 format.

**Comment by steveukx** [comment]
As `simple-git` uses the `--pretty=format:...` to format the response, you would need to supply a format object to replace the default date format `%ai` with the ISO date format `%aI`:

```
let res = await simpelGitPromise(workingDirPath).log({
  format: {
         hash: '%H',
         date: '%aI', // note the upper case I 
         message: '%s',
         refs: '%D',
         body: '%B',
         author_name: '%aN',
         author_email: '%ae'
      }
})
```

The complete set of options that can be used in the format string are in the git docs at https://git-scm.com/docs/git-log#Documentation/git-log.txt-emaIem

**Comment by 4ndre4s** [comment]
That worked, thank you!

**Comment by alexanderwallin** [comment]
Would it make sense to default to a standard format, such as ISO 8601 or its simplified human-readable version returned by `Date.prototype.toString()`? I'm using `moment` to do some formatting and get the following warning:

```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
```

I don't think a third party library should dictate what goes into this package, but standards are handy!
