### ISSUE TITLE
mergeFromTo command does not seem to work or fails silently since v1.79

### ISSUE THREAD

**Issue by arnaudbesnier** [steveukx/git-js#395]
After an upgrade from version 1.78 to version 1.79 (the diff contains changes about merge commands):

```javascript
require('simple-git')()
  .mergeFromTo('unknown branch #1', 'unknown branch #2')
```
now fails silently in v1.79 (vs "merge: unknown branch #1 - not something we can merge" in v1.78)

```javascript
require('simple-git')()
  .mergeFromTo('master', 'devel')
```
does not do anything in v1.79 (was working in v1.78)

Did the signature of the function changed? Did I miss something?
Thanks for your help 🙏

**Comment by breyana** [comment]
I'm having issues with this, too. I don't have any errors appearing. Here's what I have, and I definitely get as far as checking out the "qa" branch, but I can't get any merge to work, including .mergeFromTo

```
git.clone(`${githubLink}/${service}.git`)
            .cwd(`${gitDirectory}/${service}`)
            .checkout("qa")
            .merge(["master"])
```

**Comment by steveukx** [comment]
@breyana have you checked for errors in the merge by using:

```
.merge(['master'], (err, mergeSummary) => {
  if (err) {
    return console.error('merge error', err);
  }

  console.log('merge success', mergeSummary);
})

```

**Comment by breyana** [comment]
Thanks, I haven't tried that yet, but I changed the options and it seems to work now:
`git.merge(["origin", "master"])`

**Comment by LucianU** [comment]
Are we sure the behavior of `mergeFromTo` works as intended? I looked a bit at the source of this function and it seems to be implemented as `git.merge(fromBranch, toBranch, ...otherArgs)`.

But, when I look at the [`git-merge docs`](https://git-scm.com/docs/git-merge#_examples), I see this translates to "Merge these two branches into the current branch".

Am I misunderstanding something?

**Comment by steveukx** [comment]
It does work as intended (see #50) but it's been badly worded from the start... as of the next release (see #634) `from` and `to` will be named `remote` and `branch`.

**Comment by LucianU** [comment]
Oh, I see. Thanks for clarifying!
