### ISSUE TITLE
.log and .raw fail with 'TypeError: Buffer.concat is not a function'

### ISSUE THREAD

**Issue by nojvek** [steveukx/git-js#397]
```
rejected promise not handled within 1 second: TypeError: Buffer.concat is not a function
stack trace: TypeError: Buffer.concat is not a function
```

It seems Buffer is getting overriden. Probably best to use `global.Buffer` so scope doesn't get bessed up.

**Comment by steveukx** [comment]
Hi, apologies for the delay in responding. In order to look into this, please can you include the version of `simple-git`, `node.js` and which operating system you are using.
