### ISSUE TITLE
Support git log --merges

### ISSUE THREAD

**Issue by willwh** [steveukx/git-js#40]
Hi Guys,

This is a nice lib, thanks for your work. I ran in to an issue whereby I wanted to look at just merge changes between branches.

I'm going to push a PR for this shortly (it's really simple) - would love some feedback.

Steps to test:

In your config object, set the following:

```
config.merges: true,
config.branch: qa
```

**Comment by steveukx** [comment]
Hi
Thanks for the PR, I've now closed it as there were no other updates made to it following feedback. You can now use the `.log` function is a more generic way though which will achieve the same result:

````
git.log(
   ['--merges', 'branch..'], 
   function (err, data) {
      // 
   }
)
````

**Comment by DanielRuf** [comment]
This does not seem to be the case anymore. At least the first parameter is now for the options object.
