### ISSUE TITLE
Unexpected console output

### ISSUE THREAD

**Issue by xobotyi** [steveukx/git-js#400]
Tried to make this:
```javascript
import simplegit = require('simple-git/promise');

const repo = simplegit(somePath);

repo.cwd(somePath).then(
  () => repo.checkout('origin/' + branchName).catch(() => {})
);
```

and unexpectedly having output in console (inspite of shallowed error in chatch)
`error: pathspec 'origin/branchName' did not match any file(s) known to git`

**OS**: Windows 10
**Nodejs**: 11.15.0
**simple-git**: 1.126.0

**Comment by steveukx** [comment]
This error would be generated if `git ` was unable to resolve the supplied branch spec... do you need to `repo.fetch()` first?

To prevent logging errors to the console, switch to silent mode using `repo.silent(true)`.
