### ISSUE TITLE
Add method to check if Git is installed

### ISSUE THREAD

**Issue by MaximDevoir** [steveukx/git-js#402]
**Current Behavior**

A developer wants to use a `simple-git` method, but may need to check if `git` is installed to avoid an `Error: spawn git ENOENT` error (see [`ENOENT` section](https://github.com/steveukx/git-js/blob/03ba7548890263b10170b7ef1960f11636d91dfe/readme.md#every-command-returns-enoent-error-message)).

The developer could create a check to see if `git is installed. Like this:

```TypeScript
import spawn from 'cross-spawn'

function isGitInstalled(): boolean {
  const command = spawn.sync('git', ['--version'], {
    stdio: 'ignore'
  })

  if (command.error) {
    return false
  }
  return true
}

```

However, this situation seems common enough to where we could probably add a method to check for Git on the system.

**Proposed Behavior**

Add a method (e.g. `.installed()`, `.isGitInstalled()` etc.) that checks if Git is installed on the computer.

**Comment by michapixel** [comment]
https://github.com/steveukx/git-js/issues/410#issuecomment-584187606

**Comment by samuela** [comment]
Instead of `isGitInstalled()` I think it would be more useful to have a method to check the git CLI version, and throw an error if git is not found in PATH.

**Comment by steveukx** [comment]
From version `3.14.0` you can now use the git.version() interface to check for the version and presence of git:

```typescript
import { simpleGit } from 'simple-git';

const {installed} = await simpleGit().version();
if (!installed) {
  throw new Error(`Exit: "git" not available.`);
}
```

docs: https://github.com/steveukx/git-js/blob/main/examples/git-version.md

(thank you for the suggestion on this issue @samuela)
