### ISSUE TITLE
Check whether git is installed on system?

### ISSUE THREAD

**Issue by abladze** [steveukx/git-js#410]
Is there a way to check whether Git is installed on the system or not?
I know this is not an "Issue" but i read the docs and there seems to be no way to do so. I am new to JavaScript so please take it easy on me if I'm missing something obvious.

**Comment by michapixel** [comment]
`npm i command-exists` 
```
const commandExists = require('command-exists').sync;
if( !commandExists('git') ) {
	console.log('Git not installed');
	return false;
}
```

**Comment by steveukx** [comment]
From version `3.14.0` you can now use the `git.version()` interface to check for the version and presence of `git`:

```typescript
import { simpleGit } from 'simple-git';

const {installed} = await simpleGit().version();
if (!installed) {
  throw new Error(`Exit: "git" not available.`);
}
```

docs: https://github.com/steveukx/git-js/blob/main/examples/git-version.md
