### ISSUE TITLE
Some types of file merge conflicts aren't reported in merge/status

### ISSUE THREAD

**Issue by Blasz** [steveukx/git-js#419]
The `merge` command is reporting 'modify/delete' merge conflicts incorrectly in the merge summary.

E.g. 
```
CONFLICT (modify/delete): foo/bar.js deleted in origin/master and modified in HEAD. Version HEAD of foo/bar.js left in tree.
```
produces a merge conflict of `MergeConflict { reason: 'modify/delete', file: 'tree.' },`

Additionally, the `status` command does not report these files as conflicted at all.

**Comment by steveukx** [comment]
Thank you for the pull request, this is now on npm as version 1.130.0
