### ISSUE TITLE
Invalid Date format setting for log ()

### ISSUE THREAD

**Issue by liby** [steveukx/git-js#422]
- Simple-git Version: ^1.129.0
- NodeJS Version: 13.6.0

- Problem description
    - The parameters passed to the log method according to the configuration items described in the [git-log Documentation](https://git-scm.com/docs/git-log#Documentation/git-log.txt---dateltformatgt) are not working properly

- Screenshot
![image](https://user-images.githubusercontent.com/38807139/72789955-98c05780-3c6f-11ea-83d7-319ff60c6455.png)

- Wanted help
    - So is there a problem with the way I pass parameters?
    - Or is the log method not parsing the argument correctly?

**Comment by steveukx** [comment]
Hi, you are supplying the `--date` option in the correct way, but the [git documentation](https://git-scm.com/docs/git-log#Documentation/git-log.txt---dateltformatgt) says that the `--date` option is only applied when using the appropriate `--pretty` flag to return results in a human-readable format.

In order for the `simple-git` library to parse the response, it uses its own `--pretty` value derived from the options you pass in in the `format` object. There are many examples of the format object in either the [unit](https://github.com/steveukx/git-js/blob/master/test/unit/test-log.js] or [integration](https://github.com/steveukx/git-js/blob/master/test/integration/test-log.js) tests, where you can supply any of the placeholders from the [official documentation](https://git-scm.com/docs/git-log#_pretty_formats)

**Comment by liby** [comment]
![image](https://user-images.githubusercontent.com/38807139/72807915-5f014800-3c93-11ea-8467-400effe6e166.png)
@steveukx Thanks for your timely reply. Everything is normal now!
