### ISSUE TITLE
mark required arguments as required in the documentation

### ISSUE THREAD

**Issue by Matthias-Hermsdorf** [steveukx/git-js#423]
This script worked well @1.124.0

```
 git()
  .add('./*')
  .commit(`Build ${currentVersion}`)
  .addTag(`v${currentVersion}`);
```

But updated to @1.129.0 the tags were not added any more. By trial&error I discovered that the handler as second argument was optional before and is now required, even if it is emtpy.

This script works well.

```
  git()
  .add('./*')
  .commit(`Build ${currentVersion}`)
  .addTag(`v${currentVersion}`, () => {});
```

It would be nice if you mark the optional arguments as optional or the required as required in the documentation.

**Comment by steveukx** [comment]
Hi, I'm not sure why you are seeing the error you have described above - the `addTag` method hasn't been changed since version `1.73.0` which was back in 2017.

If you include stack traces / errors you're seeing in the console / the full script being used, I may be able to offer some help.

**Comment by Matthias-Hermsdorf** [comment]
Thanks for your offer.

It fails silently. There are no errors. 

I use a node 10.15.0 on win10. This doesn't change in between.
git version 2.24.0.windows.2

In a node repl I can do following:

```
const git = require('simple-git');
git().addTag("newTag"}) // nothing happens
git().addTag("newTag", () => {}})  // the tag gets added
```

**Comment by steveukx** [comment]
Thank you for the additional detail - I've added a fix along with an [integration test](https://github.com/steveukx/git-js/blob/master/test/integration/test-tag.js#L16-L36) so this shouldn't happen again. You can now use `addTag` without a callback in version 1.131.0

**Comment by Matthias-Hermsdorf** [comment]
Thanks for the fix.
