### ISSUE TITLE
Can't specify http.extraheader

### ISSUE THREAD

**Issue by ermshiperete** [steveukx/git-js#424]
I'm trying to implement the equivalent of

```bash
git -c http.extraheader="Authorization: Basic $TOKEN" push $REMOTE $BRANCH
```

However, the following doesn't work:

```nodejs
git.raw([
  '-c',
  `http.extraheader="Authorization: Basic ${token}"`,
  'push',
  remote,
  branch,
]);
```

I get a `The requested URL returned error: 400` from github whereas calling the above command on the command line works. Is this a bug or am I doing something wrong?

**Comment by NightFox7** [comment]
I have the same problem. Did you manage to find a solution ?

**Comment by steveukx** [comment]
In my testing, the commands in your example are passed to the `ChildProcess` used by `simple-git`. Are you able to switch to adding configuration with `addConfig` instead?

```
const gitP = require('simple-git/promise');
const git = gitP('./').addConfig('http.extraheader', `Authorization: Basic ${token}`);

const result = await git.push(remote, branch);
```

**Comment by NightFox7** [comment]
For me, the problem is with the clone command so I can't use the addConfig given the fact that I don't have local git configuration yet.

**Comment by steveukx** [comment]
You could try logging all output by adding the `GIT_TRACE` [environment variable](https://github.com/steveukx/git-js#environment-variables)

```
const GIT_TRACE = true;
const gitP = require('simple-git/promise');
const git = gitP('./').env({ ...process.env, GIT_TRACE });

const result = await git.raw(['-c', `http.extraheader="Authorization: Basic ${token}"`, remote, branch]);
```

The standard `git` binary uses `curl` for any `http` request, adding `GIT_TRACE` will add curl's verbose output to stdout which should help find where the header is being lost.

**Comment by NightFox7** [comment]
So I ran the clone command with simple-git and in command line. And here is the difference in the trace logs:
With Simple Git
```
exec-cmd.c:238          trace: resolved executable dir: ***/git-core
fatal: unable to access '${my_url}: The requested URL returned error: 400
```
With Command Line
```
exec-cmd.c:238          trace: resolved executable dir: ***/git-core
12:17:56.155715 run-command.c:663       trace: run_command: git fetch-pack --stateless-rpc --stdin --lock-pack --thin --check-self-contained-and-connected --cloning ${my_url}
```

**Comment by steveukx** [comment]
The format of the `http.extraHeader` setting requires that there are no quotes in the value, this passes the header through to the remote repo:

```
const header = `http.extraHeader=X-Foo: Bar`;
const result = await git.raw(['-c', header 'clone', repo]);
```

Whereas this fails:

```
const header = `http.extraHeader="X-Foo: Bar"`;
const result = await git.raw(['-c', header 'clone', repo]);
```

Please can you check that your header argument is formatted without the quotes...

**Comment by NightFox7** [comment]
You are correct. Thank you ! It works now.

**Comment by steveukx** [comment]
No problem, I'll add to the readme shortly.

@ermshiperete this info should resolve your query too - please ensure you are passing a correctly formatted string as the `-c` value (ie: ``http.extraheader=Authorization: Basic ${token}`` without the `"`)
