### ISSUE TITLE
raw callback not used

### ISSUE THREAD

**Issue by john-dev** [steveukx/git-js#427]
If i use raw to make a request, the callback (then parameter) is not used.
I checked the code and it seems it is not used at all.

example:
` git
      .silent(true)
      .raw(
        [
          "clone",
          "--depth=1",
          "--branch",
          "develop",
          "--single-branch",
          remote,
          gitRepo.name
        ],
        (err, result) => {
          console.log("yo");
          console.log(result, err)
        }
      );`

**Comment by steveukx** [comment]
How are you importing & creating the `git` variable? The callback is called when importing from `simple-git`:

```
const simple = require('simple-git');
const git = simple().silent();
git.raw(['clone', 'https://github.com/steveukx/git-js.git'],
    (err, data) => { err ? console.error('ERROR', err) : console.log('OK', data);  });
```

The use of a callback is ignored when using the promise interface from `simple-git/promise`:

```
const gitP = require('simple-git/promise');
const git = gitP().silent();
git.raw(['clone', 'https://github.com/steveukx/git-js.git'])
     .then(data => console.log('OK', data));
```

**Comment by john-dev** [comment]
I used the promise/ interface - my bad, i misunderstood the documentation.

Thanks
