### ISSUE TITLE
Node application is terminated if trying to checkout a non existing repo.

### ISSUE THREAD

**Issue by Abdul-Aleem029** [steveukx/git-js#429]
Hi Team,

I am running a rest based node application. In which I am trying to checkout a git repo and display the output.
But if the repo is non-existing, then the application is terminated. Is there any way to check of the repo exists, or can error handling be added as a feature for reporting non-existing repositories.

Please find below the error log thrown:

Error: Repository not found
The requested repository does not exist, or you do not have permission to access it.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at toError (D:\Checkout\CheckoutSample\checkout-test-code\node_modules\simple-git\promise.js:90:14)
    at D:\Checkout\CheckoutSample\checkout-test-code\node_modules\simple-git\promise.js:61:36
    at Git.<anonymous> (D:\Checkout\CheckoutSample\checkout-test-code\node_modules\simple-git\src\git.js:1550:20)
    at Function.Git.fail (D:\Checkout\CheckoutSample\checkout-test-code\node_modules\simple-git\src\git.js:1475:18)
    at fail (D:\Checkout\CheckoutSample\checkout-test-code\node_modules\simple-git\src\git.js:1433:20)
    at D:\Checkout\CheckoutSample\checkout-test-code\node_modules\simple-git\src\git.js:1442:16
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! checkout-test-code@1.0.0 start: `set NODE_ENV=development && fastify start -l info app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the checkout-test-code@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hp\AppData\Roaming\npm-cache\_logs\2020-03-09T03_13_20_775Z-debug.log

**Comment by steveukx** [comment]
It looks like you are using the promise based `simple-git/promise`, to add error handling to your application I would recommend using a `try / catch` block, eg:

```
const remote = 'the remote git repo url';
const gitP = require('simple-git/promise');
const git = gitP();

// as async await
try {
  console.log('checked out', await git.checkout(remote));
} catch (e) {
  console.log('Failed to checkout');
}

// as regular promises
git.checkout(remote)
  .then(result => console.log('checked out', result))
  .catch(e => console.log('Failed to checkout'))
```
