### ISSUE TITLE
status options

### ISSUE THREAD

**Issue by mfulton26** [steveukx/git-js#430]
`git.diff` supports options but `git.status` doesn't

e.g. `await git.diff(["--", "out"])` will returns the diff for things in the `out` directory but `await git.status(["--", "out"])` doesn't work (appears to take the options array as a `then` for a promise chain which causes it to return the empty string 😢).

**Comment by steveukx** [comment]
At the moment, `git.status` doesn't support supplying options, instead it uses a known set of arguments required for the status parser to read the response correctly.

You can always use the `git.raw` method for running arbitrary commands to satisfy more [complex requests](https://github.com/steveukx/git-js#complex-requests), eg:  `await git.raw(['status', '--', 'out'])`

**Comment by mfulton26** [comment]
I just figured out that `diffSummary` supports `options` and it works for my needs (just need to know if there are or are not changes in a sub directory). Thank you.
