### ISSUE TITLE
.cwd() is having issues

### ISSUE THREAD

**Issue by johncokos** [steveukx/git-js#432]
I'm having an issue getting simple-git to work with regards to changing into a directory and then executing commands.

```
  // Elsewhere
  const tmpRepoDir = '/tmp/cloned';
  const gitHubEmail = 'myemail@wherever.com';
  const gitHubUsername = 'myrealusername';

  // ...

  return git().silent(true)
    .cwd(tmpRepoDir)
    .init()
    .addConfig('user.name', gitHubUsername)
    .addConfig('user.email', gitHubEmail)
    .add('./*')
    .commit("first commit!")
    .addRemote('origin', targetRepo)
    .push('origin', 'master')
    .catch(e => console.log(e.message));
```

This results in: 

`git(...).silent(...).cwd(...).init is not a function`

I did some poking around and it looks like the this line in `exists.js` is failing ...

`var stat = fs.statSync(path);`

`tmpRepoDir` definitelly a folder. I've put in hardcoded paths as well and it's unable to get past that line. I wonder if there's some sort of permissions issue with it becuase simple-git is inside of `node_modules` and unable to get stats on something outside of there?

It's become a blocker for me, so I've reverted to doing `exec` directly to get things done, but I'd much prefer to use this if its possible.

Any experience with this?

**Comment by steveukx** [comment]
Apologies for the delay in responding... have you resolved this issue yet?

How are you including function `git()` to your project? If importing the default function (`git = require('simple-git');` there is no chain method `.catch` which would be causing an error. If you are using the promise based api `git = require('simple-git/promise')` then each step is a promise generator, so `git.cwd()` returns a promise, not a git instance, so I would expect either version to be throwing runtime errors based on the extract above.

The `exists` check requires that the path is a directory that can be read by whichever user `node` is running as. Is it possible that there are `chmod` restrictions preventing it from being accessible to the node user?
