### ISSUE TITLE
If the git repository is corrupt or broken.  Then simpleGit throws raw errors.

### ISSUE THREAD

**Issue by JoelParke** [steveukx/git-js#437]
I noticed today that I was seeing strange errors from (I thought) simpleGit.  This happened when I did:
simpleGit.add('-A')

After a hunting and thinking and checking issues here.  I discovered that my repository I was working on was corrupt.  I then used git-repair --force to fix the repository.  

SO my **SUGGESTION** is: that when you throw errors from git, could you add a 'possibly corrupted repository', to the error message?  This would have saved me a couple of hours today.  Only a thought to help someone else...

Thanks especially for a great tool.

**Comment by steveukx** [comment]
Hi, thanks for the suggestion.
Is there a repeatable way to get the git repo into a corrupted state such that it needs the git-repair? If so, I can create an integration test, and look to get more useful error messages in there.

**Comment by JoelParke** [comment]
I will ponder this a bit.  One way to generate a corrupt repository is to use something like GitKraken, and stop a merge in progress.  But this is a bit of an artificial example.  

If I generate a corrupted git repository, I will note the weird errors.  If my memory serves, they were errors that git only throws when things are broken.  And I had to use git-repair to get a functional repository back.  So rare that I remember having to use git-repair, which I never did before. In fact didn't realize that such a tool was even needed.

**Comment by JoelParke** [comment]
Not any way that I know off hand.  I should have cached the broken state
before fixing it.  If it was not private, I could have then saved it. In
the future I will look for such an issue on a open source repository and
then share it.  Sorry to not be very helpful yet in this regard.

**Comment by cmawhorter** [comment]
i _think_ i might be hitting this.  i'm getting "Error: fatal: not a git repository (or any of the parent directories): .git".

running `git status` without simple-git in the target directory gives same error.

but a .git directory does exist and it contains _stuff_. 

this is a directory that is being created in tmp and entirely managed through simple-git.  i have no idea what caused it but i'm doing nothing but cloning (depth 1) if it doesn't exist and pulling updates if it does.

perhaps this could be a fix:

1. check if git returns the _not a git repository_ error
2. check if a .git directory exists
3. if it does, display a different error saying that the repository may have become corrupted and suggest a possible fix (maybe delete and clone new?)
