### ISSUE TITLE
Always treat non-zero exit statuses to `git.raw` as an error

### ISSUE THREAD

**Issue by Blasz** [steveukx/git-js#438]
From the docs for `git.raw`

> Execute any arbitrary array of commands supported by the underlying git binary. When the git process returns a non-zero signal on exit **and it printed something to stderr**, the commmand will be treated as an error, otherwise treated as a success.

I'm running into an issue where I want to use `git show-ref` (via git.raw) to determine whether a ref exists. This command does not print anything to stderr and its exit code is used solely to determine whether it exists or not. This is similar for a range of unix/git tools that have a `-q` flag.
It would be great if non-zero exit signals were always treated as errors regardless of whether something is printed to stderr. Is there a particular use case that this extra condition was added for?

**Comment by steveukx** [comment]
Hi, apologies for this having taken so long - you would now be able to fully customise the use of `exitCode` as a determining factor for treating the task as an error by upgrading to version `2.37.0` and configuring the `errors` plugin: https://github.com/steveukx/git-js/blob/v2.37.0/docs/PLUGIN-ERRORS.md
