### ISSUE TITLE
Force Delete Branch

### ISSUE THREAD

**Issue by fishcharlie** [steveukx/git-js#441]
Is there a way to force delete a branch? Right now I'm running:

`await git.deleteLocalBranch("branch");`

And getting the following error:

```
Error: error: The branch 'branch' is not fully merged.
If you are sure you want to delete it, run 'git branch -D branch'.
```

**Comment by steveukx** [comment]
Hi, you can force delete by using the regular `git.branch(...)` function with the `-D` option:

```
const deleteSummary = await git.branch(['-D', 'myBranchName']);
```

**Comment by fishcharlie** [comment]
@steveukx Any chance for the documentation to be updated to make this more clear?

**Comment by steveukx** [comment]
There is a test case and nicer API on its way soon...
