### ISSUE TITLE
addConfig replaces existing key

### ISSUE THREAD

**Issue by ermshiperete** [steveukx/git-js#442]
The name `addConfig` and it's description suggests that it **adds** a new key and value to the config file. However, if the key already exists it gets **replaced**:

Running the following two commands:

```
      await git.addConfig('remote.origin.fetch', '+refs/heads/*:refs/origin/*');
      await git.addConfig('remote.origin.fetch', '+refs/notes/*:refs/notes/*');
```

results in the following snippet of the `config` file:

```
[remote "origin"]
    fetch = +refs/notes/*:refs/notes/*
```

whereas the expected result would be:

```
[remote "origin"]
    fetch = +refs/heads/*:refs/origin/*
    fetch = +refs/notes/*:refs/notes/*
```

**Comment by steveukx** [comment]
Hi, thank you for pointing this out. I've updated the docs accordingly - and as of version 2.3.0 you can now make use of the new interface for [`git.addConfig`](https://github.com/steveukx/git-js#git-config) where you can explicitly set whether the setting is set or appended to the local config.
