### ISSUE TITLE
Is there any way to do the equivilent of 'git reset'?

### ISSUE THREAD

**Issue by StephenArg** [steveukx/git-js#446]
I'm trying to unstage all staged files and simpleGit.reset('mixed') and simpleGit.reset('soft') are only unstaging a few of the files. Is there anyway to input the equivalent of 'git reset'? Thanks!

**Comment by StephenArg** [comment]
Thank you for making this btw. It's such a useful package!

**Comment by steveukx** [comment]
Hi, yes there is... from the [docs](https://github.com/steveukx/git-js/blob/master/readme.md):

> .reset([resetMode,] handlerFn)
> resets the repository, the optional first argument can either be an array of options supported by the git reset command or one of the string constants mixed, hard, or soft, if omitted the reset will be a soft reset to head, handlerFn: (err)

To be used as:

```
const gitP = require('simple-git/promise');
const git = gitP();

// defaults to a soft reset
const result = await git.reset();

// or pick one of soft / hard or mixed
const result = await git.reset('hard');
```
