### ISSUE TITLE
Missing CHANGELOG

### ISSUE THREAD

**Issue by medikoo** [steveukx/git-js#449]
It'll be great to have some changelog that documents changes between versions.

e.g. currently it's not clear what was breaking with v2.0.0, and it's also hard to seclude that by looking into commits.

**Comment by medikoo** [comment]
I've found now https://github.com/steveukx/git-js#release-history

Still for discoverability it'll be great to have it in CHANGELOG.md

**Comment by steveukx** [comment]
Hi, thanks for pointing this out. As of tagged version 2.6.0 (available on NPM now) there is a changelog for all of version 2, and some highlights of version 1.
