### ISSUE TITLE
Error: spawn git ENOENT in AWS Lambda

### ISSUE THREAD

**Issue by singhemant** [steveukx/git-js#457]
```
const git = require('simple-git/promise');
await git().clone(remoteAddr, `/tmp/${asset}`);
```
This results into: 
`2020-05-23T15:51:16.890Z	0feb02af-cce3-4f70-ab11-5dae09994edf	ERROR	Invoke Error 	{"errorType":"Error","errorMessage":"Error: spawn git ENOENT\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)\n    at onErrorNT (internal/child_process.js:469:16)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","task":{"concatStdErr":false,"format":"utf-8","commands":["clone","https://bitbucket.mycompany.org/scm/hps/serverless.git","/tmp/bootstrap"]},"stack":["Error: Error: spawn git ENOENT","    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)","    at onErrorNT (internal/child_process.js:469:16)","    at processTicksAndRejections (internal/process/task_queues.js:84:21)","    at GitExecutor.<anonymous> (/var/task/node_modules/simple-git/src/lib/git-executor.js:35:23)","    at Generator.throw (<anonymous>)","    at rejected (/var/task/node_modules/simple-git/src/lib/git-executor.js:6:65)"]}`
Has this been tested on Lambda? I am sure there are no permission issues or anything like that.
Please help!
Thanks!

**Comment by steveukx** [comment]
Does the process running your script have write access to `/tmp${asset}` ?

An `ENOENT` error should only be thrown when there is a permission error accessing a path on the file system. Are you able to try cloning into a sub-directory of your working directory?

**Comment by singhemant** [comment]
as far as i know, /tmp inside lambda doesn't need permissions. I can say that because, I am already using git inside my other lambdas as a git layer (https://github.com/lambci/git-lambda-layer) and that works fine able to git clone to /tmp directory. This is the first time I thought to give simple-git a try inside lambda, since it worked fine locally on my machine. After I deployed the lambda, it started breaking. 

Could you also please test in AWS lambda and let me know your findings?

**Comment by GideonPARANOID** [comment]
I had this error when trying to apply the `env('GIT_SSH_COMMAND', whatever)`, swapping that to simply setting the value on `process.env` fixed it. Not sure if that helps you or not.

**Comment by destinyb-realityi** [comment]
I'm having this issue as well, has anyone been able to resolve it?

**Comment by singhemant** [comment]
Hi @destinyb-realityi I was able to resolve it, you might not have git installed in lambda. First you need to have git available in your AWS lambda, please refer: [(https://github.com/lambci/git-lambda-layer)] and attach this git layer to your lambda. then you can use this API. hope this helps. if it worked on your local, it will work on lambda as well. 
All the best!
