### ISSUE TITLE
Typescript - types for exceptions

### ISSUE THREAD

**Issue by j-zimnowoda** [steveukx/git-js#458]
First of all thanks for awesome work. I am successfully using this library at my work.

I couldn't figure out how to import types for exceptions. Are there any?
Having them would be much easier to implement error handlers.
E.g.::
```
try {
  const mergeSummary = await git.merge();
  console.log(`Merged ${ mergeSummary.merges.length } files`);
}
catch (err) {
  console.error(`Merge resulted in ${ err.git.conflicts.length } conflicts`);
}
```
It is not easy to find out complex structures like:  `err.git.conflicts.length`

What do you think ?

**Comment by steveukx** [comment]
Hi, thank you for pointing this out.
As of version 2.6.0 (available now on NPM) I've updated the readme & type documentation to include the errors that may be thrown. Please do let me know if the error types are still too hidden.
