### ISSUE TITLE
isRepo in nested repository

### ISSUE THREAD

**Issue by prevuelta** [steveukx/git-js#459]
When cwd is within another git project `checkIsRepo` will always return true
Could you add a flag to only check cwd?

**Comment by KevinGhadyani-minted** [comment]
Do you mean `.checkIsRepo('root')`?

**Comment by steveukx** [comment]
That's correct - from the [documentation](https://github.com/steveukx/git-js#git-rev-parse--repo-properties)

> .checkIsRepo('root')
> gets whether the current working directory is the root directory for a repo (sub-directories will return false).
