### ISSUE TITLE
There is no subtree commands

### ISSUE THREAD

**Issue by minetsh** [steveukx/git-js#462]
Hi，I can't find subtree feature，so I can't use js complete the follow line command:

`git subtree push --prefix src/module origin module`

**Comment by steveukx** [comment]
I recommend using [git.raw](https://github.com/steveukx/git-js#complex-requests):

```
git.raw(['subtree', 'push, '--prefix, 'src/module, 'origin, 'module'], (err, response) => { ... })
```
