### ISSUE TITLE
Can't clone to a specific directory

### ISSUE THREAD

**Issue by Ruttmann** [steveukx/git-js#463]
I'm using v2.6.0.

I have a routine to create a directory if it don't exists. Directory path is defined by path.resolve. After those checks, I try to clone my remote repo into this directory, but the following error is thrown:

> Error: Cannot use simple-git on a directory that does not exist.

I double checked, and the directory is being correctly created. Also check chmod for it and the permissions are ok. Also tried writing as string the path to the directory, but the same problem occurs.

Let me know if more info is needed.

See the snippet below:
```js
const fs = require("fs");
const rootPath = path.resolve("./repo");
const repoLocalPath = path.resolve(rootPath, "./tj-painel-frontend");
const repoRemotePath = "git@remote.host";
const simpleGit = require("simple-git/promise");
const git = simpleGit(rootPath);

async function checkLocalRepo() {
  console.group("=> Checking local repo");
  try {
    fs.accessSync(repoLocalPath);
    console.info("- Local repo OK.");
  } catch (error) {
    await cloneRemoteRepo();
  }
  console.groupEnd();
}

async function cloneRemoteRepo() {
  console.group("=> Cloning remote repo");
  try {
    await git.clone(repoRemotePath);
  } catch (error) {
    console.error("- Error while cloning.");
    console.error(error);
    process.exit(1);
  }
}

checkLocalRepo();
```

**Comment by Ruttmann** [comment]
The situation seems weird. Fome some reason, the remote repository is being cloned, but the error mentioned above is being thrown.

**Comment by steveukx** [comment]
Hi, to aid looking through why this is happening, as of version 2.7.0 (available on npm now) you can enable detailed logs through the `debug` library. See the [Enable Logging](https://github.com/steveukx/git-js/#enable-logging) section of the readme for details.

Using the logged diagnostics, you should be able to see why this isn't working for you. If you are able to post the diagnostic output I can look to create integration tests to cover the specific use case.

**Comment by Ruttmann** [comment]
Hello.
After some days troubleshooting this question, I found the problem. I was importing the lib in this way:
`const git = require('simple-git')(rootPath)`

Since this path is unexistent, it will throw an error during the require phase. I just changed the import and now I create simpleGit with the rootPath only after creating this path. This solved the problem.
