### ISSUE TITLE
Probably incorrect files in package.json

### ISSUE THREAD

**Issue by doomsower** [steveukx/git-js#471]
I'm getting this error while running tests on my project:

```
/Volumes/Projects/myproject/services/backend/node_modules/simple-git/src/lib/runners/promise.ts:1
    import { SimpleGit } from '../../../typings';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

Looking at package.json, I see this:
```
"files": [
    "promise.*",
    "src/**/*.d.ts",
    "src/**/*.js",
    "src/**/*.js.map",
    "typings/"
  ],
```

I think the intent was to ignore `src/lib/runners/promise.ts`, but the first allows it to slip into release

**Comment by steveukx** [comment]
Hi, thank you for reporting this issue. Version `2.7.2` is now available on npm which should resolve this issue for you.
