### ISSUE TITLE
SimpleGit instance resolved as promise when using "await"

### ISSUE THREAD

**Issue by msaKnowis** [steveukx/git-js#478]
Hi,
We are just about to update to the new version 2.9.0 and we encountered an issue when the simpleGit instance is returned by an async function and gets awaited then in the consumer function

```ts

import simpleGit, { SimpleGit } from 'simple-git';

export class GitHandler {

  public async getGit(): Promise<SimpleGit> {
     // async operation to get workDir
   const workDir = await getWorkDir();
   // create git instance
    const myGitInstance = simpleGit(workDir);

   // myGitInstance.raw(......);

   return myGitInstance;
  }

  public async doSomething() {
    // get simple git instance
    const git = await this.getGit();
    // execute git command
    await git.raw(....) // --> `git` is not the real instance
  }
}
```
In this case, the git.raw execution fails, as the variable "git" is undefined. But that is dependending on the git actions that were executed in the `getGit`. If e. g. a `raw` action was executed, the resulting `git` in `doSomething ` is an empty string.
If I debug the `myGitInstance`, it looks like it was correctly instantiated as a SimpleGit instance.

It seems that with each action that is performed, the promise is somehow added to the git instance and then whenever the git instance is awaited, it resolves this promise.
This leads to the fact that we can never return a SimpleGitInstance within an async function directly and awaiting it, as I always get the result of the last promise, instead of the actual instance.

Could you please tell me whether we understood something wrong in how to use the new version of SimpleGit?

**Comment by msaKnowis** [comment]
Additional info:
If we use the "old" import syntax (prior to 2.6), the issue does not happen and everything works as expected.

**Comment by steveukx** [comment]
Hi, thank you for opening this issue. 
As of version 2.10.0 (on npm now), the `.then` and `.catch` methods are only available on the return from a task rather than on the main instance itself.

**Comment by msaKnowis** [comment]
We've tried it with 2.10.0 and it seems to work now! :)
Thank you!
