### ISSUE TITLE
Git checkout hash

### ISSUE THREAD

**Issue by ShMcK** [steveukx/git-js#48]
I'm trying to checkout a hash tag referencing a commit. Is this functionality included?

Neither of the following APIs seem to work with hash values.

    repo.checkout(hash, function(error, data) { ... });

    repo.checkoutLocal(hash, function(error, data) { ... });

**Comment by steveukx** [comment]
Seems to be working fine for me:

    $ git clone https://github.com/steveukx/git-js.git
    $ cd git-js
    $ git status
    $ node -p "require('./src')().checkout('35074f5')"
    $ git status

If you continue having problems, please create a failing test case and re-open this issue.
