### ISSUE TITLE
Possible regression for checkoutLocalBranch in v2.10.0

### ISSUE THREAD

**Issue by jordanranz** [steveukx/git-js#480]
`.checkoutLocalBranch` seems to silently fail in v2.10.0. After running the command on the repo, the branch is not created or set to the `branchName`. Manually setting the version to 2.9.0 fixes the issue.

**Comment by steveukx** [comment]
Hi, thank you for opening the issue. This is now resolved in version `2.11.0` available on npm now. 
If you have any further problems, please do open another issue.
