### ISSUE TITLE
[BUG]: checkoutBranch not working

### ISSUE THREAD

**Issue by viceice** [steveukx/git-js#490]
The `checkoutBranch` does not work. See https://github.com/viceice/simple-git-tests for reproduction.

this call seems to be incorrect (i think the `then` should only be passed if not undefined):
https://github.com/steveukx/git-js/blob/553ff0a33f127930c74b6d8e3690baee0b852c5e/src/git.js#L471

as it will cause empty `commands` here:
https://github.com/steveukx/git-js/blob/553ff0a33f127930c74b6d8e3690baee0b852c5e/src/git.js#L456

So the called git command is only `git checkout` instead of `git checkout -b target source`

**Workaround**
call checkout directly: `await repo.checkout(["-b", "test", "master"])`

**Comment by steveukx** [comment]
Thank you for the detailed bug report.

This is resolved in version 2.14.0 now available on npm.
