### ISSUE TITLE
concurrency safety, in process and out of process

### ISSUE THREAD

**Issue by x37v** [steveukx/git-js#493]
I'm not 100% clear on the safety of concurrency in this project.

# In process

The notes in [concurrent--parallel-requests](https://github.com/steveukx/git-js#concurrent--parallel-requests) indicate:
```
When the methods of simple-git are called on the root instance (ie: git = simpleGit()) rather than chained off another task, it starts a new chain and will not be affected failures in tasks already being run.
```

Does this mean that if 2 tasks check out different branches, they can expect to not conflict with each other? Each can expect that the branch they're in will stay the same in their chain until they attempt to change the branch somehow in that same chain?

Also, what is the behavior if I try to create a task that exceeds `maxConcurrentProcesses` ?

# Separate Processes

Also, how about separate processes. If I have 2 different node apps using the same `working directory`, can I expect the same behavior above? Or do I have to make sure that each node process has its own fork? Do I have to make sure that no other application is using this fork either (git commandline, etc etc)?

**Comment by steveukx** [comment]
The concurrency limiting `simple-git` provides relates to the number of child processes it spawns to run the `git` commands, in order to prevent node reporting the child processes as having closed without writing any data to `stdout` / `stderr` (see the full conversation about this in #317 ).

> what is the behavior if I try to create a task that exceeds `maxConcurrentProcesses`

Tasks added once `maxConcurrentProcesses` is reached are queued pending space becoming available in the queue, I'll make this more clear in the readme.

> if 2 tasks check out different branches

As `simple-git` is a simple wrapper of the `git` binary, attempting to run two conflicting `git` commands on the same directory at the same time will have the same result as if they had both been run in separate terminal windows - the expected behaviour in this case would be that the conflicting task fails with an error similar to:

```
fatal: Unable to create '/some-path-to/the-repo/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

**Comment by x37v** [comment]
@steveukx thanks for the quick response!


> The concurrency limiting `simple-git` provides relates to the number of child processes it spawns to run the `git` commands, in order to prevent node reporting the child processes as having closed without writing any data to `stdout` / `stderr` (see the full conversation about this in #317 ).


okay, hmm. so within the same process, is there any locking on promise chains? Can 2 tasks expect to not interfere with each other if they're switching branches etc? the doc indicates that failures don't affect other tasks, but do successes?

```
const git = simpleGit();
const results = await Promise.all([
    git.checkout('branchA').status().then(r => console.log(r)),
    git.checkout('branchB').status().then(r => console.log(r)),
]);
```

> 
> > what is the behavior if I try to create a task that exceeds `maxConcurrentProcesses`
> 
> Tasks added once `maxConcurrentProcesses` is reached are queued pending space becoming available in the queue, I'll make this more clear in the readme.
> 
> > if 2 tasks check out different branches
> 

> As `simple-git` is a simple wrapper of the `git` binary, attempting to run two conflicting `git` commands on the same directory at the same time will have the same result as if they had both been run in separate terminal windows - the expected behaviour in this case would be that the conflicting task fails with an error similar to:
> 
> ```
> fatal: Unable to create '/some-path-to/the-repo/.git/index.lock': File exists.
> 
> Another git process seems to be running in this repository, e.g.
> an editor opened by 'git commit'. Please make sure all processes
> are terminated then try again. If it still fails, a git process
> may have crashed in this repository earlier:
> remove the file manually to continue.
> ```

Understood, that is what I figured. So my guess is that if one process successfully check's out branch A, pauses for a moment, and another process check's out branch B, when the first process resumes working it'll be in branch A. So basically, each process needs its own checkout.

**Comment by steveukx** [comment]
Locking the underlying file system is left to `git` itself, so if you need to have two checked out branches available to you at the same time (ie: truly concurrently) you would need to have two separate clones of the remote repo.

If you need to ensure you are on a specific branch before running a command, you could consider using something like the below to switch to the branch before running a task:

```typescript
import git, {SimpleGit} from 'simple-git';
import { exists, FOLDER } from '@kwsites/file-exists';
import { join } from 'path';

const gitBranchMap: Map<string, Promise<SimpleGit>> = new Map();

export function simpleGitOnBranch(branch: string, baseDir: string, remote: string): Promise<SimpleGit> {
  const forBranchDir = join(baseDir, branch);
  if (!gitBranchMap.has(forBranchDir)) {
    gitbranchMap.set(forBranchDir, exists(forBranchDir, FOLDER) ? cloneBranch(branch, forBranchDir, remote) : checkoutBranch(branch, baseDir));
  }

  return gitBranchMap.get(forBranchDir)!;
}

async function checkoutBranch (branch: string, baseDir: string) {
  await git(baseDir).checkout(branch);
  return git(baseDir);
}

async function cloneBranch (branch: string, baseDir: string, remote: string) {
  await git().clone(remote, baseDir, ['--branch', branch, '--single-branch']);
  return git(baseDir);
}
```

then use that in your application:

```typescript
import {SimpleGit} from 'simple-git';
import {simpleGitOnBranch} from './wherever/you/saved-that';

// first time this is used, clones the repo to ./clones/abc on branch abc and then runs `git status`
console.log(await simpleGitOnBranch('abc', './clones', 'git@github.com:user/repo.git').status());

// next time the same branch is used, uses the repo already cloned to ./clones/abc on branch abc and then runs `git status`
console.log(await simpleGitOnBranch('abc', './clones', 'git@github.com:user/repo.git').status());


```

_(note: code has not been tested, for indicative purposes only)_
