### ISSUE TITLE
Is there any library to create pull request

### ISSUE THREAD

**Issue by satishbkodali** [steveukx/git-js#498]
Is there any library to create pull request instead of doing thru UI?

**Comment by steveukx** [comment]
Hi, you could use `git request-pull` which is documented in the git docs: https://git-scm.com/docs/git-request-pull

There isn't a custom wrapper for it in `simple-git` at the moment, but you can create arbitrary requests using `git.raw(...)` as documented in the [complex requests(https://github.com/steveukx/git-js#complex-requests) section.
