### ISSUE TITLE
git.branch results missing some branch name

### ISSUE THREAD

**Issue by Yahiko7** [steveukx/git-js#500]
I found that git.branch does not result  some branch name

git branch -v -a 

![image](https://user-images.githubusercontent.com/15901380/90329255-9cce1100-dfd5-11ea-9709-dc3be76b8cd2.png)

simple branch
```js
const simpleGit = require('simple-git');
const git = simpleGit();
git.branch().then(result => {
    console.log(result) // ==> { current: '', local: [ 'dev' ], remote: [ 'dev' ] }
})
```
The reason is because my submission contains '\r \r' 

![image](https://user-images.githubusercontent.com/15901380/90329076-1c5ae080-dfd4-11ea-8031-09aa040a3b4d.png)

The Solution:

file：src/lib/parsers/parse-branch.js ( version：2.17.0 )

the RegExp (/^(\*\s)?(\S+)\s+([a-z0-9]+)\s(.*)$/) adds a multiline attribute
```js
/^(\*\s)?(\S+)\s+([a-z0-9]+)\s(.*)$/   ===> /^(\*\s)?(\S+)\s+([a-z0-9]+)\s(.*)$/m
```
![image](https://user-images.githubusercontent.com/15901380/90329200-1f0a0580-dfd5-11ea-9e8a-0589f0f8b42b.png)

**Comment by steveukx** [comment]
Hi, apologies for not having got back to you sooner and thank you for the suggested solution.

You should find that version 2.36.0 available on NPM now permits the carriage return character.

If you have any other problems, please do create a new issue.
