### ISSUE TITLE
[BUG] clone doesn't pass object options

### ISSUE THREAD

**Issue by viceice** [steveukx/git-js#502]
https://github.com/steveukx/git-js/blob/27c3f1bceffad11ac73d2f6a10279033cda02acf/src/git.js#L193-L203

works: `await git.clone(url, '.', ['--config=http.extraheader=AUTHORIZATION bearer xxxx'])`

fails: `await git.clone(url, '.', {'--config': 'http.extraheader=AUTHORIZATION bearer xxxx'])`

**Comment by viceice** [comment]
Here `TaskOptions` can be `{ [key: string]: null | string | any }`
https://github.com/steveukx/git-js/blob/27c3f1bceffad11ac73d2f6a10279033cda02acf/typings/simple-git.d.ts#L174
https://github.com/steveukx/git-js/blob/27c3f1bceffad11ac73d2f6a10279033cda02acf/src/lib/types/index.ts#L11
https://github.com/steveukx/git-js/blob/27c3f1bceffad11ac73d2f6a10279033cda02acf/src/lib/types/index.ts#L16

**Comment by steveukx** [comment]
Hi, thanks for the detailed issue - this is now resolved and available on npm as version 2.18.0
