### ISSUE TITLE
Options as an array of strings does not work for git push

### ISSUE THREAD

**Issue by ssmereka** [steveukx/git-js#505]
The documentation says you can use an array of strings for options

<img width="971" alt="Screen Shot 2020-08-21 at 8 11 37 AM" src="https://user-images.githubusercontent.com/489291/90906057-f17edc80-e385-11ea-8c3f-23031c97db6b.png">

However the following doesn't work:

```javascript
await this.git.push(remote, branch, ['--tags'])
```
```console
error TS2345: Argument of type 'string[]' is not assignable to parameter of type 'Record<string, OptionsValues>'.
      Index signature is missing in type 'string[]'.
```

Am I doing something wrong or is this a bug?

**Comment by steveukx** [comment]
Thank you for opening the issue, apologies it's taken so long to respond.
The types are updated and available for use in `2.24.0` on npm now
