### ISSUE TITLE
git.log: Incomatible typescript types for options

### ISSUE THREAD

**Issue by viceice** [steveukx/git-js#506]
![image](https://user-images.githubusercontent.com/1798109/91021407-052f7a80-e5f4-11ea-98d4-ac2357c3a1bc.png)

ref: renovatebot/renovate#7069

**Comment by viceice** [comment]
thanks for fast fixing.

**Comment by steveukx** [comment]
Thanks for the detailed issue report... this is fixed in the published version 2.20.1 - available on npm now
