### ISSUE TITLE
Is it possible to run git describe  --tags --exact-match with this lib?

### ISSUE THREAD

**Issue by BioPhoton** [steveukx/git-js#508]
I tried to find a way to run:  `git describe --tags --exact-match` to see if I am currently on a tag.

But unfortunately no luck. Is this possible somehow with this lib?

**Comment by steveukx** [comment]
There isn't currently a specific method for handling the use of `describe` so the easiest way would be to use `git.raw`, documented in the [complex requests] (https://github.com/steveukx/git-js#complex-requests) section:

```
import simpleGit from 'simple-git';

async function isOnTag() {
 return await simpleGit().raw('describe', '--tags', '--exact-match');
}
```

**Comment by BioPhoton** [comment]
Thx for your answer and keep it going!!! Really like your lib!! ❤️
