### ISSUE TITLE
How do I implement git push -u origin master？

### ISSUE THREAD

**Issue by Vermouth1995** [steveukx/git-js#510]
![image](https://user-images.githubusercontent.com/17866208/92377545-e32b1180-f136-11ea-926a-eae6c7b8e082.png)

According to the documentation,  I don't know how to implement `git push -u origin master`

**Comment by steveukx** [comment]
Hi, from the docs relating to [git push](https://github.com/steveukx/git-js#git-push) and how to pass [options](https://github.com/steveukx/git-js#how-to-specify-options), the simplest would be:

```
git.push(['-u', 'origin', 'master'])
```
