### ISSUE TITLE
`git log` not showing tag data

### ISSUE THREAD

**Issue by adelriosantiago** [steveukx/git-js#515]
When doing `git.raw(["log"])` I get no tag information which is enclosed in `()`. 

For example I get:

> commit a31a8f0a4bedd67ef249f347fe069d677aed0e61
> Author: test <test@mail.com>

When it should be:

> commit a31a8f0a4bedd67ef249f347fe069d677aed0e61 (HEAD -> tag, tag: tag123, origin/repo)
> Author: test <test@mail.com>

**Comment by steveukx** [comment]
The output of `git.raw(...)` is the data streamed to `stdout` from the underlying git process which doesn't include the branch data in parentheses by default when the consumer of the stream is readonly (which can be seen by piping to a file, eg `git log > out.log` or `git log | grep HEAD`).

To include these details, you should use a `--pretty=format:...` string to include the details you need, or use the built in `git.log()` function from this library which parses the response for you.

**Comment by adelriosantiago** [comment]
Works good, thanks!
