### ISSUE TITLE
git show (feat)

### ISSUE THREAD

**Issue by ctfrancia** [steveukx/git-js#517]
I was looking throw the docs and don't see the command for `$ git show [--options]` the main reason why needed is because when using docker we are trying to debug and see what is the pull hash we are building from. Unless I am missing something I don't see it in the API list.

**Comment by Mytakeon** [comment]
Isn't it the last item in the API list? `git.show([options], handlerFn)`

**Comment by steveukx** [comment]
In the current release you can pass `options` as an array of strings, for a working example please see the [git show test case](https://github.com/steveukx/git-js/blob/v2.21.0/test/unit/test-show.js#L25)
