### ISSUE TITLE
The first commit returns more than the ID in the CommitSummary.commit

### ISSUE THREAD

**Issue by jensklose** [steveukx/git-js#520]
This following behavior is an edge case only for a first (root) commit.  

**Expected:**
`const co = await git.add(".").commit("first commit");`
should return the commitId in the CommitSummary.commit field.
```
CommitSummary {
  branch: 'master',
  commit: 'a78979d',
  summary: { changes: 2, insertions: 2, deletions: 0 },
  author: null
}
```

**Actual:**
```
CommitSummary {
  branch: 'master',
  commit: '(root-commit) a78979d',
  summary: { changes: 2, insertions: 2, deletions: 0 },
  author: null
}
```

The reason is the git output:
```
09:36 # git commit -m "hui"
[master (root-commit) 1153df9] hui
 1 file changed, 0 insertions(+), 0 deletions(-)
```

Feature or bug?

**Comment by steveukx** [comment]
Hi, apologies it's taken a while to get back to you on this one & thank you for the detail in your issue.
From version `2.31.0` (on npm now) you can check the `commitResult.root` property to see whether this was a root commit and the commit hash no longer contains the `root-commit` message.
