### ISSUE TITLE
DeprecationWarning when running diff command

### ISSUE THREAD

**Issue by reintroducing** [steveukx/git-js#524]
Hello,
I'm simply running the following in a node script:
```
const diff = await simpleGit().diff();
```
In terminal, I see this as a result:
```
(node:21222) DeprecationWarning: Instance method `debug.destroy()` is deprecated and no longer does anything. It will be removed in the next major version of `debug`.
```

I'm on node v12.8.0 and npm v6.10.2.

**Comment by innocenzi** [comment]
I have this as well. Apparently `destroy` is no longer required. 

https://github.com/visionmedia/debug/commit/e2d3bc9e428bdd45adb8d6e7f8ab543bee54d9a6

**Comment by steveukx** [comment]
Hi, thanks for pointing this out - you can upgrade to `2.23.0` on npm now to no longer see this notice.

**Comment by innocenzi** [comment]
Thank you, that was fast!
