### ISSUE TITLE
When I merge code there are conflicts but no exception or error

### ISSUE THREAD

**Issue by 1156958090** [steveukx/git-js#528]
This is my code 
```
try {
        const result = await simpleGit.mergeFromTo('testGit1','categoryParams')
        console.info(result);
    } catch (error) {
        console.error(error);
    }
```
MergeSummaryDetail.result is "success"

**Comment by steveukx** [comment]
Hi, there are [tests](https://github.com/steveukx/git-js/blob/main/test/integration/merge-integration.spec.js) for detecting conflicts in a merge, so to check why yours isn't being recognised please run your script with [verbose logging enabled](https://github.com/steveukx/git-js#enable-verbose-logging) with the environment variable `DEBUG=simple-git:simple-git:*` and include the log here. Thanks

**Comment by 1156958090** [comment]
`
simple-git:task:merge:1 Adding task to the queue, commands = [ 'merge', 'testGit2' ] +0ms
  simple-git:task:merge:1 Starting task +4ms
  simple-git:task:merge:1 [SPAWN] git [ 'merge', 'testGit2' ] +0ms
  simple-git:task:merge:1 [SPAWN] { cwd: 'not true path',
  simple-git:task:merge:1   env: undefined,
  simple-git:task:merge:1   windowsHide: true } +0ms
  simple-git:task:merge:1 [SPAWN] stdOut received 114 bytes +17ms
  simple-git:task:merge:1 [SPAWN] stdOut received 64 bytes +1ms
  simple-git:task:merge:1 [SPAWN] exitCode=1 event=exit +2ms
  simple-git:task:merge:1 [HANDLE] Preparing to handle process response exitCode=1 stdOut= +0ms
  simple-git:task:merge:1 [HANDLE] retrieving task output complete +0ms
  simple-git:task:merge:1 passing response to task's parser as a utf-8 +0ms
MergeSummaryDetail {
  conflicts: [],
  merges: [],
  result: 'success',
  remoteMessages: RemoteMessageSummary { all: [] },
  created: [],
  deleted: [],
  files: [],
  deletions: {},
  insertions: {},
  summary: { changes: 0, deletions: 0, insertions: 0 } }
  simple-git:task:merge:1 [SPAWN] exitCode=1 event=close +3ms
`

**Comment by 1156958090** [comment]
@steveukx hi, Is there any solution？

**Comment by 1156958090** [comment]
@steveukx hello, is anybody here

**Comment by steveukx** [comment]
The output you've added here doesn't include the response from `git` - it should have been printed to the terminal with the prefix `simple-git:output:merge:1`. Without that I'm afraid I can create any test cases for this issue.

The commands being run also don't appear to match up to the ones in your original query - in the original question you're using `git.mergeFromTo('testGit1', 'categoryParams')` but the command shows `testGit2`. Please include the full output for the merge command, eg:

```
await git.mergeFromTo('main', 'blah');
```

generates:

```
  simple-git:task:merge:5 Starting task +0ms
  simple-git:task:merge:5 [SPAWN] git [ 'merge', 'main', 'blah' ] +0ms
  simple-git:task:merge:5 [SPAWN] { cwd: 'repo', env: undefined, windowsHide: true } +8ms
  simple-git:task:merge:5 [SPAWN] stdErr received 103 bytes +22ms
  simple-git:output:merge:5 [stdErr] merge: main - not something we can merge
```

**Comment by 1156958090** [comment]
ok, this is my code
```
try {
        const result = await Git.mergeFromTo('testGit2', 'testGit3')
        console.info(result);
    } catch (error) {
        console.log(error)
    }
```
logs:
```
simple-git:scheduler Constructed, concurrency=5 +0ms
  simple-git:task:merge:1 Adding task to the queue, commands = [ 'merge', 'testGit2', 'testGit3' ] +0ms
  simple-git:scheduler Scheduling id=1 +9ms
  simple-git:scheduler Attempting id=1 +1ms
  simple-git:task:merge:1 Starting task +4ms
  simple-git:task:merge:1 [SPAWN] git [ 'merge', 'testGit2', 'testGit3' ] +1ms
  simple-git:task:merge:1 [SPAWN] { cwd: 'not true path',
  simple-git:task:merge:1   env: undefined,
  simple-git:task:merge:1   windowsHide: true } +0ms
  simple-git:task:merge:1 [SPAWN] stdOut received 114 bytes +24ms
  simple-git:output:merge:1 [stdOut] 自动合并 src/pages/Goods/Board/index.jsx
  simple-git:output:merge:1 冲突（内容）：合并冲突于 src/pages/Goods/Board/index.jsx
  simple-git:output:merge:1  +0ms
  simple-git:task:merge:1 [SPAWN] stdOut received 64 bytes +1ms
  simple-git:output:merge:1 [stdOut] 自动合并失败，修正冲突然后提交修正的结果。
  simple-git:output:merge:1  +1ms
  simple-git:task:merge:1 [SPAWN] exitCode=1 event=exit +1ms
  simple-git:task:merge:1 [HANDLE] Preparing to handle process response exitCode=1 stdOut= +1ms
  simple-git:task:merge:1 [HANDLE] retrieving task output complete +0ms
  simple-git:task:merge:1 passing response to task's parser as a utf-8 +0ms
  simple-git:scheduler Completing id= 1 +30ms
  simple-git:scheduler Schedule attempt ignored, pending=0 running=0 concurrency=5 +0ms
MergeSummaryDetail {
  conflicts: [],
  merges: [],
  result: 'success',
  remoteMessages: RemoteMessageSummary { all: [] },
  created: [],
  deleted: [],
  files: [],
  deletions: {},
  insertions: {},
  summary: { changes: 0, deletions: 0, insertions: 0 } }
  simple-git:task:merge:1 [SPAWN] exitCode=1 event=close +4ms
```
@steveukx

**Comment by steveukx** [comment]
Thank you for the additional detail. I'm sorry to say that as `simple-git` relies on the underlying `git` binary to respond in an english language locale, the parsers are unlikely to work for you at present. I will add this detail to the troubleshooting guide now.

**Comment by 1156958090** [comment]
You are right, I changed my git language to English and it was ok. thanks
