### ISSUE TITLE
Using outputHandler to monitor progress events

### ISSUE THREAD

**Issue by xiaoxian521** [steveukx/git-js#529]
Can I add a callback method when I download so that I can add the download progress

**Comment by steveukx** [comment]
Until [v3](#527) is released, you can use [outputHandler](https://github.com/steveukx/git-js#piping-to-the-console-for-long-running-tasks) to receive updates as `git` tasks are run.

**Comment by xiaoxian521** [comment]
well，Is there any way to monitor the download progress

**Comment by steveukx** [comment]
That would depend on which command you are running through `git` and whether the response from the `git` binary contains progress information.

In order to suggest something more specific, please include your code and any use of `outputHandler` you have already tried.

**Comment by xiaoxian521** [comment]
Code:
```
const download = require('simple-git')
var time = 0
module.exports.clone = async (repo) => {
    const ora = require('ora')
    const process = ora(`DownLoad.....${repo}${time}`)
    process.start()
    console.log(download)
    await
        download()
            .outputHandler(() => {
                time += 1
            })
            .silent(true)
            .clone(repo)
            .then(status => {
                time = 100
                return
            })
            .catch(err => { console.log("err::", err) })
    process.succeed()
}
```

Question:
Git download does not always execute the outputhandler function

**Comment by xiaoxian521** [comment]
@steveukx  The above method is that I simulate the progress. I hope to use a method to execute the download all the time

**Comment by xiaoxian521** [comment]
@steveukx hi，Is there any solution

**Comment by steveukx** [comment]
The `outputHandler` is called once per task, and is passed the `stdout` / `stderr` streams from the `git` binary. To check when those streams receive data, you would need something along these lines:

```
(async function () {
    const simpleGit = require('simple-git');
    const ora = require('ora');

    const remote = {
        name: 'simple',
        repo: 'https://github.com/steveukx/git-js.git'
    };
    const spinner = ora('Source Control').start();

    const git = simpleGit('repo');
    git.outputHandler((bin, stdOut, stdErr) => {
        stdErr.on('data', d => spinner.text = `Received: ${d.length}b`);
        stdOut.on('data', d => spinner.text = `Received: ${d.length}b`);
    });
    try {
        spinner.prefixText = 'git.init';
        await git.init();

        spinner.prefixText = 'git.addRemote';
        await git.addRemote(remote.name, remote.repo);

        spinner.prefixText = 'git.fetch';
        await git.fetch([remote.name]);

        spinner.prefixText = 'git.checkout';
        await git.checkout('v2.9.0');

        spinner.prefixText = '';
        spinner.text = 'Complete.';
        spinner.stopAndPersist();
    }
    catch (e) {
        spinner.text = 'Error: ' + e;
        spinner.stopAndPersist();
    }

}());
```

**Comment by xiaoxian521** [comment]
ok. thanks i am try

**Comment by xiaoxian521** [comment]
I think git -js can combine with the progress module to make a progress bar

**Comment by xiaoxian521** [comment]
@steveukx  v3 edition  Is there any way to monitor the download progress？

**Comment by xiaoxian521** [comment]
@steveukx v3 edition Is there any way to monitor the download progress？

**Comment by xiaoxian521** [comment]
@steveukx  hi Can you give me a reply

**Comment by xiaoxian521** [comment]
such as:
```
const download = require('download');
const Progress = require('progress');


// Global variables.
const FORMAT = '[:bar] :percent :etas';
const OPTIONS = {
  complete: '=',
  incomplete: ' ',
  width: 20,
  total: 0
};


/**
 * Download and extract files (with progress).
 * @param {string} url URL to download.
 * @param {string} [dst] Path to where your file will be written.
 * @param {object} [opt] Options for "download", progress, onresponse.
 */
function edownload(url, dst, opt) {
  var o = (opt || typeof dst==='string'? opt:dst)||{};
  var bar = o.progress===undefined? new Progress(FORMAT, OPTIONS):o.progress;
  return download(url, dst, opt).on('response', o.onresponse||(res => {
    if(bar==null) return;
    bar.total = res.headers['content-length'];
    res.on('data', dat => bar.tick(dat.length));
  }));
};
module.exports = edownload;
```

**Comment by steveukx** [comment]
Hi, you can now configure `simple-git` with a `progress` handler to receive progress updates on any `git` operation that supports them - https://github.com/steveukx/git-js#progress-events

If you have any problems using the new api, please do open another issue.

**Comment by xiaoxian521** [comment]
ok ,thanks! i try

**Comment by xiaoxian521** [comment]
@steveukx 
Here's a problem. When the download progress shows 100%, my project is not completely downloaded

**Comment by xiaoxian521** [comment]
and stage Always in resolving state

**Comment by xiaoxian521** [comment]
@steveukx Here's a problem. When the download progress shows 100%, my project is not completely downloaded

**Comment by xiaoxian521** [comment]
@steveukx 
version："simple-git": "^2.35.2"
bug：The progress bar reaches 100% before downloading

**Comment by steveukx** [comment]
Hi, in order to look into this for you please also include the code you are using to respond to progress events. Thanks

**Comment by xiaoxian521** [comment]
```
const SimpleGit = require('simple-git')
const ora = require('ora')
const process = require("process")

const spinner = ora('开始下载').start();

const progress = ({ stage, progress }) => {
    let proText = `当前下载进度: ${progress}%`
    spinner.text = proText
    if (progress === 100) {
        spinner.text = proText + ' 下载完成'
        spinner.stopAndPersist()
        process.exit()
    }
}

module.exports.clone = async (repo) => {
    const git = SimpleGit({ progress: progress })
    await git.clone(repo)
}
```

**Comment by steveukx** [comment]
Your progress handler is terminating the node process on the first 100% complete `stage` rather than when the `clone` task is complete - note that there are potentially several stages of any one command (for example a clone will have stages for both counting and receiving assuming you're in english locale).

A more robust solution would be:

```javascript
const SimpleGit = require('simple-git')
const ora = require('ora')
const process = require("process")

const spinner = ora('开始下载').start();

const progress = ({ stage, progress }) => {
    let proText = `当前下载进度: ${stage} ${progress}%`
    spinner.text = proText
    if (progress === 100) {
        spinner.text = proText + ' 下载完成'
    }
}

module.exports.clone = async (repo) => {
    const git = SimpleGit({ progress: progress })
    await git.clone(repo);
    process.exit();
}
```

**Comment by xiaoxian521** [comment]
Wow, thank you for your advice
It's perfect

**Comment by steveukx** [comment]
No problem, please do open a new issue if you have any further issues
