### ISSUE TITLE
Ability to set author of a commit

### ISSUE THREAD

**Issue by keirlawson** [steveukx/git-js#53]
This would be really useful

**Comment by keirlawson** [comment]
Why was this closed, has this been implemented? I can't see mention of it in the docs.

**Comment by steveukx** [comment]
Looks like user-error, I'll reopen for you.
Please can you add to this issue the git command you want to run, and preferably open a pull request with appropriate tests.
Thanks

**Comment by keirlawson** [comment]
So ideally this would be an option on the .commit ie .commit(message, { author: 'some author' }, handlerFn)

**Comment by Luncher** [comment]
When this feature can add it?

**Comment by Luncher** [comment]
When this feature can add it?
