### ISSUE TITLE
Could not load source task-options.ts

### ISSUE THREAD

**Issue by antonszilasi** [steveukx/git-js#534]
I am attempting to use simple-git within my node js app.

simple git works totally fine when I use it as an independent script (for example simple-git.js) and run using `node simple-git.js `however when I attempt it use it within
my node app I get the following error even though simple git is installed!

` 'c:\Users\ajszi\Documents\speed_speedengine\app\node_modules\simple-git\src\lib\utils\task-options.ts': Unable to retrieve source content.`

Within this module task-options.js exists but task-options.ts doesn't why is simple-git searching for task-options.ts?

**Comment by steveukx** [comment]
Hi, could you share the code for your `simple-git.js` file along with the version of `simple-git` and node.js you're using?

The TypeScript files (eg `task-options.ts`) are only present in the source of the library, there are type definitions (eg `task-options.d.ts`) in the bundled content so you can use `simple-git` in a TypeScript application without the need for a separate `@types/...` dependency.

If you are running in a debug environment, there are source maps also provided with `simple-git` (eg `task-options.js.map`) which can be used to step through the source as though it is there. The source map is the only place the TypeScript version is mentioned.

Have you installed `simple-git` with either `npm install simple-git` or `yarn add simple-git` or by another mechanism? and are you running is with `node` directly, or are you using `ts-node` (either directly or by running `ts-node/register` in your `simple-git.js` file somewhere)?

**Comment by antonszilasi** [comment]
@steveukx thank you for your quick response!

1. The code can be seen as follows:
![image](https://user-images.githubusercontent.com/8773483/101216786-58768780-363d-11eb-8cde-a928c6e5a117.png)

2. simple-git was installed simply by 'npm install simple-git' see the screenshot below:
![image](https://user-images.githubusercontent.com/8773483/101217083-f79b7f00-363d-11eb-8200-b7cb356eaf21.png)

I have no idea why npm -v simple-git returns version 5.6.0 shouldnt it return 2.24.0?

3. I have tried running node directly through node app.js and through nodemon app.js and through mocha (for testing)

**Comment by antonszilasi** [comment]
Ok I actually managed to solve this issue by promisifying it it

still id be curious what was happening above, hopefully this issue is still helpful to you

![image](https://user-images.githubusercontent.com/8773483/101222109-4cdb8e80-3646-11eb-8392-a0abb419c275.png)
