### ISSUE TITLE
TypeError: Object fromEntries is not a function

### ISSUE THREAD

**Issue by antonszilasi** [steveukx/git-js#538]
simple-git 2.24.0 is sometimes throwing this error:

I am using express with node.js 

![image](https://user-images.githubusercontent.com/8773483/101691300-c0591380-3a2b-11eb-8410-a4cf4580b7cb.png)

**Comment by antonszilasi** [comment]
let me know what other info is required

**Comment by steveukx** [comment]
The `git.log` method uses `Object.entries` and `Object.fromEntries` which should both be available in node v12 and above.

Which version of node are you using?

**Comment by antonszilasi** [comment]
@steveukx looks like I need to upgrade node?
![image](https://user-images.githubusercontent.com/8773483/101712623-2b6a1080-3a53-11eb-9256-af06d97b084a.png)

**Comment by steveukx** [comment]
Upgrading node would be a good option (the LTS release is now version 14), but if that's not an option for you, please add a dependency on `core-js@3` and use their polyfills:

```
require('core-js/stable/array/flat-map');
require('core-js/stable/object/from-entries');
require('core-js/stable/object/from-entries');

const simpleGit = require('simple-git');
```

**Comment by antonszilasi** [comment]
thanks that appears to have fixed it
