### ISSUE TITLE
git config --get remote.origin.url Not working

### ISSUE THREAD

**Issue by BioPhoton** [steveukx/git-js#539]
I tried `git.raw(['config --get remote.origin.url'])` with works directly, but it tells me `Error: git: 'config --get remote.origin.url' is not a git command. See 'git --help'`

Is there a way to run this command?

Thanks for your help!

**Comment by steveukx** [comment]
There are some examples of using `git.raw` in the [complex-requests examples](https://github.com/steveukx/git-js#complex-requests) section in the readme... `git.raw` should be called either with an array of strings (where each item represents one command) or varargs of strings:

```
// use as varargs
git.raw('config', '--get', 'remote.origin.url')

// use as array of strings
git.raw(['config', '--get', 'remote.origin.url'])
```
