### ISSUE TITLE
message.flatMap is not a function

### ISSUE THREAD

**Issue by Yahiko7** [steveukx/git-js#548]
![image](https://user-images.githubusercontent.com/15901380/102332453-10ede500-3fc7-11eb-9c9e-7b094f56eb48.png)

**Comment by steveukx** [comment]
Thanks for reporting this issue, I have now reinstated support for node 10 but support will be removed in version 3 of the library to be released next year, at which point you would need to refer to [legacy node versions](https://github.com/steveukx/git-js/blob/main/docs/LEGACY_NODE_VERSIONS.md) in the docs for how to import the necessary polyfills.
