### ISSUE TITLE
.flatMap(...) is not iterable

### ISSUE THREAD

**Issue by renqi7** [steveukx/git-js#551]
![image](https://user-images.githubusercontent.com/39795406/102442528-86a58f80-405f-11eb-8581-d380c525c8af.png)

**Comment by steveukx** [comment]
This is resolved in version 2.30.0, please upgrade to the latest version.

As this error is only found in nice version 10 or below, support for which will be removed in version 3 of the library to be released next year, you may want to either upgrade node or have a look at the at the [legacy node versions](https://github.com/steveukx/git-js/blob/main/docs/LEGACY_NODE_VERSIONS.md) docs for how to import the necessary polyfills.
