### ISSUE TITLE
Feature request: Global parameters

### ISSUE THREAD

**Issue by BenBirt** [steveukx/git-js#559]
Firstly, thank you very much for simple-git!

I'd love to be able to pass global parameters to every invocation of `git`. In particular it'd be extremely useful to be able to pass configuration parameters instead of modifying the local config file (e.g. `git -c foo=bar`).

I imagined this as another field in `SimpleGitOptions`.

**Comment by BenBirt** [comment]
Something like: https://github.com/steveukx/git-js/compare/main...BenBirt:main

(Note that I haven't tested this, just wanted to illustrate what I meant! I'm happy to open a PR if this suggestion is helpful.)

**Comment by steveukx** [comment]
Hi, apologies it's taken a while to get back to you, but thank you for the link to your repo.

I'm planning a more plugin style approach for the forthcoming versions of `simple-git` so have opted to use that for providing the custom arguments here. From version 2.32.0 (on npm now) you can use the SimpleGitOptions [config](https://github.com/steveukx/git-js#per-command-configuration) option to supply your custom config:

```
const git = simpleGit({ config: ['foo=bar'] });
git.pull(); // runs "git -c foo=bar pull"
```

If you have any trouble with the new version, please do open a new issue / pull request.

**Comment by BenBirt** [comment]
Thanks!
