### ISSUE TITLE
Allow to override git config options for a single command

### ISSUE THREAD

**Issue by alisey** [steveukx/git-js#562]
Example of a command I want to run:
```shell
$ git -c http.proxy=someproxy pull
```

When options added via `.addConfig(key, value)`, they are persisted in the local config file.

`git.pull({'http.proxy': 'someproxy'})` fails because the config options need to specified before the command name.

`git.raw(['-c', 'http.proxy=someproxy', 'pull'])` works, but you have to work with the raw output.

---

My use case is disabling the global credentials helper when authenticating over HTTPS with `GIT_ASKPASS`:
```shell
$ export GIT_ASKPASS=/path/to/askpass
$ export GIT_TERMINAL_PROMPT=0
$ git -c credential.helper= pull
```

I'm using `GIT_ASKPASS` instead of `git().clone('https://${USER}:${PASS}@${REPO}')` because when you clone like that the password gets written in plain text to `.git/config` of the cloned repo.

**Comment by steveukx** [comment]
Hi, thank you for opening the issue - this is now possible using version 2.32.0 on npm:

```
const git = simpleGit({ config: ['http.proxy=someproxy'] });
await git.pull() 
```

If you have any problems using the new version, please do open a new issue.

**Comment by alisey** [comment]
Thank you so much, it's working great!
