### ISSUE TITLE
should check git version when new Git(fpath, opt) and throw an error when version is too old

### ISSUE THREAD

**Issue by fishbar** [steveukx/git-js#566]
some old service install git version <= 2,  then  the git log --prettyformat=xxx not work currect. 

so if the module check the git version  in constructor function,  user can find error at very begining,  and save a lot of debug time

**Comment by steveukx** [comment]
Hi, thanks for creating the issue and the pull request #567 .

Git version 2 was released in 2014 with all of the 1.x releases having now been fully out of support for a few years now. I'll make a specific section of the FAQ for supporting old versions in the log formatting in the next version.

**Comment by steveukx** [comment]
This is [available in the readme](https://github.com/steveukx/git-js#log-format-fails) for versions 2.34.2 onward
