### ISSUE TITLE
TypeScript: git.reset() doesn't allow string arg for reset mode

### ISSUE THREAD

**Issue by ockham** [steveukx/git-js#575]
When attempting to compile a script that uses `simple-git` with TypeScript, I'm getting the following error for a line that contains `await simpleGit.reset( 'hard' )`:

```
bin/plugin/lib/git.js:108:25 - error TS2769: No overload matches this call.
  Overload 1 of 3, '(mode: ResetMode, options?: string[] | ResetOptions | undefined, callback?: SimpleGitTaskCallback<string, GitError> | undefined): Response<...>', gave the following error.
    Argument of type '"hard"' is not assignable to parameter of type 'ResetMode'.
  Overload 2 of 3, '(mode: ResetMode, callback?: SimpleGitTaskCallback<string, GitError> | undefined): Response<string>', gave the following error.
    Argument of type '"hard"' is not assignable to parameter of type 'ResetMode'.
  Overload 3 of 3, '(options?: string[] | ResetOptions | undefined, callback?: SimpleGitTaskCallback<string, GitError> | undefined): Response<string>', gave the following error.
    Argument of type '"hard"' is not assignable to parameter of type 'string[] | ResetOptions | undefined'.

108  await simpleGit.reset( 'hard' );
```

Reading [typedefs](https://github.com/steveukx/git-js/blob/4b754f568ed85163ef0291df99b70b8b0f3c1ec6/typings/simple-git.d.ts#L478-L499) and [unit tests](https://github.com/steveukx/git-js/blob/0fc658bcd89e9241dc84c3547b28f824e7198156/test/unit/reset.spec.ts#L14-L18), it seems like I need a type assertion to `ResetMode`:

```
await simpleGit.reset( 'hard' as ResetMode );
```

However, this isn't clearly reflected in [the docs](https://github.com/steveukx/git-js#git-reset):

> [the argument] sets the reset mode to one of the supported types (use a constant from the exported `ResetMode` enum, **or a string equivalent**: `mixed`, `soft`, `hard`, `merge`, `keep`)

(Highlight mine.)

I'm not familiar enough yet with TypeScript, but is there any way to allow passing these strings directly (without the type assertion)? Otherwise, it'd be great to document that it's required when using TS.

**Comment by steveukx** [comment]
Hi, when using TypeScript it is currently necessary to either use the `ResetMode` enum, or cast the string with `as ResetMode` in order to be recognised as a valid reset mode - examples of both can be found in the [unit tests](https://github.com/steveukx/git-js/blob/main/test/unit/reset.spec.ts#L56). For JavaScript you only need supply the string equivalent to one of the `ResetMode` values.

If you would prefer to use a string without type information, you can use an array of strings (overload 3 in your issue detail) to pass any supported strings to the underlying `git reset` command:

```typescript
// to use the enum directly
import simpleGit, {ResetMode} from 'simple-git';
simpleGit().reset(ResetMode.HARD);
```

```typescript
// to use strings without type information
import simpleGit, {ResetMode} from 'simple-git';
simpleGit().reset(['--hard']);
```

```javascript
// to use javascript
const simpleGit = require('simple-git');

// with a string literal
simpleGit().reset('hard');

// or with the constant
simpleGit().reset(simpleGit.ResetMode.HARD);
```

**Comment by steveukx** [comment]
From your downstream PR, it looks as though `lib/git.js` would work fine with the updated version of `simple-git` - you just need to change the import from `require('simple-git/promise')` to be `require('simple-git')` as all previously chained commands are now also async awaitable.

**Comment by ockham** [comment]
> From your downstream PR, it looks as though `lib/git.js` would work fine with the updated version of `simple-git` - you just need to change the import from `require('simple-git/promise')` to be `require('simple-git')` as all previously chained commands are now also async awaitable.

Thanks for looking! We've made that change, it's it's working nicely :+1: (It's really just the TypeScript ignore I was hoping to maybe get rid of :sweat_smile: -- but it's of course not so bad to keep it around a little longer.)
