### ISSUE TITLE
Progress Handler incompatible with non-English locales

### ISSUE THREAD

**Issue by ockham** [steveukx/git-js#579]
The new [progress handler feature](https://github.com/steveukx/git-js#progress-events) (in v2.35.0) is great -- thanks a lot for implementing it!

Here's a [video](https://github.com/WordPress/gutenberg/pull/28848#pullrequestreview-592747744) of it in action. Note that while implementing this change, I found that it didn't work on my own system, whereas it worked for my coworker. I [suspect](https://github.com/WordPress/gutenberg/pull/28848#issuecomment-780814208) that the reason is that my locale is set to German, and the [RegEx that's looking for progress messages](https://github.com/steveukx/git-js/commit/5508bd4b10c7bb5233f93446931cdaa90ffeae4f#diff-3e408f15a975cc4cecd0de8fdfc86a92f1fd2202e3aa3d92d57f7bdc1f9e8fdfR18) is "hard-wired" to an English progress message (`Receiving objects:`) -- which it can't find in `git`'s German-language output on my system (would be `Empfange Objekte:` for me). (My coworker's locale is set to English.)

Would it be possible to force English by setting an environment variable (e.g. `LC_ALL=C`) when spawning `git`, in order to make the progress handler work?

**Comment by steveukx** [comment]
Hi, looks great in the video.

The published version supports any stage in the RegExp - https://github.com/steveukx/git-js/blob/v2.35.0/src/lib/plugins/progress-monitor-plugin.ts#L18, so as long as the non-english locale conforms to the format `/^([a-zA-Z ]+):\s*(\d+)% \((\d+)\/(\d+)\)/` (eg: `Empfange Objekte: 20% (2/10)`) the progress would be matched and the stage property set to `empfange`.

I see in your pull request, you're using `git.fetch` which doesn't currently auto-add the `--progress` command, please try changing that line to be `await git.fetch( 'origin', source.ref, [ '--progress' ] );` as an interim until I can publish the next version to do it automatically for you.

**Comment by ockham** [comment]
Hi @steveukx, and thanks for your quick reply! (And a great tool!)

> The published version supports any stage in the RegExp - https://github.com/steveukx/git-js/blob/v2.35.0/src/lib/plugins/progress-monitor-plugin.ts#L18, so as long as the non-english locale conforms to the format `/^([a-zA-Z ]+):\s*(\d+)% \((\d+)\/(\d+)\)/` (eg: `Empfange Objekte: 20% (2/10)`) the progress would be matched and the stage property set to `empfange`.

Ah, right! Seems like I was looking at the wrong RegEx :sweat_smile: 
 
> I see in your pull request, you're using `git.fetch` which doesn't currently auto-add the `--progress` command, please try changing that line to be `await git.fetch( 'origin', source.ref, [ '--progress' ] );` as an interim until I can publish the next version to do it automatically for you.

Hmm, I actually meant to use the progress handler for the [`git.clone` command](https://github.com/WordPress/gutenberg/pull/28848/files#diff-5a08defd70ab4f4a6f61d7c4acfe4b5d6609f294c4a0a8895dd98fc4703a04bcR123-R128) right before the `git.fetch`. Anyway, I tested my PR again locally, and this time, [it worked](https://github.com/WordPress/gutenberg/pull/28848#issuecomment-781499293) :tada: (My working hypothesis is that I didn't properly remove my local git clone before running the relevant command.)

Anyway, looks like this issue can be closed! :smile:

**Comment by zlocate** [comment]
Progress plugin does not work for Russian locale for git clone command.

In my case, Git clone output contains Cyrillic symbols (output is "Определение изменений:  ${progress}% (${processed}/${total}") where "Определение изменений" don't match regex part `^([a-zA-Z ]+)`  

This issue affect any non-English locale.
Correct regexp, that works with any locale is `/^(\s\S)+:\s*(\d+)% \((\d+)\/(\d+)\)/`

**Comment by steveukx** [comment]
@zlocate thanks for pointing this out - the new version 2.45.1 will support non-english characters.
