### ISSUE TITLE
New required property "config" is not well documented or may not need to be required

### ISSUE THREAD

**Issue by ssmereka** [steveukx/git-js#580]
Looks like a required property `config` was [recently](https://github.com/steveukx/git-js/commit/f2c3d297c4bdad56ec0c4b77eb534999fdceead6#diff-e29efb3f1d48fff1ad36c954aac43105e81192c233bcf90249e4592a82f097fa) added to `SimpleGitOptions`, as seen [here](https://github.com/steveukx/git-js/blob/main/src/lib/types/index.ts#L72).  However the documentation does not show this as a required value.

![Screen Shot 2021-02-18 at 10 51 11 AM](https://user-images.githubusercontent.com/489291/108406727-a2e8b880-71d7-11eb-8653-6a3391df523b.png)

Should it maybe have been an optional value?  eg `config?: string[];`

Either way, I was updating our dependancies and was a little confused by the error message thrown.  To fix I just added the `config` value.

![Screen Shot 2021-02-18 at 10 55 55 AM](https://user-images.githubusercontent.com/489291/108406905-e17e7300-71d7-11eb-869f-e2d0bb24c099.png)

**Comment by steveukx** [comment]
Hi, thank you for opening this issue.

The `simpleGit` builder function actually accepts a `Partial<SimpleGitOptions>` as all of the properties are optional, this is now reflected in the docs published as `2.35.1`
