### ISSUE TITLE
Braking change when deprecating ListLogSummary TS type

### ISSUE THREAD

**Issue by lGSMl** [steveukx/git-js#586]
https://github.com/steveukx/git-js/blob/a0549200deb48d5b54bea42f0b7ad1144ab0d7b1/typings/response.d.ts#L305
was left without default type for generic
https://github.com/steveukx/git-js/blob/d3e8dc7380d5730c57c48072ef62999f62aa7951/typings/response.d.ts#L453

Introduced in https://github.com/steveukx/git-js/pull/533

removing default type for generic results in error for the client using this API, if it was used without specifying concrete type before deprecation

e.g.

```
 async log(): Promise<ListLogSummary> {
        return this.simpleGit.log();
    }
```

will return 
`Generic type 'ListLogSummary' requires 1 type argument(s)`

I understand that there is another interface with default type to use now, but it still was unpleasant surprise and not sure why default type could not be preserved while deprecating

**Comment by steveukx** [comment]
Hi, thank you for pointing this out - there were no tests left using the deprecated interface which let this one slip through. The new version `2.35.2` on npm now re-introduces support for the `ListLogSummary` without a generic.

If you have any other problems using the library, please do open a new issue.
