### ISSUE TITLE
Handle timeout of processes

### ISSUE THREAD

**Issue by buxxi** [steveukx/git-js#590]
We're using this library in MagicMirror to check if there is a new version available for the main application or any 3rd party modules.

A while back I found out that the application didn't close finished processes completely (https://github.com/MichMich/MagicMirror/issues/1907) and that it was because of the update checking. We tried to upgrade to the newest version of simple-git but the problem still persisted.

And I've looked through the documentation without success for setting some kind of timeout for the calls or how to close the previous calls.

The relevant code is here:
https://github.com/MichMich/MagicMirror/blob/10dc315f3b96ebb5e980e47a21011d44bb9da979/modules/default/updatenotification/node_helper.js#L72

**Comment by steveukx** [comment]
Hi, are you currently finding that the spawned `git` processes timeout and therefore throw? If so you can handle that in your calling function by changing to something like this:

```javascript
performFetch () {
  simpleGits.forEach(async (sg) => {
    try {
      const data = await sg.git.fetch(['--dry-run']).status();
      data.module = sg.module;

      const data2 = await sg.git.log({ "-1": null });
      if (data2.latest && "hash" in data2.latest) {
        data.hash = data2.latest.hash;
        this.sendSocketNotification("STATUS", data);
      }           
    } catch (e) {
      // handle any errors here, this should catch any reason for failure in the underlying child process
    }
  });

  this.scheduleNextFetch(this.config.updateInterval);
},
```

If you are targeting an older version of node that doesn't support async functions, you can implement the same with promise chains followed by a trailing `.catch(e => {})`.

There currently isn't a mechanism for forcibly closing long-running tasks after a set timeout, I will look at adding a new feature for that, but in the interim please let me know if adding error handling to your application resolves your issue.

If the issue persists, please run with [debug logging enabled](https://github.com/steveukx/git-js#enable-verbose-logging) and send the output of the logs. Thanks

**Comment by buxxi** [comment]
Hi,

Thanks for the quick response!

No, our original issue is that the git process isn't being closed and the system keeps getting zombie processes.

```
> ps ax | grep "Z"
 430199 ?        Z      0:00 [git-remote-http] <defunct>

> pstree -p -s 430199
systemd(1)───containerd(385398)───containerd-shim(411902)───node(411920)───git-remote-http(430199)
```

and the only thing running in a container is the node-application for MagicMirror and the only thing using simple-git is this update checker.

The first thing I noticed when debugging was that the callback for fetch() was never called with neither an error nor a success response. That was because of using urls with git:// and it got stuck on waiting for standard input, that was mainly my own fault and not the expected usage. Now I only use https:// and it works, but like once in a week (with an update check ever 10min) I still get a zombie process like the one above.

I could probably modernize the code to use async/await but I fail to see how that would solve the problem? The old style should still work right? And even if an exception is thrown and is unhandled the underlying git-process should have been closed already?

I could probably try with the debug logging but it will take me a week or two to reproduce the error.

**Comment by steveukx** [comment]
You can use the new [timeout plugin](https://github.com/steveukx/git-js/blob/main/docs/PLUGIN-TIMEOUT.md) to `SIGINT` kill `git` processes that have stopped responding by configuring the `block` timeout in milliseconds. 

As each of the items in the `simpleGits` array has its own instance of `simple-git`, looping over the array with a ` forEach` to synchronously trigger the `git.fetch` you will spawn a new child process for each item in the array. As there are limits to the number of child processes the node process can reliably spawn and marshal data between, I do recommend using a queue rather than a `forEach` directly.

As an example - use [parallelLimit](https://caolan.github.io/async/v3/docs.html#parallelLimit) from the [async](https://www.npmjs.com/package/async) library:

```javascript
const { parallelLimit } = require('async');

performFetch() {
    const self = this;
    const concurrentTasks = 4;

    parallelLimit(
        simpleGits.map((sg) => {
            return function (queue) {
                sg.git.fetch(["--dry-run"]).status((err, data) => {
                    data.module = sg.module;

                    if (err) {
                        return queue(null, { sg: sg, ok: false, error: err });
                    }

                    sg.git.log({ "-1": null }, (err, data2) => {
                        if (err) {
                            return queue(null, { sg: sg, ok: false, error: err });
                        }

                        if (data2.latest && "hash" in data2.latest) {
                            data.hash = data2.latest.hash;
                            self.sendSocketNotification("STATUS", data);
                        }

                        queue(null, { sg: sg, ok: true })
                    });

                });
            }
        }), 
        concurrentTasks,
        (err, result) => {
            const fails = result.filter(r => r.error);
            console.log(`Processed ${simpleGits.length} modules, found ${fails.length} modules in error`);
        }
    );
}
```

**Comment by buxxi** [comment]
Thank you!

I will discuss this further with the MagicMirror devs but I think we have enough info to finally fix this.
