### ISSUE TITLE
Simple way to output git command performed by simple-git

### ISSUE THREAD

**Issue by nvuillam** [steveukx/git-js#593]
Using [outputHandler from example](https://github.com/steveukx/git-js#piping-to-the-console-for-long-running-tasks), command is always "git" , and not the effectively called command

In such code `command` variable should contain git checkout... , not just 'git'

![image](https://user-images.githubusercontent.com/17500430/109951291-cdf60080-7cdd-11eb-9a23-f7e792655cc0.png)

Is there a simple way to be able to get the effective command so I can log it ?

Many thanks !

**Comment by steveukx** [comment]
Hi, I've updated the example to match the type docs so you can now see the trailing `args` parameter that should do exactly as you need:

```
function outputHandler (bin, stdOut, stdErr, args) {

  // the name of the binary used, defaults to git, see customBinary for more info
  assert.equal(bin, 'git');
      
  // all other arguments passsed to the binary
  assert(Array.isArray(args));
}
```

The `bin` and `args` are separate as it's possible to set a custom binary instead of the default `git`.

**Comment by nvuillam** [comment]
It works well, thanks @steveukx :)
