### ISSUE TITLE
Get current branch returns empty string 

### ISSUE THREAD

**Issue by iyinchao** [steveukx/git-js#596]
Hi, when I use `branch.current` to get the current branch name, the result is empty string sometimes.

I look into this using `DEBUG=simple-git` and found the command `git branch -v -a` it use output like this:
![image](https://user-images.githubusercontent.com/3615672/110118305-21a73d80-7df5-11eb-93fe-374d05ff2bab.png)

Whenever a `^M` in commit message, the branch info is missing,  `^M` is common to see in commit messages. (When has `\r\r`, or `\r\n`)

There is another issue about this: https://github.com/steveukx/git-js/issues/500

lib version: 2.36.0
os: window 10

**Comment by steveukx** [comment]
Hi, thank you for the extra detail on this issue.
You should find that version 2.36.0 available on NPM now permits the carriage return character.

If you have any other problems, please do create a new issue.
