### ISSUE TITLE
Module 'simple git' has no exported member 'SimpleGitProgressEvent'

### ISSUE THREAD

**Issue by xiaoxian521** [steveukx/git-js#601]
version: 2.36.1
```
  import simpleGit, { SimpleGit, SimpleGitProgressEvent } from 'simple-git';
```

ts Tips Module 'simple git' has no exported member 'SimpleGitProgressEvent'

**Comment by steveukx** [comment]
Hi, thank you for reporting this, a new version will be published shortly that exports `SimpleGitProgressEvent`
