### ISSUE TITLE
Enabling verbose logging programmatically doesn't work

### ISSUE THREAD

**Issue by remal** [steveukx/git-js#603]
I'm trying to programmatically get simple-git to log everything and I can't do it. Basically, the library works fine, but verbose logging - not.

This doesn't help:
```typescript
require('debug').enable('simple-git')
const git = simpleGit(workspacePath)
// ...
```

This doesn't help too:
```typescript
require('debug').enable('simple-git')
process.env.DEBUG = [process.env.DEBUG || '', 'simple-git', 'simple-git:*'].filter(it => it.length).join(',')
const git = simpleGit(workspacePath)
// ...
```

Dependency versions:
* simple-git: 2.36.2
* debug: 4.3.1

What am I doing wrong?

**Comment by steveukx** [comment]
Hi, in order to programatically enable `simple-git` logging, you would need to enable it prior to requiring in `simple-git`:

```
require('debug').enable('simple-git:*');
require('simple-git')().init().then(console.log);
```

**Comment by remal** [comment]
I'm not sure if it's possible, as I import simple-git, as a module like this:
```typescript
import simpleGit from 'simple-git'

require('debug').enable('simple-git:*')
const git = simpleGit('...')
```

**Comment by pereslavtsev** [comment]
the same problem

**Comment by steveukx** [comment]
Hi, you should now be able to programmatically enable/disable debugging as expected with version 2.38.0 available on NPM now:

```
import debug from 'debug';
import simpleGit from 'simple-git';

debug.enable('simple-git');

// this call will have debugging enabled
simpleGit().init().then(() => console.log('DONE');
```

If you have any further problems, there is also now a [debugging guide](https://github.com/steveukx/git-js/blob/main/docs/DEBUG-LOGGING-GUIDE.md)
