### ISSUE TITLE
Hangs when running shortlog

### ISSUE THREAD

**Issue by Eschon** [steveukx/git-js#605]
I tried to get the shortlog of a repository. Since there seems to be no api function for that I tried using the raw function.

```
git.raw(['shortlog', '-ens'], (error, result) => {
    console.log(error);
    console.log(result);
  });
```

But when I run my node script it just hangs. When enabling verbose logging i only get

```
$ node test.js
  simple-git [GitExecutor] [SPAWN] git [ 'shortlog', '-ens' ] +0ms

```

I also tried using promises and running without the -ens options all with the same result.

Other commands like

```
git.raw(['log'], (error, result) => {
    console.log(error);
    console.log(result);
  });
```

run without problems.

I use node v14.16.0 and simple-git 5.0.2

**Comment by steveukx** [comment]
Hi, apologies it's taken a while to reply.

[shortlog](https://git-scm.com/docs/git-shortlog) reads branch details from `stdin` if they're not found in the executed command, so you would need to use:

```
git.raw('shortlog', '-ens', 'HEAD')
```

**Comment by Eschon** [comment]
No problem, turns out a normal log suits my needs better anyways.

But I checked your solution and it works. Thanks!
