### ISSUE TITLE
Change working directory

### ISSUE THREAD

**Issue by Brayden** [steveukx/git-js#61]
Is there any possible way, outside of ```require``` to change between multiple working directories?

I am working in a project that could have multiple git repositories and I need to switch between these folders and branch/commit/push each of them on specific route calls.

**Comment by steveukx** [comment]
Currently, no. It would be possible to implement this with something like the following:

    var git = require('simple-git')
    git()
      .commit().push()
      .then(function () { git._baseDir = 'some-new-dir'; })
      .commit().push();

I would recommend simply creating multiple instances of the `simple-git` class instead though:

    var git = require('simple-git');
    ['dir-a', 'dir-b'].forEach(function (cwd) {
      git(cwd).commit().push();
    });

**Comment by Brayden** [comment]
Would I also be able to require it in an individual route like this?  If I recall correctly "require" will cache it, so I was thinking of also combining it with the ```requireNew``` (https://github.com/gajus/require-new) node library so it wouldn't cache it.


```
module.exports = function(app) {
    app.post('/route/xyz123', function(req, res) {
        var simpleGit = require('simple-git')( workingDirPath );
    }
}
```

If I were to use your suggested approaches (which, by the way THANK YOU so much for your quick reply), I think for my file/folder structure the first approach would be most ideal.  My question comes in when you're doing the initial ```.commit().push()``` prior to doing the change of the ```baseDir```.  Is that first commit/push required prior to a baseDir change or could I simply do:

```
var git = require('simple-git');

git().then(function () { git._baseDir = 'some-new'dir'; });
```

Thank you so much for your help. This means a lot.

**Comment by steveukx** [comment]
Node's `require` will cache the result of requiring the module, but as that value is used as a constructor for a new `Git` instance each time it is called, using it per request in a route like your example will be fine.

The first argument to the main git function is the base directory, so it would probably make more sense to pass it there rather than using a `then` as the step in the chain - but that's entirely up to you :)
