### ISSUE TITLE
To pull the cloned remote branch by using url [where the repo saved] from other directory

### ISSUE THREAD

**Issue by karthiganesh476** [steveukx/git-js#613]
I used code to clone like this from the simple-git npm package

  ```
 var gulp=require('gulp');
   const simpleGit=require('simple-git');
   const git=simpleGit();
   gulp.task('d',  async function()
   {
   await git.clone( repository ,localfoldername,{'--branch': branch name})
   shell.cd(localfoldername)
   await git.pull()
   }
```
While running the gulp task in a terminal in visual studio code as 'd:/default> gulp d'

cloning is done with a local folder
But pull will not occur
Because the gull command worked on 'd:/default>' where there will remote repository 'origin' was saved
It was saved in 'd:/default/localfolder' there I need to pull
Please suggest to me how to overcome this, I am new to both gulp and git

where there is an option to move to remote branch URL then clone

or other suggestions

git

**Comment by steveukx** [comment]
Hi, you just need to set the working directory for the `git` instance to be the new directory, for example:

```javascript
const gulp = require('gulp')
const simpleGit = require('simple-git');

gulp.task('d',  async function() {
 const git = simpleGit();

 await git.clone(repository, localfoldername, {'--branch': branch name});
 await git.cwd(localfoldername);
 await git.pull()
}
```

**Comment by karthiganesh476** [comment]
Hi Steve, I am new to git and gulp, can you please explain with this

```
const gulp = require('gulp')
const simpleGit = require('simple-git');
gulp.task('work',async function(done){
    const git = simpleGit();
  await git.clone('https://gitlab.syncfusion.com/bold-reports/javascript-docs-samples.git', 'other', {'--branch':'JS-61153-js-samples'})
  await git.cwd('D:/otherclonetask/other')
  console.log(process.cwd()) // It shows like this D:/clonetask
 try
{
  await git.pull(); // Then pull operation is not done
  console.log("Success")
  }
  catch(e)
  {
   console.log("Failed")
  }
});
```

**Comment by steveukx** [comment]
Hi, changing the `cwd` of the `simple-git` instance doesn't change the working directory of the `node` process, just where the `simple-git` commands will be run.

If you are still having problems, please see the [debug logging guide](https://github.com/steveukx/git-js/blob/main/docs/DEBUG-LOGGING-GUIDE.md) for details of how to enable logging to better trace your issue


```
const gulp = require('gulp')
const simpleGit = require('simple-git');

gulp.task('work',  async function() {
 const git = simpleGit();
 const repository = 'https://gitlab.syncfusion.com/bold-reports/javascript-docs-samples.git';
 const localfoldername = 'D:/otherclonetask/other';
 const branch = 'JS-61153-js-samples';

 await git.clone(repository, localfoldername, {'--branch': branch});
 await git.cwd(localfoldername);
 await git.pull()
}
```

**Comment by karthiganesh476** [comment]
Thankyou @steveukx  It worked correctly

**Comment by steveukx** [comment]
The `git.exec` method (as documented `.exec(handlerFn) | calls a simple function in the current step`) is a way to call a function, so you can be sure the function is executed between any other chained methods (though in your example you don't chain methods as you just use the one git instance and await each time).

To call out to a shell command like `npm install` etc, you would need to use something like `child_process.exec` - documentation for this is on the node website at https://nodejs.org/dist/latest-v14.x/docs/api/child_process.html#child_process_child_process_exec_command_options_callback

For example:

```
const {exec} = require('child_process');
const repoDir = require('path').join(__dirname, 'new');

exec('npm install', { cwd: repoDir });
```

**Comment by karthiganesh476** [comment]
- Hi @steveukx ,
- My task is to be clone a repository into a local folder with the help of branch
- If the local folder exists I need to do clean and pull
- Then I need to run commands like **"npm install"** and **"gulp build"** commands after that 
- Issue I am facing now: I can't able to clean the untracked files in the directory "example"
- Please help me from this issue

```
const gulp = require('gulp');
const simpleGit = require('simple-git');
var argument = require('yargs').argv;
var process = require('process');
var shell=require("shelljs");
var fs=require('fs')
const repoDir = require('path').join(__dirname,'example');
gulp.task('work', async function (done) {
  const git = simpleGit();
  if(fs.existsSync(repoDir))
  {
    console.log("Started cleaning...")
    await git.cwd(process.cwd() + '/' + 'example');
    await git.clean( "f",(err,res)=>
    {
      if(err)
      {
        console.log(err);
      }
      else
      {
        console.log(res);
      }
    });
    console.log("Cleaned....")
  }
  else
  {
    await git.clone(argument.repo, argument.local, {'--branch':argument.branchh});
    await git.cwd(process.cwd() + '/' + argument.local);
  }
  await git.pull((err, res) => 
  {
    if (err) 
    {
      console.log(err);
    }
    else 
    {
      res = "Pull Success"
      console.log(res);
    }
  });
shell.exec("npm install",{ cwd: repoDir },{async:true})
shell.exec("Gulp build",{ cwd: repoDir },{async:true})
done()
});
```

**Comment by karthiganesh476** [comment]
Hi ,

- Please give example for this .clean(cleanSwitches [,options])
- I want to clean the untracked folders 
- ex: `git clean -d -f -x`
- Please help me to do the above-mentioned code by using simple-git package "command : clean"

**Comment by steveukx** [comment]
Hi @karthiganesh476 - I'm happy to help when there are issues with the library, but please do show how you are trying to use the library.

You can find examples of `git.clean` in the integration tests https://github.com/steveukx/git-js/blob/main/test/integration/clean.spec.ts or unit tests https://github.com/steveukx/git-js/blob/main/test/unit/clean.spec.ts

**Comment by karthiganesh476** [comment]
Hi,

- I want to store the output of simple-git command in variable
- ex: var current_branch= 'git.branch()'
- [ git branch -> if the branch= development then current_branch ="development"]

 ```
const gulp = require('gulp');
  const simpleGit = require('simple-git');
  var argument = require('yargs').argv;
  var shell=require("shelljs");
  var fs=require('fs')
  gulp.task('work', async function (done) {
    const git = simpleGit();
    const repoDir = require('path').join(__dirname,argument.local_folder);
    if(!fs.existsSync(repoDir))
    {
      await git.clone(argument.repository, argument.local_folder, {'--branch':argument.branch});
      await git.cwd(repoDir);
    }
    else
    {
    await git.cwd(repoDir);
     let current_branch;
     let a = git.branch()
      console.log(a);
      let cloning_branch =argument.branch;
      console.log(cloning_branch);
     if(current_branch != cloning_branch)
     {
       console.log("checkout............")
       await git.checkout(argument.branch)
       await git.clean(['f','d','x'])
       await git.pull()
     }
     else
     {
       console.log("Clean........................")
      await git.clean(['f','d','x'])
      await git.pull()
     }

    }
  done()
  });
```
