### ISSUE TITLE
Missing GitPluginError in types

### ISSUE THREAD

**Issue by Qumornik** [steveukx/git-js#616]
Hi,

I think this one https://github.com/steveukx/git-js/blob/cb56da3aee76223faf94ed207c28e396620a3eaa/src/lib/errors/git-plugin-error.ts is missing here https://github.com/steveukx/git-js/blob/cb56da3aee76223faf94ed207c28e396620a3eaa/typings/errors.d.ts

Based on doc https://github.com/steveukx/git-js/blob/cb56da3aee76223faf94ed207c28e396620a3eaa/docs/PLUGIN-TIMEOUT.md we should be able to export it

**Comment by steveukx** [comment]
Hi, thank you for opening this issue... the next version will be available later today including an export for `GitPluginError`
