### ISSUE TITLE
log on test to port the project for fossil scm

### ISSUE THREAD

**Issue by iznotek** [steveukx/git-js#622]
hye, and thanks for the project.
i'm trying to port your project to use the fossil scm instead of git,
but i do not find a way to get the log output of each task spawn execution
on the jest running tests... i try with DEBUG=simple-fossil (after i renamed all),
i tried with debug.enable() in test/__fixture__/instance.ts...
how do you adjust your code parsing behaviour during development using the test suite...?
to be simple, i do not have any log behaviour of the src/ code in jest...
thanks

**Comment by steveukx** [comment]
Hi, the creation of commands to pass to the binary is mostly done with a [task builder](https://github.com/steveukx/git-js/tree/main/src/lib/tasks) and the response parsed by a [parser](https://github.com/steveukx/git-js/tree/main/src/lib/parsers) that processes the output from git line by line.

As the [fossil for git users](https://fossil-scm.org/home/doc/trunk/www/gitusers.md) documentation suggests both the commands and responses would need to change, you may find it easier to use something like [@kwsites/exec-p](https://www.npmjs.com/package/@kwsites/exec-p) (or the node built-in [child_process.spawn](https://nodejs.org/api/child_process.html#child_process_child_process_spawn) as used by `simple-git` to pass commands directly to a child process.

**Comment by iznotek** [comment]
thanks to reply. i do understand your code structure, the task builder and the spawn, and i did begin to change commands and responses accordingly to the fossil behaviour. my question is about the developement process with full logger support on test suite... even on your repo unchanged, if i do `DEBUG=simple-git npx jest --verbose` i do not get any deep log infos about anything on the code itself, like for example in fossilResponse in fossil-executor-chain where there is a lot of logger.info, etc... how do you develop with full code log ?

**Comment by steveukx** [comment]
Debug logs can be configured as per the [logging guide](https://github.com/steveukx/git-js/blob/main/docs/DEBUG-LOGGING-GUIDE.md) for when you're working with the library.

If you need the logs when developing the library itself, you would need to ensure the output of the `debug` library isn't being swallowed by whichever process they're running in (note that running the tests without having built the library will use `babel` to transpile the typescript, and `jest` doesn't run in-band by default.

The tests are run in ci using a simple [`yarn test`](https://github.com/steveukx/git-js/blob/main/.github/workflows/ci.yml#L36), I run single tests / test suites in my IDE as well as running the full set with yarn.

For further assistance, please add a link to your repo so I can better advise you.
