### ISSUE TITLE
fetch remote only working if branch is specified

### ISSUE THREAD

**Issue by dcolens** [steveukx/git-js#633]
I hit an issue where simple-git would not fetch from a remote because it is not passing the remote in the git arguments. 

Looking at the code: https://github.com/steveukx/git-js/blob/c9207da1d8196193b580c5d4fed6101e5c4d4ff8/src/lib/tasks/fetch.ts#L7 the remote is only passed if both remote and branch are provided which was not my case.

could you allow for passing just a remote to git fetch ?

**Comment by steveukx** [comment]
Hi, you can find the typescript types for this method in [simple-git.d.ts](https://github.com/steveukx/git-js/blob/main/typings/simple-git.d.ts#L326-L337) and examples of how it's used in the [unit tests](https://github.com/steveukx/git-js/blob/main/test/unit/fetch.spec.ts).

The usage pattern you're looking for is [calling fetch with an array of option arguments](https://github.com/steveukx/git-js/blob/main/test/unit/fetch.spec.ts#L55-L59).

**Comment by dcolens** [comment]
thanks, from the documentation we were under the impression `fetch('my_remote')` should work, but simple-git just ignores the argument without error/warning in that case, using `fetch(["my_remote"])` yields the expected `git fetch my_remote` command.

Thanks for the quick response in any case :-)
