### ISSUE TITLE
Cannot update submodules in private repos requiring token

### ISSUE THREAD

**Issue by okainov** [steveukx/git-js#635]
Seems like there is no option to pass token in order to update submodules in the private repository.... How could I pass a token?

```

import Git from 'simple-git';
  const git = Git(localDir);
await git.submoduleUpdate(['--init', upgrade.depName]);

```

For initial repo one could modify repo URL and add token there, but for submodules it doesn't seem to work...

**Comment by steveukx** [comment]
Do you know how you would pass the token through if you were using command line `git`?

If you need to pass a custom header, use the [per-command-configuration](https://github.com/steveukx/git-js#per-command-configuration) plugin:

```
import Git from 'simple-git';
const git = Git(localDir, { config: [`http.extraheader=Authorization: Basic ${token}`] });
// any command run through this `git` instance will now include the custom Authorization header
```

**Comment by okainov** [comment]
>Do you know how you would pass the token through if you were using command line git?

I use `.netrc` file in my home directory...

>If you need to pass a custom header, use the per-command-configuration plugin:

Sounds good, I can try this, thanks.

**Comment by steveukx** [comment]
If your submodules have been added with an `http` based remote uri, the `.netrc` file will be picked up as usual when `git` is called by `simple-git`. You may need to check that there is a `.netrc` file configured for the user you're running the `nodejs`  script as.

To help finding issues with authorisation in the sub-module, you may want to [enable git tracing](https://github.com/steveukx/git-js/issues/424#issuecomment-590270247)

**Comment by okainov** [comment]
>If you need to pass a custom header, use the per-command-configuration plugin:

Unfortunately this does not work, because Github has deprecated this type of authentication and it just raises error 400 for our repos (private Github.com repo in private org). `.netrc` though works quite fine

**Comment by steveukx** [comment]
I'll add a note about the `.netrc` version in the auth guide. Thanks for letting me know it's no longer supported by github.
