### ISSUE TITLE
Authentication with http.extraheader

### ISSUE THREAD

**Issue by turbopasi** [steveukx/git-js#639]
Let's say I use `http.extraheader` to clone a private repository, like 

```js
import Git from 'simple-git';

const PTA = "ghp_xxxxyyyyzzzz"; 
const b64 = Buffer.from(PTA).toString("base64");

const git = Git('./', { config: [`http.extraheader=Authorization: Basic ${b64}`] });

( async () => {
  await git.clone("https://github.com/turbopasi/some-private-repo")
})();
```
the PTA does not get stored anywhere , right ? ( Assume the PTA is not hardcoded like in the script above , but provided probably via a request body )

**Comment by steveukx** [comment]
Hi, that is correct - the headers themselves aren't logged by the library by default. They would however be logged if you enabled [verbose debugging](https://github.com/steveukx/git-js/blob/main/docs/DEBUG-LOGGING-GUIDE.md)

**Comment by turbopasi** [comment]
Thanks for confirming @steveukx and for the note about [verbose debugging](https://github.com/steveukx/git-js/blob/main/docs/DEBUG-LOGGING-GUIDE.md) ! 

I was just wondering because when I tried the authentication method used in the documentation (adding auth the remote url `https://${USER}:${PASS}@${REPO}`; ) git stores it in plain text in `/.git/config` - I wasn't sure if that's the same with using the `extraheader` method.
