### ISSUE TITLE
Order mistake in submoduleUpdate 

### ISSUE THREAD

**Issue by LittleCreamSoda** [steveukx/git-js#640]
I suppose that output of this command:
`git.submoduleUpdate('my-submodule-name', ['--remote'])` is gonna be:
`git submodule update my-submodule-name --remote` which doesn't really update the submodule. [The correct way](https://git-scm.com/book/en/v2/Git-Tools-Submodules) to update a particular submodule is gonna be:
`git submodule update --remote my-submodule-name`

**Comment by steveukx** [comment]
Thanks for reporting this. Does the order cause an issue when using `git.submoduleUpdate`? If so - please switch to the `git.raw` interface until such time as there is a fix in the library:

```typescript
git.raw('submodule', 'update', '--remote', 'my-submodule-name')
```

**Comment by LittleCreamSoda** [comment]
Yep, submoduleUpdate is not working, when providing an extra option. Another workaround for this could be: 
`git.submoduleUpdate(['--remote', '--merge',<yourSubmoduleName>])`
