### ISSUE TITLE
git.push(..) syntax to delete remote tags

### ISSUE THREAD

**Issue by davidjgonzalez** [steveukx/git-js#642]
Hi, im trying to figure out how to compute the simplegit's `git.push(..)` syntax to delete remote tags. 

What i want to do is

`git push remote-to-remote-tag-from --delete TAG_TO_DELETE`

however, I cant seem to get 

`git.push(ORIGIN, '', `--delete ${tag}`)` or  `git.push(`${ORIGIN} --delete ${tag}`)` to work...

**Comment by steveukx** [comment]
Hi, you can pass arbitrary extra arguments to `git.push` using a [trailing options array](https://github.com/steveukx/git-js#how-to-specify-options):

```typescript
git.push(['remote-to-remote-tag-from', '--delete', 'TAG_TO_DELETE'])
```

If you find that there is no suitable interface in `simple-git` for the command you need to run - you can also use:

```typescript
git.raw('remote-to-remote-tag-from', '--delete', 'TAG_TO_DELETE')
```

which allows any argument order to be passed on the the `git` process.
