### ISSUE TITLE
.addConfig() only local?

### ISSUE THREAD

**Issue by LetsMelon** [steveukx/git-js#644]
Is it possible to use this command to change global config values?
Because I want to change a global config value but `--local` is hardcoded into the function `addConfigTask`. (The function `Git.prototype.addConfig`uses `addConfigTask`) 
The hardcoded line: https://github.com/steveukx/git-js/blob/9f32df42699edcc8d636dfce28c52517abeb8ea9/src/lib/tasks/config.ts#L6

I could code a fix for this by adding a parameter to `Git.prototype.addConfig` and `addConfigTask`. This parameter could be called `local`. If `local` is true then it's `config --local ...` otherwise `config --global ...` and the default could be `true`.

**Comment by LetsMelon** [comment]
And yes, I know that I can use `Git.raw()`

**Comment by steveukx** [comment]
Hi, thanks for the issue - I've added another argument to `git.addConfig` to allow setting the scope of the configuration:

```
import simpleGit, { GitConfigScope } from 'simple-git';

simpleGit().addConfig('user.name', 'Your Name', false, GitConfigScope.global);
```

**Comment by LetsMelon** [comment]
Thanks!
