### ISSUE TITLE
Commit hash result is wrong when a committed file path contains `[AB] CDE`

### ISSUE THREAD

**Issue by EllaSharakanski** [steveukx/git-js#647]
To reproduce:
1. Have a file called `[AB] CDE FG.xml`.
2. Stage the file (`git.add('.')`).
3. Commit it by using `const res = git.commit('message')`.
4. Check the value of `res.commit`.

Expected: `res.commit` should be equal to the commit hash.
Actual: `res.commit` equals `CDE FG.xml`.

The reason is that `commit` [has a parser](https://github.com/steveukx/git-js/blob/main/src/lib/parsers/parse-commit.ts) that uses the following regex: `/\[([^\s]+)( \([^)]+\))? ([^\]]+)/`, where the third group is the commit hash. Then, `task-parser` [runs this parser line by line](https://github.com/steveukx/git-js/blob/9f32df42699edcc8d636dfce28c52517abeb8ea9/src/lib/utils/task-parser.ts) and mutates `result.commit` with any matches. However, in this case, the commit result looks like this:

    [branch 3f3bfa9] commit-message
      1 file changed, 0 insertions(+), 0 deletions(-)
      create mode 100644 ./[AB] CDE FG.xml

So the first line matches the regex, but also the third line matches it. In this case, `task-parser` overrides `result.commit` with the last match which is `CDE FG.xml`.

A quick fix would be to make the regex smarter (e.g. make it start with `^`), but I think that maybe `task-parser` shouldn't override matches, and instead it should just find the first line that matches and use that result? However, this is a big breaking change so it might not be a good idea.

**Comment by steveukx** [comment]
Hi, thank you for the detailed issue... 

The simple fix of adding the `^` prefix is available in version `2.41.1` on npm now.
