### ISSUE TITLE
Request: .listConfig() add scope

### ISSUE THREAD

**Issue by LetsMelon** [steveukx/git-js#652]
The command `git config --global --list` is possible but it isn't possible to specify the scope in .listConfig(). The line with the commands:
https://github.com/steveukx/git-js/blob/0f75aa476d91f9a761418f9815f745ac61d064b3/src/lib/tasks/config.ts#L41

Similar to #644

**Comment by steveukx** [comment]
The `ConfigListSummary` returns detail for every scope in the same object, use the `files: string[]` array to determine the paths from which `git` reads its config, and use those as keys in the `values: { [fileName: string]: ConfigValues }` object to read specifically those values:

```
const config = await git.listConfig();
const global = config.values[config.files[0]];
```

As more locally defined configuration settings override global values, there is also a `all: ConfigValues` property that shows the combined settings that will actually be applied after all overrides are accounted for:

```
const config = await git.listConfig();
const effective = config.all; // accounts for any local config that overrides the global config
```

**Comment by LetsMelon** [comment]
I think it would be still a good 'improvement' to add the scope to `.listConfig()`, but I think it isn't so important. So if you want to close the issue, please close it. But thanks four your quick response! 👍

**Comment by steveukx** [comment]
This is now supported in version `2.42.0`, for example:

```
const systemConfig = await git.listConfig('system'); 
const localConfig = await git.listConfig(GitConfigScope.local);
```

Note that when you supply a scope, only that scope is returned which doesn't account for the layering of configurations that make up the configuration `git` will be using.
