### ISSUE TITLE
Fatal error because of uncoded user credentials for .clone(), .push(), .pull()

### ISSUE THREAD

**Issue by dmytroantonkin** [steveukx/git-js#653]
If the user credentials contain restricted characters by RFC 1738 https://www.rfc-editor.org/rfc/rfc1738.txt (paragraph 2.2), user will get such error: 

fatal: unable to access 'https://your.vcs.com/whatever.git/': Could not resolve host: username

In my case error was causing question mark, if convert "?" -> "%3f", by UTF-8 charset - error won't appear.
In my opinion, during creation of URL, it should be checked for restricted characters and encode them, if any appears.

**Comment by steveukx** [comment]
Thank you for opening this issue. I'm unsure as to which URL you are expecting the library to validate.
Please would you create a pull request so I can better understand how you think this could be solved.
