### ISSUE TITLE
OpenSSL SSL_connect: Connection was reset in connection to github.com:443

### ISSUE THREAD

**Issue by lou1swu** [steveukx/git-js#654]
When I use `git clone https://github.com/xxx` with shell, I can connect to github.com normally.
But when I use simple-git, it throw error "OpenSSL SSL_connect: Connection was reset in connection to github.com:443".

**Comment by steveukx** [comment]
Sorry for the slow reply - how are you authenticating when you run git commands via the terminal? You may need to ensure there is a `.netrc` file accessible to the user the script runs as.

If you are still having a problem, please also include the script you are using to connect via `simple-git` along with the output of running the script with [verbose debugging](https://github.com/steveukx/git-js/blob/main/docs/DEBUG-LOGGING-GUIDE.md#verbose-logging-options) enabled.
