### ISSUE TITLE
DiffResultTextFile.binary should have type 'false' for type inference

### ISSUE THREAD

**Issue by anatawa12** [steveukx/git-js#657]
In my prediction, `DiffResultTextFile.binary` always be `false` and `DiffResultBinaryFile.binary` always be `true`, Aren't they? If my predictions are correct, both should have literal types for type inference.

**Comment by steveukx** [comment]
Hi, thanks for pointing that out - you can make use of the new types in version 2.41.2 soon to be available on npm
