### ISSUE TITLE
Adding all unstaged files

### ISSUE THREAD

**Issue by EskelCz** [steveukx/git-js#676]
Is there a way to add all unstaged files?
Basically `git add --all` or `git add -A`?

Or to get a list of unstaged files so I can plug it into the add method as array?

Thanks

**Comment by steveukx** [comment]
Similar to adding just one file - you should use:

```
await git.add('--all');
```

Examples of `git.add` can be found in the [unit tests](https://github.com/steveukx/git-js/blob/main/test/unit/add.spec.ts#L11)
