### ISSUE TITLE
how to change the git binary path？

### ISSUE THREAD

**Issue by ljx94nb** [steveukx/git-js#682]
# how to change the git binary path？

I want to use an additional git binary file directory, for example: Users/Desktop/Orca/bin/git, But there is no configuration item.

**Comment by steveukx** [comment]
Hi, [the api](https://github.com/steveukx/git-js#api) you're looking for here is:

| API | What it does |
|-----|--------------|
| .customBinary(gitPath) | sets the command to use to reference git, allows for using a git binary not available on the path environment variable |

Use it as a builder method:

```
import simpleGit from 'simple-git';

const GIT = '/path/to/git';
const git = simpleGit().customBinary(GIT);

git.init().then(console.log);
```

**Comment by ljx94nb** [comment]
> Hi, [the api](https://github.com/steveukx/git-js#api) you're looking for here is:
> 
> 你好，你在这里寻找的 api 是:
> 
> API 空气污染指数	What it does 它的作用
> .customBinary(gitPath) . customBinary (gitPath)	sets the command to use to reference git, allows for using a git binary not available on the path environment variable 设置命令来引用 git，允许使用 git 二进制文件在路径环境变量中不可用
> Use it as a builder method:
> 
> 使用它作为一个构建方法:
> 
> ```
> import simpleGit from 'simple-git';
> 
> const GIT = '/path/to/git';
> const git = simpleGit().customBinary(GIT);
> 
> git.init().then(console.log);
> ```

Thanks a lot!
