### ISSUE TITLE
Synchronous equivalent to asynchronous API

### ISSUE THREAD

**Issue by offbynull** [steveukx/git-js#687]
Are there any plans to add a synchronous API? I understand the benefits of making the API async but some of us aren't in a position to spam the async keyword across all of the functions in our workflow just to use the library.

**Comment by steveukx** [comment]
Hi, I don't have any plan to switch to [spawnSync](https://nodejs.org/dist/latest-v16.x/docs/api/child_process.html#child_process_child_process_spawnsync_command_args_options) at present, but you can make use of the `Promise` / `callback` versions of each of the commands in the library if you prefer to avoid the `async` keyword:

```typescript
import simpleGit from 'simple-git';

const git = simpleGit();

// promise style
git.add('*').commit('message').then(() => console.log('DONE')).catch(e => console.error('FAIL', e));

// callback style
git.add('*', maybeError).commit('message', (e) => maybeError(e) || console.log('DONE'));

function maybeError (e) {
  e && console.error('FAIL', e);
  return e;
}

```
