### ISSUE TITLE
Status reports incorrect 'current' branch when on a detached head

### ISSUE THREAD

**Issue by 50Wliu** [steveukx/git-js#693]
Quick repro:
```ts
const git = SimpleGit();
await git.init();
await git.commit('Initial commit', undefined, {
  '--allow-empty': null,
});
await git.checkout((await git.log()).latest.hash);
const status = await git.status();
console.log(status.current);
```

Expected: `null`
Actual: `HEAD`

`git status --porcelain -b -u` at this point reports `## HEAD (no branch)`, and so I would expect simple-git to report current to be `null`.

I can create a PR to fix this, seems like all that's needed is the addition of a new regex.

(Disclaimer: the codebase I'm working on is using simple-git 1.110.0, but it looks like the logic is still incorrect on main.)

**Comment by steveukx** [comment]
Hi, thank you for the detailed issue report.

As `(await git.status()).current === 'HEAD'` has been the case for so long, and is even codified in the tests as the intended behaviour, I have added `detached: Boolean` as a property of the `StatusResult` to provide this information.

The revised version will be available on npm shortly.

**Comment by 50Wliu** [comment]
Ah, I didn't realize there were back-compat reasons for keeping it as HEAD. Thank you for the new detached property!

**Comment by 50Wliu** [comment]
...thanks for trying bot, but really, this can be closed.
