### ISSUE TITLE
git --amend --no-edit not supported/showing deprecation notice

### ISSUE THREAD

**Issue by lenntt** [steveukx/git-js#694]
I'm trying to git amend without changing the previous commit message, (i.e. `git commit --amend --no-edit`)

```
git.commit(null, {'--amend': null, '--no-edit': null})
```
shows a warning:
> simple-git deprecation notice: git.commit: requires the commit message to be supplied as a string/string[], this will be an error in version 3

```
git.commit('', {'--amend': null, '--no-edit': null})
```
just fails, because of empty commit message (no-edit gets ignored)

**Comment by steveukx** [comment]
Hi, to use `git.commit` without any messages being written into the command, you can use an empty array in place of the `null` from your first example:

```
git.commit([], {'--amend': null, '--no-edit': null});
```

**Comment by lenntt** [comment]
great, thanks!
