### ISSUE TITLE
What is The Easy Way To Push files To Github with simple-git

### ISSUE THREAD

**Issue by sorkab** [steveukx/git-js#699]

**Comment by steveukx** [comment]
Depending on whether you already have the GitHub repository cloned or not would change the commands you need to run.

For a worked example in builder style that adds files, commits them then pushed the commit you can check out the [example in the readme](https://github.com/steveukx/git-js#push-with--u).

For help with just the syntax of the push command itself you can use any of the [unit tests](https://github.com/steveukx/git-js/blob/main/test/unit/push.spec.ts) as examples.

as examples
