### ISSUE TITLE
Parser error (Cannot read property 'split' of undefined)

### ISSUE THREAD

**Issue by bushev** [steveukx/git-js#713]
Hello,

I've got an error from parser util then trying to pull from remote in case of conflicts.

```
Error
From github.com:ybushev/test
 * branch            main       -> FETCH_HEAD
fatal: Not possible to fast-forward, aborting.

{
  commands: [ 'pull', 'git@github.com:ybushev/test.git', 'main', '--ff-only' ],
  format: 'utf-8',
  parser: [Function: parser]
}
(node:99399) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at Object.toLinesWithContent (/Users/bushev/IdeaProjects/****-server/node_modules/simple-git/src/lib/utils/util.ts:59:17)
    at /Users/bushev/IdeaProjects/****-server/node_modules/simple-git/src/lib/utils/task-parser.ts:12:24
```

**Comment by steveukx** [comment]
Hi, thank you for opening the issue.

A new version (3.1.0) is now available on npm that recognises this fatal error in a pull and responds with a `GitResponseError<PullFailedResult>` detailing the error.

For more details - please see [GitResponseError](https://github.com/steveukx/git-js/blob/simple-git-v3.1.0/simple-git/src/lib/errors/git-response-error.ts) and [PullFailedResult](https://github.com/steveukx/git-js/blob/simple-git-v3.1.0/simple-git/typings/response.d.ts#L259-L274).

If you have any problems integrating with the new version, please do open a new issue.
