### ISSUE TITLE
git status --ignored

### ISSUE THREAD

**Issue by ahmafi** [steveukx/git-js#718]
Does this library support something like `git.status(['--ignored'])`?

In `StatusResult` I can only see these:

```js
[
  'not_added', 'conflicted',
  'created',   'deleted',
  'modified',  'renamed',
  'files',     'staged',
  'ahead',     'behind',
  'current',   'tracking',
  'detached'
]
```

**Comment by steveukx** [comment]
Hi, ignored files were being ignored entirely from the `git.status` call - I've now included them so when you have supplied `--ignored` to the `git.status` method, they will be listed in the returned `StatusResult`:

```
import simpleGit from 'simple-git';

simpleGit().status(['--ignored']).then(result => {
  console.log('ignored: ', result.ignored);
});
```

Please update to version `3.1.0` on npm now to have ignored files included in the response. If you have any problems upgrading to the new version, please do open a new issue.
