### ISSUE TITLE
Push allows -u flag

### ISSUE THREAD

**Issue by irinchev** [steveukx/git-js#72]
Would it be possible to add an option, allowing us to set the -u flag of the push command? I do 

      var Git = require('simple-git')(localPath);
      Git.init()
            .add('./*')
            .commit("first commit!")
            .addRemote('origin', 'some-repo-url')
            .push('origin', 'master')
            .then(fn);

and then i get the old and famous

     There is no tracking information for the current branch.
     Please specify which branch you want to merge with.
     See git-pull(1) for details

        git pull <remote> <branch>

     If you wish to set tracking information for this branch you can do so with:

       git branch --set-upstream-to=origin/<branch> master

Maybe there is another way of doing that and is currently available? 

Regards, Dani

**Comment by unional** [comment]
I have the exact same need

**Comment by jonlinper** [comment]
+1.
Any workaround to currently do a "git add -u" ?

**Comment by jonlinper** [comment]
Awesome.
Thanks steveukx.

**Comment by unional** [comment]
Thanks!

**Comment by irinchev** [comment]
Awesome! Thanks a lot!!
