### ISSUE TITLE
I need create brach

### ISSUE THREAD

**Issue by njavilas2015** [steveukx/git-js#728]
I need to create a new branch when starting a project the exact command I want to run is git switch -c main but I can't get it to work please help

**Comment by steveukx** [comment]
Hello, you can find more info in the docs on how to specify options: https://github.com/steveukx/git-js#how-to-specify-options

```
// copy current branch to a new branch called 'new-branch-name'
git.branch([ '-c', 'new-banch-name' ]);
```
