### ISSUE TITLE
Provide options example for .diff

### ISSUE THREAD

**Issue by villesau** [steveukx/git-js#737]
Hi,

I'm trying to understand how to use the library but some examples seems to be lacking. I'm trying to pull diff like this: `git diff --exit-code --name-only master`. I figured out it should look something like this: 

```
simpleGit()
  .diff(['--exit-code', '--names-only', 'master'])
  .then(diff => console.log(diff))
```

However I'm getting following error:

```
node_modules/src/lib/plugins/error-detection.plugin.ts:38
            return {error: new GitError(undefined, error.toString('utf-8'))};
                           ^
GitError: usage: git diff [<options>] [<commit> [<commit>]] [--] [<path>...]

    at Object.action (/Users/node_modules/src/lib/plugins/error-detection.plugin.ts:38:28)
    at PluginStore.exec (/Users/node_modules/src/lib/plugins/plugin-store.ts:24:29)
    at /Users/node_modules/src/lib/runners/git-executor-chain.ts:114:40
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (/Users/node_modules/src/lib/runners/git-executor-chain.ts:111:14)
    at GitExecutorChain.<anonymous> (/Users/node_modules/src/lib/runners/git-executor-chain.ts:88:40)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/node_modules/simple-git/cjs/index.js:55:24) {
  task: {
    commands: [ 'diff', '--exit-code', '--names-only', 'master' ],
    format: 'utf-8',
    parser: [Function: parser]
  }
}

```

I think there's likely something wrong with the way I'm trying to use the library, but the API description is not too helpful in what comes to `diff` options: https://github.com/steveukx/git-js#api

**Comment by steveukx** [comment]
Hello, it looks as though you have a typo in your command - `--names-only` should likely be `--name-only` :

```
simpleGit()
  .diff(['--exit-code', '--name-only', 'master'])
  .then(diff => console.log(diff))
```

The error content that you're seeing is the message directly reported by the `git` binary.

**Comment by villesau** [comment]
Oh good catch! However, the documentation could still be improved around it so that the options would be explained to some extent for the diff. It was not immediately obvious that it takes plain git options in.
