### ISSUE TITLE
Git output

### ISSUE THREAD

**Issue by pragma-git** [steveukx/git-js#738]
Is it possible to somehow retrieve the output from git (same as when running git from command line)?  Perhaps in using the outputHandler?

**Comment by steveukx** [comment]
Hi, you can use the `outputHandler` as a means to accessing the `stdOut` and `stdErr` for all commands in a `simpleGit` instance - something akin to:

```javascript
const git = simpleGit().outputHandler((cmd, stdOut, stdErr, ...args) => {
  const out = [];
  stdOut.on('data', buffer => out.push(buffer));
  stdOut.on('close', console.log(Buffer.concat(out).toString('utf8')));
});

git.init();
```

When the method you're using doesn't parse the result, you can access the raw result just from it's completion:

```javascript
console.log(await simpleGit().stash())
```

Or if you know the git command line arguments you would want to use - call the `git.raw()` method instead as that will never parse the response:

```javascript
console.log(await simpleGit().raw('pull', '--ff-only'))
```

**Comment by pragma-git** [comment]
Thanks for quick reply.

I took your example, as is, but for git.clone I do not get any output.  For git.branch I do.

From command line `git clone` there is a lot of output :
```Cloning into 'electron-api-demos'...
remote: Enumerating objects: 6248, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 6248 (delta 15), reused 16 (delta 5), pack-reused 6218
Receiving objects: 100% (6248/6248), 5.33 MiB | 4.01 MiB/s, done.
Resolving deltas: 100% (3769/3769), done.```

Is above possible to reproduce with simple-git?

**Comment by steveukx** [comment]
The `remote:` messages are printed to `stdErr` rather than `stdOut` so you would need to use the `outputHandler` to access them as they're not included in the actual output and therefore also not included in the return of the `.raw()` method.

If you intend to use the `remote:` messages to form a progress update - you can use the [progress plugin](https://github.com/steveukx/git-js/blob/main/docs/PLUGIN-PROGRESS-EVENTS.md)

**Comment by pragma-git** [comment]
I really love this package, and use it for my pragma-git GUI client. 

I still can't  understand how I can retrieve the underlying git-output for the multiple ways it may be presented. Also, I am not sure if it is always presented anywhere.  

My intention is to have a catch-all of git cli output, so that I can log the underlying git response to a file.  If I understand it correctly, this output lands different places ( the return value of simpeGit() for unparsed outputs, remote output to stdErr instead of stdOut, errors to stdErr, and I am not sure if there are more cases).

If possible, would you guide me to some standardized way to catch all git output? Thanks in advance.

**Comment by steveukx** [comment]
I see you're using version 2.x of the library - as you are in active development, please do ensure you upgrade to latest 3.x for ongoing support

**Comment by pragma-git** [comment]
I feel very stupid.  Can't even get it to work running a simplified example directly in node (instead of nwjs).

```
const simpleGit = require('simple-git');  // I am now using 3.1.1


const git = simpleGit().outputHandler((cmd, stdOut, stdErr, ...args) => {
  console.log( 'command = git ' + args.join(' '));  // Pick up and print the git command (works)
  
  // Pick up and print the stdOut and stdErr streams  (fails / empty)
  const out = [];
  stdOut.on('data', buffer => out.push(buffer));
  stdOut.on('close', console.log('stdOut : ' + Buffer.concat(out).toString('utf8')));
  
  const err = [];
  stdErr.on('data', buffer => err.push(buffer));
  stdErr.on('close', console.log('stdErr : ' + Buffer.concat(err).toString('utf8')));
});

git.init();
```

Above script gives
```
command = git init
stdOut : 
```


Command line  `git init` gives :
``` 
Reinitialized existing Git repository in /Users/jan/Documents/Projects/Pragma-git/pragma-git/test_scripts/.git/
```

**Comment by steveukx** [comment]
As you're planning on using the `outputHandler` to log to a file - here is a working version that you can work from:

```javascript

const simpleGit = require('simple-git');

const git = simpleGit();
git.outputHandler(sendGitOutputToFile('log.txt'));

(async function () {
  await git.init();
  await git.add('app.js');
  await git.commit('initial commit');
}())

function sendGitOutputToFile (path) {
  const stream = require('fs').createWriteStream(path, { flags: 'a' });
  let counter = 0;

  return (cmd, stdOut, stdErr, args) => {
    const id = ++counter;

    stream.write(Buffer.from(`\nINIT[${id}] ${cmd} ${args.join(' ')}`));
    
    stdOut.on('data', buffer => stream.write(Buffer.concat([ Buffer.from(`\nSTDOUT[${id}] `), buffer])));
    stdErr.on('data', buffer => stream.write(Buffer.concat([ Buffer.from(`\nSTDERR[${id}] `), buffer])));
  }
}
```

You should find that `log.txt` ends up containing something like:

```
INIT[1] git init
STDOUT[1] Initialized empty Git repository in /Volumes/examples/output-handler/.git/

INIT[2] git add app.js
INIT[3] git commit -m initial commit
STDOUT[3] [main (root-commit) 2ac8b53] initial commit
 1 file changed, 28 insertions(+)
 create mode 100644 app.js
```

**Comment by pragma-git** [comment]
Thanks, I am really grateful for you support 👍.

For reference, I ended up making a wrapper so I can use `simpleGitLog`  as a drop-in replacement for my usual `simpleGit`:

```js
 const simpleGit = require('simple-git');  // Non-logging
 function simpleGitLog(pwd) {  return simpleGit(pwd).outputHandler( sendGitOutputToFile() ) } // Use as with simpleGit, but this one logs through pragmaLog
```

The `sendGitOutputToFile` was adapted from your very helpful answer, with output and some processing moved to `pragmaLog()`. Modified version of `sendGitOutputToFile` : 
```js
function sendGitOutputToFile() {
  let counter = 0;

  return (cmd, stdOut, stdErr, args) => {
    const id = ++counter;

    pragmaLog( `COMMAND[${id}] ${args.join(' ')}`);
    
    stdOut.on('data', buffer => { pragmaLog( `STDOUT [${id}] ${buffer.toString()}`) });
    stdErr.on('data', buffer => { pragmaLog( `STDERR[${id}] ${buffer.toString()}` ) });
  }
}
```

Output to file is forwarded from (`sendGitOutputToFile`) to the function `pragmaLog(message)`, which also performs filtering of URL credentials, and some simplified robustness.  

For completeness : 
```js
function pragmaLog(message){
    message = message.toString();
    
    // Remove anything between :// and @ 
    // Example : BLABLA https://user:passwd@github.com/JanAxelsson/imlook4d.git BLABLA 
    // =>        BLABLA https://CREDENTIALS@github.com/JanAxelsson/imlook4d.git BLABLA
    let cleanedMessage;
    if ( message.includes('://') && message.includes('@') ){
        let before = message.split('://')[0]; // https
        let after= message.split('@')[1];      // github.com/JanAxelsson/imlook4d.git
        cleanedMessage = before + '://CREDENTIALS@' + after;   
    }else{
        cleanedMessage = message;
    }
    
    // Write message to stream
    const stream = require('fs').createWriteStream(MAINLOGFILE, { flags: 'a' });
    
    let timeStamp = new Date().toISOString();
    let space = '   ';
    let output = timeStamp + space + cleanedMessage + os.EOL;
    stream.write( output);
}

// And the following is defined elsewhere:
// const os = require('os');
// const MAINLOGFILE = path to logfile
```
