### ISSUE TITLE
.diff with --quiet: no way to differentiate the result

### ISSUE THREAD

**Issue by eyalpost** [steveukx/git-js#743]
I need a fast way to check if a file or folder have any differences.
Seems like using `--quiet` is the recommended way but it seems like there's no way to get the exit code in order to know whether there is indeed a difference or not.
I tried:
```
await git.diff(['--quiet', 'master']);
```
and 
```
await git.raw(['diff', '--quiet', 'master']);
```
but both just return the output (which is empty because I used quiet) which doesn't help in this case.

Any suggestions?

**Comment by steveukx** [comment]
Hi, apologies for the slow reply - at present the library doesn't support using the exit code in this way.

The current best solution would be to use `hasDiff = !!(await git.diff(['master']))` until there is explicit support for `diff --quiet` as a feature.
