### ISSUE TITLE
Make startPoint optinal for checkoutBranch

### ISSUE THREAD

**Issue by alansouzati** [steveukx/git-js#75]
Hi thanks for working on this library.

What do you guys think about making startPoint optional so that I can do:

```
  simpleGit(root).checkoutBranch('my_new_branch')
```

that results in:

`git checkout -b my_new_branch `

If you guys agree with this change I can send a PR.

**Comment by steveukx** [comment]
Hi

This is actually already available as `simpleGit(root).checkoutLocalBranch('my_new_branch')`.

If you find this doesn't do what you need, please do open a pull request.

- Steve

**Comment by alansouzati** [comment]
got it, I've missed the `checkoutLocalBranch` function. Sorry about that.
