### ISSUE TITLE
Long commit hash for commit method

### ISSUE THREAD

**Issue by josecelano** [steveukx/git-js#757]
It seems the `git.commit(...)` method returns a short commit hash:

```
{
  author: null,
  branch: 'main',
  commit: '6925085',
  root: true,
  summary: { changes: 0, insertions: 0, deletions: 0 }
}
```

Is there a way to get the 40-character hash with the method options?

It seems the `git.log(...)` returns the full hash.

**Comment by steveukx** [comment]
Hi, I don't know of a way to make the `git commit` return long hashes, but you can use `git show` afterward:

```
const {commit} = await git.commit(...);
const longCommit = await git.show([commit, '--pretty=%H', '-s']);
```

**Comment by josecelano** [comment]
thanks, @steveukx, I'll do that in my `SimpleGit` wrapper. I just wanted to know if there were a hidden option for that n the package.
