### ISSUE TITLE
reset with commitId

### ISSUE THREAD

**Issue by Luncher** [steveukx/git-js#76]
can you Give the interface reset a commit id parameter it like: git reset commitId

**Comment by steveukx** [comment]
You can now use `git().reset(['commitId', '--hard'])` where the first argument is any array of options that would be accepted by the `git reset` command

**Comment by GammaNu** [comment]
i've just test theses : 
```
await git(tempRepo).reset('--hard',fromCommit);
await git(tempRepo).reset(fromCommit,'--hard');
await git(tempRepo).raw(["reset","--hard",fromCommit]);
```
Only the third is working :/

**Comment by steveukx** [comment]
Apologies for the delay... only the last one is using the correct API. To pass more than one option to the `.reset` method, you would need to supply them as an array:

```
await git(tempRepo).reset(['--hard', fromCommit])
```
