### ISSUE TITLE
How I can create pull request with git simple

### ISSUE THREAD

**Issue by salemkode** [steveukx/git-js#762]
Well, I have a project where I uploaded the changes to a repository

Of course for security reasons the program will send the changes to a private repository and then I want it to make a merge request to the main repo

nodejs => fork-repo (in my account) done 
(fork-repo PR / MR to original repo) I need that

**Comment by steveukx** [comment]
Hello, what have you tried so far?

You may want to have a look at the docs for setting up a new remote (with `git.addRemote`) and pushing to the remote (with `git.push). For example - https://github.com/steveukx/git-js#push-with--u

To fork a remote or create pull requests, you would need to use tooling for the remote itself. If you are using GitHub you will need either the GitHub website or their library https://www.npmjs.com/package/@octokit/core
