### ISSUE TITLE
Pushing tag after npm version

### ISSUE THREAD

**Issue by Ornhoj** [steveukx/git-js#764]
I'm trying to push the latest version created via `npm version` to github, but the following code doesn't work

package.json
```
{
  script: {
    "version": "node pushVersion.js"
  }
}
```

pushVersion.js 
```
const fs = require('fs')
const packageJson = fs.readFileSync('./package.json')
const version = JSON.parse(packageJson).version || 0

const simpleGit = require('simple-git')
const git = simpleGit()

let latestTag = `v${version}`

git
  .push(['origin', latestTag])
  .exec(() => console.log('%s is on github', latestTag))
```

If I inject `.addTag(latestTag)` before `.push(...)` - the tag gets pushed, but I recieve an error that the tag already exist.

Getting the tags with `.tags(...)` will provice me a list of tags which doesn't contain the latest version bumped by npm version.

How can I push a single tag after npm version?
manually typing `git push origin <tagname> works.

**Comment by steveukx** [comment]
Hi, I would recommend running your code in the `postversion` script in the `package.json`:

```json
{
  ...
  "scripts": {
    "postversion": "git push && git push --tags",
  }
}
```

NPM will already have created a git tag as part of the `npm version` command, so all you need do is a `git push` to push the current `HEAD` and `git push --tags` to push the newly created tag.

In your example you are pushing a new branch with the same name as the tag, rather than pushing the tag itself. If you do want to carry on pushing a branch rather than a tag, you just need to remove the `.addTag` line as NPM has already created the tag for you.

**Comment by Ornhoj** [comment]
Hi @steveukx

First of all thank you for the quick answer. I did see the "postversion" option, but I would rather take an approach that didn't push all tags hence the `git push origin <tagname>`

The reason for the `.addTag` portion is that without it the tag doesn't appear on Githubs tag list.

I had hoped for a "pushLatestTag" approach, but I'll have to fiddle around some more :)

**Comment by steveukx** [comment]
Do you have NPM's [git-tag-version](https://docs.npmjs.com/cli/v8/commands/npm-version#git-tag-version) set to `false` when you run `npm version`? If not, there should be a git tag already created in your local.

Try switching to:

```javascript
const git = simpleGit();
const latest = `v${ require('./package.json').version }`;

Promise.resolve()
  .then(git.tags())
  .then(tags => {
    console.log(`Tag List: `, tags);
    return tags.all.some(tag => tag === latest);
  })
  .then(alreadyTagged => {
    if (!alreadyTagged) return git.tag(latest);
  })
  .then(() => {
    return git.push('origin', latest);
  })
  .then(() => console.log('DONE'))
;

```

If that's still not working as expected - please can you run your code with [debug enabled](https://github.com/steveukx/git-js/blob/main/docs/DEBUG-LOGGING-GUIDE.md) and include the relevant bit of the log in the issue

**Comment by Ornhoj** [comment]
That was perfect! that does exactly what I wanted to achieve. Only "issue" is the `git.tags()` which doesn't return the TagList, hence `tags.all` fails since `tags`will be `undefined`.

I've added the final setup (with corrections) here for future references:

**projectRoot/package.json**
```
{
  ...
  script: {
    "postversion": "node pushVersion.js"
    ...
  }
}
```

**projectRoot/pushVersion.js**
```
const simpleGit = require('simple-git')
const git = simpleGit()
const latest = `v${require('./package.json').version}`

Promise.resolve()
  .then(() => git.tags((err, tags) => tags)) // changed to return the tagList from git.tags()
  .then((tags) => {
    return tags.all.some((tag) => tag === latest)
  })
  .then((alreadyTagged) => {
    if (!alreadyTagged) return git.tag(latest)
  })
  .then(() => {
    git.push('origin') // Added to ensure everything committed is pushed as well
    return git.push('origin', latest)
  })
  .then(() => console.log('Tag "%s" is now available on Github', latest))
```

**Comment by Ornhoj** [comment]
@steveukx I'm closing this issue, since your answer provided me with a working solution
