### ISSUE TITLE
Git status result with '-z' option

### ISSUE THREAD

**Issue by taras-dubyk** [steveukx/git-js#770]
If I run `simpleGit.status(['-z'])` I get almost empty result.

That's because [parseStatusSummary](https://github.com/steveukx/git-js/blob/94c24623bf2f48b66ba1db22b94dbebd42e10f53/simple-git/src/lib/responses/StatusSummary.ts#L123) expects the operation result split by a new line character ('\n').
But if the `-z` option is present the result will be split by a NUL character ('\0') instead;
Also, renamed file parsing logic should be updated, as with the `-z` option the format for rename entries is a bit different ([link](https://git-scm.com/docs/git-status#_porcelain_format_version_1)).

I have to use `-z` option because of file names with non-ASCII symbols.
I know about `git config core.quotepath off`, but it's not applicable for my use case.

**Comment by steveukx** [comment]
Hi, thank you for opening the issue. This was added as a feature in 3.4.0 on March 18th apologies for not having mentioned in the issue... you can now upgrade to version 3.5.0 on npm to start using this.
