### ISSUE TITLE
Leading/tralling single quotes from log()?

### ISSUE THREAD

**Issue by lsm** [steveukx/git-js#78]
I got leading single quotes for commit hash and trailing ones for emails from the result of the `log` calls:

```js
{ latest:
   { hash: '\'b1a3d56dd2065f58835d320901f0fdc905f9d5cb',
    ...
   author_email: '...@gmail.com\''},
   ...
}
```

Which, `git log origin/master..master` returns normally:
`commit b1a3d56dd2065f58835d320901f0fdc905f9d5cb`

I were using simple-git@1.28.0 with node@4.4.0 on Mac.

Is this normal or a bug?

**Comment by steveukx** [comment]
Thank you for point this out - looks like it's been a bug for all 1.x versions. You should now be able to use 1.28.1 from npm with this resolved.

**Comment by lsm** [comment]
Cool, thanks for the fix!
