### ISSUE TITLE
cloning specific branch and commit sha

### ISSUE THREAD

**Issue by abrl91** [steveukx/git-js#780]
Hi, 
I searched on the open and closed issues here and didn't find an answer to my question.
I am trying to clone a specific branch and commit of the repository

this is my code: 

```
async clone(installationId, branchName, commitSHA) {
        const token = await this.getAccessToken(installationId);
        const baseDir = `${os.homedir()}/Dev/git-remote/clone-commit`;
        const repository = `https://amit-amp-org:${token}@github.com/amit-amp-org/sample-test.git`
        await simpleGit({
            binary: 'git',
            maxConcurrentProcesses: 10,
        }).clone(
            repository,
            baseDir,
            ['--branch', branchName])
            .checkout(commitSHA)
    }
```

This is the error I get: 
`GitError: fatal: not a git repository (or any of the parent directories): .git`

But when I check on the baseDir I see the .git file

What am I doing wrong?

**Comment by abrl91** [comment]
OK, I think I got it. I missed the `baseDir` on `simpleGit` configuration options, but now I am getting a different error:
`Cannot use simple-git on a directory that does not exist`. What if I want to create this directory on the fly? while I am cloning the repo?

**Comment by steveukx** [comment]
Hi, you can do this in either of two ways:

```typescript
async function useTwoInstances(repository, branchName, baseDir, commitSHA) {
  await simpleGit().clone(repository, baseDir, ['--branch', branchName]);
  await simpleGit({ baseDir }).checkout(commitSHA);
}

async function changeDirectoryAfterClone(repository, branchName, baseDir, commitSHA) {
  await simpleGit()
    .clone(repository, baseDir, ['--branch', branchName])
    .cwd(baseDir)
    .checkout(commitSHA);
}
```

Likely the easier to create a second instance of `simple-git` using the `baseDir` you cloned into. If you do want to use the same instance throughout though, you can use `git.cwd` to change the working directory for all subsequent tasks.

**Comment by abrl91** [comment]
@steveukx Thank you!
