### ISSUE TITLE
Is there a way to return the full commit hash using the commit method?

### ISSUE THREAD

**Issue by josecelano** [steveukx/git-js#782]
I would like the `.commit` function to return the full commit hash instead of `df462c39`:

```
{
  author: {
    email: 'bot@nautilus-cyberneering.de',
    name: 'NautilusCyberneering[bot]'
  },
  branch: 'issue-22-job-commit-not-created',
  commit: 'df462c39',
  root: false,
  summary: { changes: 0, insertions: 0, deletions: 0 }
}
```

But it seems there is no option also in Git to do it. Apparently, the only option to do it is by using the low-level command git [commit-tree](https://git-scm.com/docs/git-commit-tree).

I see you do not have a wrapper for it and I should use the `.raw` method.

**Comment by steveukx** [comment]
Hi, as far as I am aware `git` will always use the short hash when responding to `git commit`. In order to get the most recent commit you can use:

```
await git.commit(...);
const hash = await git.revparse('HEAD');
```

**Comment by josecelano** [comment]
> Hi, as far as I am aware `git` will always use the short hash when responding to `git commit`. In order to get the most recent commit you can use:
> 
> ```
> const commit = await git.commit(...);
> 
> // generic version to give full hash of the tip of the HEAD
> const headHash = await git.revparse('HEAD');
> 
> // or expand the short hash from the commit
> const commitHash = await git.revparse(commit.commit);
> ```

Thank you @steveukx for your fast reply. I have the feeling that relaying on shorter hashes might produce conflicts in the future. I know that could be very unlikely but that method has an option `--disambiguate:

```
       --disambiguate=<prefix>
           Show every object whose name begins with the given prefix. The <prefix> must be at least 4 hexadecimal digits long to avoid
           listing each and every object in the repository by mistake.
```

I thought that getting the full hash from the beginning was a way to avoid that problem.

**Comment by da2ce7** [comment]
@josecelano @steveukx 

It is possible to change git's settings to stop abbreviating commit id's:
```
git config --local core.abbrev 40
```

In more recent versions of git, we have the explicit option:

```
git config --local core.abbrev "no"
```
