### ISSUE TITLE
Types not loaded with module resolution `NodeNext`

### ISSUE THREAD

**Issue by adam-coster** [steveukx/git-js#786]
[With Typescript 4.6+](https://www.typescriptlang.org/docs/handbook/esm-node.html) we have the new `NodeNext` module and module-resolution option. This opts into using the latest `package.json` rules with Node, wherein the existence of [the `exports` field](https://nodejs.org/api/packages.html#package-entry-points) causes the root-level `types` and `main` fields to be ignored.

The simple-git `package.json` does not specify the `exports['.'].types`, so projects using `NodeNext` cannot load the types. Fortunately this is an easy fix -- I used [patch-package](https://github.com/ds300/patch-package) to patch `simple-git@3.6.0` locally, resulting in the following diff:

```diff
diff --git a/node_modules/simple-git/package.json b/node_modules/simple-git/package.json
index 11611e1..335fe0e 100644
--- a/node_modules/simple-git/package.json
+++ b/node_modules/simple-git/package.json
@@ -45,6 +45,7 @@
   "module": "dist/esm/index.js",
   "exports": {
     ".": {
+      "types": "./dist/typings/index.d.ts",
       "import": "./dist/esm/index.js",
       "require": "./dist/cjs/index.js"
     },
```

Note that the Node docs say that the `types` field should always be first, though in practice I haven't seen that it matters.

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by steveukx** [comment]
Thank you for opening this detailed issue. A new version of `simple-git` will be published to npm today with the fix included.
