### ISSUE TITLE
StatusSummary incorrect if merge conflict has been added but not committed

### ISSUE THREAD

**Issue by soulwu** [steveukx/git-js#793]
run `git merge feat-a` # some conflicts occured
... do something to resolve conflicts ...
run `git add .`

then run `await simpleGit().status()`, got something like
```
StatusSummary {
  not_added: [],
  conflicted: [],
  created: [],
  deleted: [],
  ignored: undefined,
  modified: [],
  renamed: [],
  files: [],
  staged: [],
  ahead: 0,
  behind: 0,
  current: 'feat-b',
  tracking: 'origin/feat-b',
  detached: false,
  isClean: [Function (anonymous)]
}
```

but the merge not finished yet. If i run `git status`, i can see the tips.

**Comment by steveukx** [comment]
Hi, thank you for opening the issue.
To help create a solution for this, please can you run `git status --porcelain -u -b --null` and include here the output of that command? Thanks

**Comment by XeroAlpha** [comment]
You can try `await git.revparse('MERGE_HEAD').catch(() => null)`.
It will return the merge head commit hash if current is merging, otherwise null.
