### ISSUE TITLE
Git log with `--name-only` or `--name-status` always return an empty files array

### ISSUE THREAD

**Issue by Ndpnt** [steveukx/git-js#794]
I would like to list the commits with the path of the changed files associated with them. 

Currently I use `git.log({ '--stat' : null })` which works but can take a while on git repositories with a huge number of commits. 

So I'd like to use the `--name-only` options instead, which I think is faster to run, but when I use this option I always get an empty `files` array. 

With `--stat` option I get this:
```
{
	hash: '4dec0533c6706504ed8681b6f76afb8f43c58dc5',
	date: '2022-05-02T07:27:51+00:00',
	message: 'Start tracking Camaieu Privacy Policy',
	refs: 'HEAD -> master',
	body: 'This version was recorded after filtering snapshot in repository ./data/snapshots with commit 6d608ed\n',
	author_name: 'Open Terms Archive Bot',
	author_email: 'bot@opentermsarchive.org',
	diff: DiffSummary {
		changed: 1,
		deletions: 0,
		insertions: 214,
		files: [{
			file: 'Camaieu/Privacy Policy.md',
			changes: 214,
			insertions: 46,
			deletions: 0,
			binary: false
		}]
	}
}
```

With `--name-only` or `--name-status` option I get this:
```
{
	hash: '4dec0533c6706504ed8681b6f76afb8f43c58dc5',
	date: '2022-05-02T07:27:51+00:00',
	message: 'Start tracking Camaieu Privacy Policy',
	refs: 'HEAD -> master',
	body: 'This version was recorded after filtering snapshot in repository ./data/snapshots with commit 6d608ed\n',
	author_name: 'Open Terms Archive Bot',
	author_email: 'bot@opentermsarchive.org',
	diff: DiffSummary {
		changed: 0,
		deletions: 0,
		insertions: 0,
		files: []
	}
}
```

Whereas I expect to get something like this:
```
{
	hash: '4dec0533c6706504ed8681b6f76afb8f43c58dc5',
	date: '2022-05-02T07:27:51+00:00',
	message: 'Start tracking Camaieu Privacy Policy',
	refs: 'HEAD -> master',
	body: 'This version was recorded after filtering snapshot in repository ./data/snapshots with commit 6d608ed\n',
	author_name: 'Open Terms Archive Bot',
	author_email: 'bot@opentermsarchive.org',
	diff: DiffSummary {
		changed: 0,
		deletions: 0,
		insertions: 0,
		files: ['Camaieu/Privacy Policy.md']
	}
}
```

**Comment by MattiSG** [comment]
We @OpenTermsArchive would really love to have this fixed 🙂 
@Ndpnt offered an implementation in #797, that we published under [`@opentermsarchive/simple-git`](https://www.npmjs.com/package/@opentermsarchive/simple-git) as we really need to use it in https://github.com/ambanum/OpenTermsArchive/pull/875 and would prefer that others benefit as well.

@steveukx As open-source maintainers ourselves, we know how taking that work can be. I see that you are open to sponsoring. We are willing to sponsor this project if that can help with getting improvements like this one merged 🙂 Let me know what would work over here or over email at contact[AT]opentermsarchive[DOT]org.

**Comment by steveukx** [comment]
Hello @MattiSG and @Ndpnt thank you for the pull request, the suggested change is much appreciated.

To add support for more of the formats, please follow #807 for a new version of `simple-git` to be published this weekend that supports both `--name-only` and `--name-status`.

**Comment by steveukx** [comment]
Hi, you can now use `simple-git@3.8.0` on npm with support for `--name-only` and `--name-status` in `git.log`:

```typescript
git.log({ '--name-only': null })
git.log({ '--name-status': null })
```

**Comment by Ndpnt** [comment]
Hi @steveukx, thanks for the publication of a new version of `simple-git` with the support of these options!
