### ISSUE TITLE
`simpleGit` is not callable in TypeScript ESM

### ISSUE THREAD

**Issue by tukusejssirs** [steveukx/git-js#804]
Thanks for this awesome utility!

I tried to use it in an TypeScript ESM module, but running `simpleGit()` gets me an error from TypeScript:

```ts
import simpleGit, {SimpleGit} from 'simple-git'

const git: SimpleGit = simpleGit()

// Output:
error TS2349: This expression is not callable.
  Type 'typeof import("$repo_root/node_modules/simple-git/dist/typings/index")' has no call signatures.
```

When I ignore the error (using `@ts-ignore:next-line`), it runs just fine, therefore I suspect it is an error in the type definition or something

#### Notes

1. I created a TypeScript project that outputs an ESM module based on [@sindresorhus](https://gist.github.com/sindresorhus)’ [recommendations](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm).

2. I tested this using `typescript@4.7.3` and `typescript@4.3.5`; same results.

3. I used `simple-git@3.7.1`.

**Comment by steveukx** [comment]
Hi, as the use of libraries in typescript can be impacted by your tsconfig, please can you create an example repo in order for me to look into this for you?

In order to ensure `simple-git` can be imported by TypeScript, there is an example that gets run as part of the integration tests: https://github.com/steveukx/git-js/tree/main/packages/test-typescript-consumer

**Comment by tukusejssirs** [comment]
Well, I’ve just check the `tsconfig*.json` configs, but I have no idea what might cause this issue.

Here you go my config:

```js
// tsconfig.json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "baseUrl": "./",
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "incremental": true,
    "module": "node16",
    "moduleResolution": "node16",
    "noFallthroughCasesInSwitch": false,
    "noImplicitAny": false,
    "outDir": "./dist",
    "removeComments": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strictBindCallApply": true,
    "strictNullChecks": false,
    "target": "es2020"
  }
}
```

```js
// tsconfig.build.json
{
  "exclude": [
    "node_modules",
    "test",
    "dist",
    "**/*spec.ts"
  ],
  "extends": "./tsconfig.json"
}
```

**Comment by tukusejssirs** [comment]
Okay, I’ve found out that when I change `module` and `moduleResolution` from `node16` to `node` in `tsconfig.json`, all works as expected.

I believe the issue comes from a fact that when using TS 4.7.x + `module` set to `node16`, import paths are required to have `.js` extension (even for `.ts` files; see also microsoft/TypeScript#49083), however, I am not sure about this.

**Comment by tukusejssirs** [comment]
It also does not work with `nodenext`.

@steveukx, do you consider this a bug in `simple-git`? Could this be resolved? I use `@nestjs/testing` for my tests, but it simply fails with `   error TS6046: Argument for '--module' option must be: 'none', 'commonjs', 'amd', 'system', 'umd', 'es6', 'es2015', 'es2020', 'es2022', 'esnext', 'node16', 'nodenext'.` I could create a custom Jest config to overcome the issue, however, I still would like to use `node16`.

**Comment by tukusejssirs** [comment]
Well, I use [`execa`](https://github.com/sindresorhus/execa), but it is written in JS (but contains TS type defs).

[Here](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#ecmascript-module-support-in-node-js) is the official TS guide (sourced from [here](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm)).

Anyway, I tried to build `simple-git` from Git source (`npm i && npm run build`; I also tried `yarn install && yarn run build`) with no changes made by me, but it failed.

```bash
$ node scripts/build.js
ESM: generating esm source
ESM: generating cjs source
ESM: done
$ tsc -p tsconfig.release.json --outDir dist && cp -r typings dist
../../../../node_modules/@types/cache-manager-redis-store/index.d.ts(24,32): error TS2694: Namespace '"/home/ts/node_modules/redis/dist/index"' has no exported member 'RedisClient'.
../../../../node_modules/@types/cache-manager-redis-store/index.d.ts(29,34): error TS2694: Namespace '"/home/ts/node_modules/redis/dist/index"' has no exported member 'ClientOpts'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build stderr:
error Command failed with exit code 2.
error Command failed with exit code 2.
lerna ERR! yarn run build exited 2 in 'simple-git'
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by steveukx** [comment]
The issues relating to `redis` and `@types/cache-manager-redis-store` are unexpected - they're not in the dependency graph for the `simple-git` workspace.

The main difference I see between the types in `execa` and `simple-git` is the use of a default export in `simple-git`. I am happy to add a named export so you would switch to:

```typescript
import { simpleGit, SimpleGit } from 'simple-git';

const git: SimpleGit = simpleGit();
```

Until the new version is released, and for if you see this issue with other libraries before they've added support for ESM in TypeScript, you can change the import for `simple-git` as follows:

```typescript
import { default as simpleGit, SimpleGit } from 'simple-git';

const git: SimpleGit = simpleGit();
```

(This approach has been tested with `simple-git` 3.9.0, typescript 4.74 and your tsconfig.json/tsconfig.build.json)

**Comment by steveukx** [comment]
You can now use version `3.10.0` in your ESM TypeScript application, but please be advised that you will need to import the named `simpleGit` export rather than relying on the default export.

(Default exports remain available for backward compatibility with any application still using CJS).

**Comment by tukusejssirs** [comment]
> The issues relating to `redis` and `@types/cache-manager-redis-store` are unexpected - they're not in the dependency graph for the `simple-git` workspace.

Of course! For some reason I didn’t read the error. Sorry for the report of this error.

> I am happy to add a named export so you would switch to:
>
> ```ts
> import { simpleGit, SimpleGit } from 'simple-git';
> ```

Yeah, thanks, it fixes the issue. :pray:

Just a note: wouldn’t it be better to rename `simpleGit` to something else? Its name is same as `SimpleGit` (apart from the casing). Also, don’t you think it should have capital initial letter?

**Comment by steveukx** [comment]
The `simpleGit` export is a factory function rather than a class constructor, so by convention (or at least, the convention I follow) it has a lower case first letter (the class it constructs boils down to a [SimpleGitApi](https://github.com/steveukx/git-js/blob/main/simple-git/src/lib/simple-git-api.ts#L17) which does have the initial capital).

Using the same name as main export and its return type was a style choice, but you can see similar patterns being used in things like `express`:

```typescript
import express, {Express} from 'express';

const app: Express = express();
```

**Comment by pepicrft** [comment]
👋🏼 I'm running into the same issue in [this project](https://github.com/Shopify/cli/pull/1122). The issue happens when the `NodeNext` / `Node16` module resolution is used, and I can't change that because we need it for other packages. I'll do some investigation to see if I can come up with a fix.

**Comment by pepicrft** [comment]
We are also experiencing this issue in the [Shopify CLI](https://github.com/Shopify/cli/pull/1122) when we tried to adopt the module resolution `NodeNext` which we need for other packages. I think the issue is coming from module IDs like `../src/lib/responses/GetRemoteSummary` in `.d.ts` files missing the extension. Is it ok if I open a PR adjusting module IDs to align with ESM?
