### ISSUE TITLE
log gives quoted output

### ISSUE THREAD

**Issue by TuningGuide** [steveukx/git-js#81]
```
	gitRepo
		.log(function(err, log) {
			console.log(log);
		});
```
Gives me hashes with prepended ' and author_email's with appended '. And also the stdoutput is quoted with '

**Comment by steveukx** [comment]
Is this a duplicate of #78?

**Comment by TuningGuide** [comment]
Oh. yes it is. I must have installed it 21 days ago ^^,

**Comment by steveukx** [comment]
No problem!
