### ISSUE TITLE
Create Pull Requests using simple-git app

### ISSUE THREAD

**Issue by abhimeht23** [steveukx/git-js#818]
Hi @steveukx ,

I am creating an express based web app and using the simple-git package for users to clone and push changes. I wanted to know if it's possible to create pull requests using this API? Pls advise.

Thanks,
Abhi

**Comment by steveukx** [comment]
Hi - you may find more information in this question: https://github.com/steveukx/git-js/issues/762#issuecomment-1046226151

To summarise though - to fork a remote or create pull requests, you would need to use tooling for the remote itself. If you are using GitHub you will need either the GitHub website or their library https://www.npmjs.com/package/@octokit/core

**Comment by abhimeht23** [comment]
Thank you @steveukx. It does help. I will close this comment.
