### ISSUE TITLE
github vs gitlab

### ISSUE THREAD

**Issue by abhimeht23** [steveukx/git-js#819]
Hi @steveukx ,

Quick question, I am currently using your simple-git package in my express web app and user account is created on Github. Will this simple-git package still work/compatible if we decide to switch over to GitLab?

Thanks,
Abhi

**Comment by steveukx** [comment]
Hello @abhimeht23 - `git` commands will generally be the same no matter the remote, though the naming convention of pull request branches and the content of the `remote` messages (usually seen when pushing) can differ.

If you do find any inconsistencies between the two when you make the switch please do create a new issue, including the output from Github and GitLab so i can update the parsers (or feel free to open a pull request of course)
