### ISSUE TITLE
check-ignore cannot be used on non-cwd git repos

### ISSUE THREAD

**Issue by NSSwiftSpear** [steveukx/git-js#824]
the actual git check-ignore command does not source the work-tree it's working from from the --git-dir, it's default behavior is to retrieve the working tree from the current working directory if one exists there.

If my current working directory is in any git repo which is not the repo for which I'm trying to check if files are ignored by git, I currently cannot use simple-git to do so.

`git_metrics % git --git-dir /Users/me/git/repo-a/.git check-ignore /Users/me/git/repo-a/README.md
fatal: /Users/me/git/repo-a/README.md: '/Users/me/git/repo-a/README.md' is outside repository at '/Users/me/git/repo-b/git_metrics'`

vs

`git --work-tree /Users/me/git/repo-a --git-dir /Users/me/git/repo-a/.git check-ignore /Users/me/git/repo-a/README.md`

Simplegit should either be able to globally configure the root of the work tree or allow options to pass into check-ignore

**Comment by steveukx** [comment]
Have you set the working directory for the `simple-git` instance? (see [configuration](https://github.com/steveukx/git-js#configuration))

```typescript
const excludedInRepoA = await (
  simpleGit('/Users/me/git/repo-a')
    .checkIgnore('/Users/me/git/repo-a/README.md')
);

const excludedInRepoA = await (
  simpleGit({ baseDir: '/Users/me/git/repo-a' })
    .checkIgnore('/Users/me/git/repo-a/README.md')
);
```
