### ISSUE TITLE
Is there a way to get the exit code of the Git command?

### ISSUE THREAD

**Issue by tukusejssirs** [steveukx/git-js#826]
Exit codes are a good way to determine the failure type without parsing the error message (which might change over the course of time).

For example:

1. Create an empty Git repository.
2. Get log.

Currently `simpleGit(path).log({maxCount: 1)` error is as follows:

```ts
GitError: fatal: your current branch 'main' does not have any commits yet

    at Object.action (file://$repo_root/node_modules/simple-git/dist/esm/index.js:3583:25)
    at PluginStore.exec (file://$repo_root/node_modules/simple-git/dist/esm/index.js:3610:25)
    at file://$repo_root/node_modules/simple-git/dist/esm/index.js:1244:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (file://$repo_root/node_modules/simple-git/dist/esm/index.js:1242:16)
    at GitExecutorChain.<anonymous> (file://$repo_root/node_modules/simple-git/dist/esm/index.js:1226:44)
    at Generator.next (<anonymous>)
    at fulfilled (file://$repo_root/node_modules/simple-git/dist/esm/index.js:50:24) {
  task: {
    commands: [
      'log',
      '--pretty=format:òòòòòò %H ò %aI ò %s ò %D ò %b ò %aN ò %aE òò',
      '--max-count=1'
    ],
    format: 'utf-8',
    parser: [Function (anonymous)]
  }
}
```

When I run `git log` in terminal, it returns `128` exit code which would be simple to use and do something else in comparison with other possible exit codes.

**Comment by steveukx** [comment]
Hi, thank you for the suggestion - I'll look at creating a `GitResponseError` to parse this case - the exit code 128 is a catch-all exit code for git not having shut down cleanly and is used for many kinds of unclean shutdown so can't be relied upon to detect this specific error.

In the meantime, if you would like to add the exit codes to the `GitError` returned by `simple-git`, you can detect the exit code and implement your own errors by supplying an `error` plugin config to the `git` function:

```
import { simpleGit } from 'simple-git';

const git = simpleGit({
  errors (error, result) {
    // the default handler runs first, if it detected an error
    // assign a new property with the task's exit code and return that
    // otherwise continue handling the response.
    return error instanceof Error && Object.assign(error, { exitCode: result.exitCode }) || error;
  }
});
```

**Comment by tukusejssirs** [comment]
Sorry for late answer, I have somehow missed the notification.

---

>  the exit code 128 is a catch-all exit code for git not having shut down cleanly and is used for many kinds of unclean shutdown so can't be relied upon to detect this specific error.

That was just an example. In the example from the issue description, all I wanted to know if it ran successfully (exit code `0`) or not, i.e. if there are any commits already in the repository.

> In the meantime, if you would like to add the exit codes to the GitError returned by simple-git, you can detect the exit code and implement your own errors by supplying an error plugin config to the git function:

If I understand it correctly, it won’t help me, as Git (IMHO) sometimes erroneously exits with a non-zero exit code, e.g. for `git diff` when there are some changes.

I don’t want to change the exit code or create some custom one. All I want to make sure that a command is run successfully, albeit subjectively, based on the exit codes of a particular Git command.

---

A bit OT: I think that [`execa`](https://github.com/sindresorhus/execa) returns a better output than `simple-git`. Although it returns too much IMO, when it throws an error, it includes also stuff like this:

```ts
{
  failed: boolean,   // If the command failed (non-zero exit code)
  exitCode: number,  // Exit code
  stdout: string,    // Everything output to STDOUT
  stderr: string,    // Everything output to STDERR
}
```

It would be nice to have similar output in `simple-git` too.

Today, when I run `git diff --no-index --raw` via `simple-git` on some path with binary files that contain some `CRLF` characters, `simple-git` returned the following error. I wanted to get `STDOUT`, but I was unable (without some regexes), because when I used `error.toString()`, it kept `Error: ` in front of the string and a `warning` was at the end of it. I would be much easier `simple-git` returned `STDOUT` and `STDERR` separately. For now, I need to use `execa` for this particular command.

<details>
  <summary>full error</summary>

```ts
GitError: :100644 100644 e69de29 0000000 M      /tmp_test/machine/a
:100644 000000 e69de29 0000000 D        /tmp_test/machine/b
:100755 100644 010e546 0000000 M        /tmp_test/machine/bin.exe
:100644 000000 e69de29 0000000 D        /tmp_test/machine/c
:100644 000000 e69de29 0000000 D        /tmp_test/machine/d
:100644 100644 9277af1 0000000 M        /tmp_test/machine/e
:000000 100755 0000000 8bd6648 A        /tmp_test/server/h
:000000 100644 0000000 8bd6648 A        /tmp_test/server/j
:100755 100644 e69de29 0000000 M        /tmp_test/machine/x
:000000 100644 0000000 8bd6648 A        /tmp_test/server/y
warning: in the working copy of '/tmp_test/machine/bin.exe', CRLF will be replaced by LF the next time Git touches it

    at Object.action (file:///node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:42:29)
    at PluginStore.exec (file:///node_modules/simple-git/src/lib/plugins/plugin-store.ts:29:29)
    at file:///node_modules/simple-git/src/lib/runners/git-executor-chain.ts:127:42
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (file:///node_modules/simple-git/src/lib/runners/git-executor-chain.ts:124:14)
    at GitExecutorChain.<anonymous> (file:///node_modules/simple-git/src/lib/runners/git-executor-chain.ts:100:40)
    at Generator.next (<anonymous>)
    at fulfilled (file:///node_modules/simple-git/dist/esm/index.js:50:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  task: {
    commands: [
      'diff',
      '--raw',
      '--no-index',
      '/tmp_test/machine',
      '/tmp_test/server',
      '--diff-filter=ACDMRT',
      '--find-copies-harder'
    ],
    format: 'utf-8',
    parser: [Function: parser]
  }
}
```

</details>

<details>
  <summary><code>error.toString()</code></summary>

```ts
Error: :100644 100644 e69de29 0000000 M /tmp_test/machine/a
:100644 000000 e69de29 0000000 D        /tmp_test/machine/b
:100755 100644 010e546 0000000 M        /tmp_test/machine/bin.exe
:100644 000000 e69de29 0000000 D        /tmp_test/machine/c
:100644 000000 e69de29 0000000 D        /tmp_test/machine/d
:100644 100644 9277af1 0000000 M        /tmp_test/machine/e
:000000 100755 0000000 8bd6648 A        /tmp_test/server/h
:000000 100644 0000000 8bd6648 A        /tmp_test/server/j
:100755 100644 e69de29 0000000 M        /tmp_test/machine/x
:000000 100644 0000000 8bd6648 A        /tmp_test/server/y
warning: in the working copy of '/tmp_test/machine/bin.exe', CRLF will be replaced by LF the next time Git touches it
```

</details>

**Comment by steveukx** [comment]
When `simple-git` runs a task, it treats the task as an error when there is a non-zero error code and content printed to stdErr. This isn't always correct though, so each task can provide custom error handling which is how the [branch](https://github.com/steveukx/git-js/blob/main/simple-git/src/lib/tasks/branch.ts#L60-L66) task detects failures to delete a branch instead of any other git error.

In my example above the `result` has the interface:

```typescript
interface GitExecutorResult {
   stdOut: Buffer[];
   stdErr: Buffer[];
   exitCode: number;
   rejection: Maybe<Error>;
}
```

To provide the full output from the git task to the error, you can use:

```
const git = simpleGit({
  errors (error, result) {
    return error instanceof Error && Object.assign(error, { result }) || error;
  }
});

git.log({ ... }).catch(e => {
  console.log(`task resulted in exitCode ${exitCode}`);
  console.log(e.result.stdOut.toString('utf8'));
  console.error(e.result.stdErr.toString('utf8'));
});
```
