### ISSUE TITLE
Diff commands do not return changes from a specified commit to working changes

### ISSUE THREAD

**Issue by kvabel** [steveukx/git-js#828]
Hi,

As part of a project, I need to get the changes that occurred between a specific commit (or latest merge) and the current working copy. Using command line, I am able to get these changes using:
```
git diff 0fd4faf8f2~1 --name-only
```

Using the .diff method or .diffSummary, it appears I am only getting what's on my working copy (either staged or unstaged):
```javascript
const lastMergeCommit = (await gitModule.log(['--merges', '-n', 1, '--format=%h'])).latest.hash;
filesArray = await gitModule.diff(['--name-only', `${lastMergeCommit}~1`])
```

I am aware that current documentation for the diff method specifies a difference between working copy and last commit, but is there any way to use the diff method to return the expected result? The --name-only parameter is also not working out for me.

**Comment by steveukx** [comment]
Hi, you an use the task options object/array in both `git.diff` and `git.summary` to achieve this:

```typescript
git.diff(['0fd4faf8f2~1', '--name-only']);
git.diffSummary('0fd4faf8f2~1', ['--name-only']);
```

Please see the https://github.com/steveukx/git-js#how-to-specify-options docs for more information on how to supply those options.

In what way does the name only parameter not work out for you? If you do need support, please ensure your run the command with [verbose logging enabled](https://github.com/steveukx/git-js/blob/main/docs/DEBUG-LOGGING-GUIDE.md#verbose-logging-options), and include the relevant section of the logs in this issue.

**Comment by kvabel** [comment]
Hello again,

This was an issue on my side. I've tried making a test repository with simple file changes to retest from scratch. On my main project, I was creating modules that were a wrapper around the simple-git functions like diff(options, callback = null) to add some custom error handling.

The thing was, I never sent any callbacks. Instead, I sent a `null` to that parameter, which created the issue:
![simple_git_1](https://user-images.githubusercontent.com/37853678/180786622-043247d2-9d07-4aa0-a764-74ef1c3c0879.png)
![simple_git_2](https://user-images.githubusercontent.com/37853678/180786633-871453d5-c5b1-4cb9-a5d8-fb4386478848.png)

Removing that null callback parameter and ignoring it fixes the issue.
