### ISSUE TITLE
how to specify from and to in git log correctly

### ISSUE THREAD

**Issue by daniloab** [steveukx/git-js#829]
Hi, there. First of all congrats on the excellent lib(that I have been using for some years).

Now, a simple question: how to specify from and to on the git log command? This is the terminal command 

- `git log v3.0.88...main`

How replicates it with the git().log()?

I tried here `await git().log(['v3.0.88', 'main']);` but it returns me the entire log of the repo

**Comment by steveukx** [comment]
Hi, good to hear it's been of use :)

You can find examples of how to use from and to in the `git.log` unit tests: https://github.com/steveukx/git-js/blob/main/simple-git/test/unit/log.spec.ts#L410-L428

For the `...` syntax you just need an object with properties `from` and `to`:

```typescript
const from = 'v3.0.88';
const to = 'main';

git().log({ from, to });
```

**Comment by daniloab** [comment]
cool, thanks!
