### ISSUE TITLE
ESLint error: `Using exported name 'simpleGit' as identifier for default export  import/no-named-as-default`

### ISSUE THREAD

**Issue by josecelano** [steveukx/git-js#834]
I'm importing the module with:

```TypeScript
import {simpleGit, SimpleGit, SimpleGitOptions} from 'simple-git'
```

And I get this error:

```s
Using exported name 'simpleGit' as identifier for default export  import/no-named-as-default
```

This is the ESlint error: https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-named-as-default.md

UPDATE: the error appeared with:

```TypeScript
import simpleGit, {SimpleGit, SimpleGitOptions} from 'simple-git'
```

**Comment by steveukx** [comment]
Thanks for opening the issue.

In order to look into this for you, please either post the full content of the file causing this issue, or create a minimal repository showing your use of eslint and a file that reports this error.

**Comment by josecelano** [comment]
Sorry, I think I got confused with two different repos I was working on. I've updated the issue description.

The error appeared with:

```typescript
import simpleGit, {SimpleGit, SimpleGitOptions} from 'simple-git'
```

And, It was fixed with what I wrote initially on the issue description:

```typescript
import {simpleGit, SimpleGit, SimpleGitOptions} from 'simple-git'
```
