### ISSUE TITLE
git log: using only one of "from", "to"

### ISSUE THREAD

**Issue by bieron** [steveukx/git-js#845]
https://github.com/steveukx/git-js/blob/6b3e05c99a42c75aa9104df151c5386b7b5e2e87/simple-git/src/lib/tasks/log.ts#L123

Hi there, big fan of this repo.
Is there any particular reason why LogOptions `from` and `to` are only applied when both present? Is this a safety measure against something? It denies a valid use case of `git log someCommit..` or `git log ..someCommit` (basically, allowing git to assume HEAD)

**Comment by steveukx** [comment]
Hi, there's no great reason to force using both - you can now use `simple-git@3.13.0` with one or other of `from` and `to`

**Comment by bieron** [comment]
Wow, that was quick, thanks!
