### ISSUE TITLE
Changing date format without using the Options object

### ISSUE THREAD

**Issue by jessica-new** [steveukx/git-js#847]
Hi,

I'm trying to alter the date format (making strictDate false by default), but at the same time pass in a custom argument.

`gitManager.log([...customCommand, "--date=iso8601"]);`

I've tried passing in something like this, but I think it's overwritten by 
      `--pretty=format:${START_BOUNDARY}${formatStr}${COMMIT_BOUNDARY}`, in https://github.com/steveukx/git-js/blob/d0dceda552f7a2f3ee41cb1e56742ff6b1da18ed/simple-git/src/lib/tasks/log.ts#L114

Do you know of any ways I can pass in custom arguments and also a date format?

**Comment by steveukx** [comment]
You can set the `strictDate` property along with other options in the same object:

```
git.log({
  ...customCommand,
  strictDate: false,
  '--date': 'iso8601',
});
```

Assuming that your `customCommand` is supplied as an object: https://github.com/steveukx/git-js#options-as-an-object

You can also override the format object entirely if you need more flexibility (note that the keys in the format object are used in the resulting `LogResult`:

```typescript
git.log({
  ...customConfig
  format: {
    hash: '%H',
    date: '%aI',
    message: '%s',
    refs: '%D',
    body: '%b',
    author_name: '%aN',
    author_email: '%aE',
  },
})
```

**Comment by jessica-new** [comment]
Thanks, that helps a lot
