### ISSUE TITLE
Correct way to get log of a specific file

### ISSUE THREAD

**Issue by escoand** [steveukx/git-js#857]
I'm not able to request the log of a specific file, like this:

```js
 simpleGit().log({file: "path/to/my/file"})
```

It fails with this error:
```
GitError: fatal: ambiguous argument 'path/to/my/file': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

But I found no way to circumvent this problem.

**Comment by escoand** [comment]
Ok, the reason seems to by I'm within the `.git` directory or in a bare repository. Is there a way to accomplish this for this cases as well without using `.raw()`?

**Comment by escoand** [comment]
Once again, found a way to do so:

```js
simpleGit().log({"--":null, "path/to/my/file":null})
```

But is there a reason not to add `--` before `.file` in any case?

**Comment by carafelix** [comment]
This is still a problem:
```js
export async function getCommitsFileFullInfo(filePath:string):Promise<LogResult>{
    const parentPath = path.dirname(filePath)
    return await git.cwd({
        path: parentPath,
    }).log({
        file: filePath,
    })
}
```
The return value was all commits in that folder, disregarding the options.file as a whole. 

Adding ``` "--":null``` solved it.

**Comment by steveukx** [comment]
Thanks for bringing this one up again - `simple-git` now has a `pathspec` utility that does exactly this.

From the next version you will no longer need to include `'--': null` in the options object, a pathspec splitter will automatically be added for you.
