### ISSUE TITLE
Docker K8s pod restarts | No logs no error shown 

### ISSUE THREAD

**Issue by Harsh-Ajudia** [steveukx/git-js#860]
I have been using simple-git with my node.js in one of my recent projects. It works perfectly in my local setup machine but it fails to do so in the server setup. I will try to explain in detail here. 

**Process & Logic:** The aim behind my project is to automate the monotonous task of the git process i.e. to automate everything from taking the clone of a repo, checking out some branch, adding files through code, doing git add . and then committing and pushing changes to the remote repo.

**Issue:** The pod restarts without any apparent reason no console log is generated. We do get SIGTERM signal and then it restarts

**The Code structure pseudocode**

```js
//step: clone _________________________________________
simpleGit({
    baseDir: '',
    timeout: {
        block: 60 * 1000
    }
}).clone()
.then(res => {console})
.catch(err => {console})

// step: checkout (in case it is different) _________________________________________
simpleGit({
    baseDir: '',
    timeout: {
        block: 60 * 1000
    }
}).checkout(name)
.then(res => {console})
.catch(err => {console})

// step: make changes _________________________________________
// in this step we write all files with node fs module to the git baseDir

// step: add files _________________________________________
simpleGit({
    baseDir: '',
    timeout: {
        block: 60 * 1000
    }
}).add('.')
.then(res => {console})
.catch(err => {console})

// step: commit _________________________________________
simpleGit({
    baseDir: '',
    timeout: {
        block: 60 * 1000
    }
}).commit(message)
.then(res => {console})
.catch(err => {console})

// step: push _________________________________________
simpleGit({
    baseDir: '',
    timeout: {
        block: 60 * 1000
    }
}).push(remoteurl, branch)
.then(res => {console})
.catch(err => {console})
`

So this fails sometimes during clone, pull, or push randomly

Looking forward to hearing from you. 

Thanks

**Comment by steveukx** [comment]
Hi, I've not used `simple-git` in k8, but there should be no great difference than when it's being run in docker.

Things to look out for include:

- [switch on verbose logging](https://github.com/steveukx/git-js/blob/main/docs/DEBUG-LOGGING-GUIDE.md#verbose-logging-options)
- consider using [progress events](https://github.com/steveukx/git-js/blob/main/docs/PLUGIN-PROGRESS-EVENTS.md#progress-events) to log each task's progress
- [ensure the pod has `git` installed](https://github.com/steveukx/git-js/blob/main/examples/git-version.md#check-if-git-is-installed)
- ensure the user account the pod is running as is authorised for accessing the remote repo.

let me know how it goes.

**Comment by Harsh-Ajudia** [comment]
> Hi, I've not used `simple-git` in k8, but there should be no great difference than when it's being run in docker.
> 
> Things to look out for include:
> 
> * [switch on verbose logging](https://github.com/steveukx/git-js/blob/main/docs/DEBUG-LOGGING-GUIDE.md#verbose-logging-options)
> * consider using [progress events](https://github.com/steveukx/git-js/blob/main/docs/PLUGIN-PROGRESS-EVENTS.md#progress-events) to log each task's progress
> * [ensure the pod has `git` installed](https://github.com/steveukx/git-js/blob/main/examples/git-version.md#check-if-git-is-installed)
> * ensure the user account the pod is running as is authorised for accessing the remote repo.
> 
> let me know how it goes.

Hi,

Thanks for reaching me.

Please find the answers to your suggestions.

- Switch on verbose: Not tried as of now so will definitely try this.(using progress.on events in current code)
- consider progress event logging: Yes using it but when the pod restarts and I check the previous logs it does not specify the error
- ensure git installation: It is done in my env as it sometimes runs the whole process without any errors/pod restarts
-  ensure the user account the pod is running as is authorised: I use username:password@remote for auth and I have access to the remote rep

Will update you by trying few things you suggested.

Thanks

**Comment by steveukx** [comment]
Hi, having read through your example again, I've noticed that each command is being executed immediately without waiting for the previous command to complete. If this isn't just because you've trimmed the code to fit in a GitHub Issue, it would mean your script could be attempting to checkout, add, commit and push all before the clone has finished.

Consider switching to a set of promises that run in series:

```typescript

function git(baseDir = '') {
  return simpleGit({ baseDir, timeout: { block: 60 * 1000 }});
}

function series(...fns) {
  return fns.reduce((chain, fn) => chain.then(() => fn().then(console.log)), Promise.resolve());
}

const steps = [
  () => git().clone(),
  () => git().checkout(name),
  () => git().add('.'),
  () => git().commit(message),
  () => git().push(remoteurl, branch),
];

series(...steps).catch(console.error);
```

Or reuse the same `simple-git` instance so the later steps queue on the previous ones completing:

```typescript
let git = simpleGit({ ... });
git = git.clone(remote, localDir);
git = git.cwd(localDir);
git = git.checkout(name);
// etc

// then use a promise binding to log at the end of all the steps above
git.then(console.log).catch(console.error);
```

**Comment by Harsh-Ajudia** [comment]
Hi, thanks again for the answer.

I followed the steps you mentioned and it worked!

I am not facing any issues as of now. It works wonders.

Thanks
