### ISSUE TITLE
Would the `Readme#usage` be more readable with a table?

### ISSUE THREAD

**Issue by mohamedhayibor** [steveukx/git-js#87]
@steveukx  I am thinking of something like this:

| Api        | description       | 
| ------------- |:-------------:|
| method     | ..... |
| method     | ..... |

Let me know and I will gladly send a PR.

**Comment by steveukx** [comment]
That would be great thanks, the API has expanded somewhat since the project started!

**Comment by steveukx** [comment]
Thanks for adding that!
