### ISSUE TITLE
Is there a way to get the end of a process via Progress Events?

### ISSUE THREAD

**Issue by DrKabum** [steveukx/git-js#880]
I'd need to know when a process is finished reliably when tracking progress events. When checking with the `progress` value, I don't seem to always get 100% when the process is very fast.

Is there another way?

**Comment by DrKabum** [comment]
To answer my own question, in my case I was able to solve my problem with using a Task Callback to signal the end of the process where I needed it.

**Comment by steveukx** [comment]
Apologies for having missed your question for quite some time... but yes that would be the right way to be informed of a task completing.
