### ISSUE TITLE
How to get repository information?

### ISSUE THREAD

**Issue by aldanchenko** [steveukx/git-js#884]
Hello,

Could you please help. How to get repository information? Like repository owner, for Github for example it will be steveukx (https://github.com/steveukx/git-js).

Thank you for help!

**Comment by steveukx** [comment]
Hi, I hope you found a satisfactory solution as it's taken quite some time to see your question. This kind of info would be specific to the `git` provider rather than the repo itself (ie: github / gitlab / bitbucket would all have their own APIs for finding out repo info).
