### ISSUE TITLE
Is there a way to add --no-optional-locks to git commands?

### ISSUE THREAD

**Issue by summera** [steveukx/git-js#886]
Apologies if I missed it in the docs, but is there a way to add [`git` options](https://git-scm.com/docs/git#_options) to a `simpleGit` instance, such as [`--no-optional-locks`](https://git-scm.com/docs/git#Documentation/git.txt---no-optional-locks)? I'd like to use it with the `status` command, like so:

```sh
git --no-optional-locks status ...
```

Note, that this is a global option that comes **before** the command. Since `git` also responds to the `GIT_OPTIONAL_LOCKS` environment variable, I _think_ I could use `simpleGit().env("GIT_OPTIONAL_LOCKS", 0).status()` to achieve the same thing, however it would be nice to be able to set arbitrary options on the `simpleGit` instance.

 Is this currently only achievable through the plugins that come with `simpleGit` (such as  `commandConfigPrefixingPlugin`)?

**Comment by steveukx** [comment]
Hello, thank you for all the detail in this issue.

There isn't a standard way to apply options before the command itself, but as you suggest, you can use the environment variables to achieve the same effect.

If you rely on environment variables from the outer process being available to the child processes spawned by `simple-git`, you may want to use the object form of the `.env` command:

```typescript
simpleGit().env({ ...process.env, GIT_OPTIONAL_LOCKS: 0 }).status();
```

I will look to make a new plugin that supports the global options, and will reference this issue when I do so you see the progress notification.
