### ISSUE TITLE
`git stash push -- *` has different behavior from CLI

### ISSUE THREAD

**Issue by kevcao-certik** [steveukx/git-js#888]
When running `git stash push -- *` in a repo, directories/files that were deleted do not get added to the stash.

However, with `simple-git`, doing `git.stash(["push", "--", "*"])` does include those deleted directories/files. Am I missing something with the `options` object that causes this discrepancy?

**Comment by kevcao-certik** [comment]
Alternatively, could add support for `git stash push --staged`, since `git add --all --ignore-removal` is supported.

**Comment by steveukx** [comment]
Hello, all of the above are currently supported:

```typescript
// git stash push -- *
git.stash(['push', '--', '*']);

// git stash push --staged
git.stash(['push', '--staged']);

// git add --all --ignore-removal
git.add(['--all', '--ignore-removal']);
```

For reference, I've added a unit test to show support for the `git stash push -- *` command in [stash.spec.ts](https://github.com/steveukx/git-js/blob/main/simple-git/test/unit/stash.spec.ts#L13-L18).

If you are seeing a different behaviour between running the command through `simple-git` and on the terminal directly, is it possible there are different environment variables being used, or that your script runs as a different user with a different global config?

As a next step, I recommend following the [verbose debugging](https://github.com/steveukx/git-js#enable-verbose-logging) guide to see the commands `simple-git` spawns.
