### ISSUE TITLE
git.log() command doesn't log commits from merges

### ISSUE THREAD

**Issue by thomastangerine** [steveukx/git-js#896]
I am using the simple-git's git.log() call to retrieve the latest commit on a particular directory. 

My code is as follows:
```
const gitOptions: LogOptions<DefaultLogFields> = { file: docfxPath }

const git: SimpleGit = simpleGit(docfxPath, { binary: 'git' });

const log = await git.log(gitOptions);

console.log(log.all.slice(0, 5));
const latestCommitId = (await git.log(gitOptions)).latest?.hash;
  ```
  
  When I run the git log terminal command on that same directory, I get the list as follows:
  
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/20932876/217402395-3cbe3ec1-d0d9-4fe6-b0d7-dbbadb2f00fd.png)

However, the list of commits returned by the simple-git call in my code above returns the following list of commits, with the latest commit with message "Merge branch 'thomastang/pushmodel' ... " not being present: 
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/20932876/217402698-d6d9a785-24a2-4821-94d5-0ff7a1795f9f.png)

The git.log().latest field also improperly has the value of the second to latest commit, with the message "empty commit". 

My guess is that Simple-Git's git.log() call for some reason does not include commits that are from merges. I was wondering if my assumption is correct, and if there is a way to retrieve commit logs including commits from merges using Simple-Git?

**Comment by steveukx** [comment]
Hi, apologies for the super delayed response.

There's no obvious reason for merge commits not showing up - so if you didn't find a cause for this please can you run the script with [verbose logging](https://github.com/steveukx/git-js/blob/main/docs/DEBUG-LOGGING-GUIDE.md#verbose-logging-options) enabled.

The verbose logs show the command that `simple-git` passed into `git`, along with all the data that was received. Does manually running the command `simple-git` generates also miss the merge commit?

**Comment by jankrynauw** [comment]
This seems to be related to the `--first-parent` argument.

When you use `--first-parent`, git log follows only the first parent of a merge commit. This effectively gives you a "linear" view of the branch's history, showing only the commits that were directly made onto that branch, and skipping the detailed history of merged feature branches.
