### ISSUE TITLE
Timeout plugin does not work properly without Progress plugin

### ISSUE THREAD

**Issue by emrivero** [steveukx/git-js#897]
### Stack
* Node: v14.18.3
* simple-git@3.16.0
* Ubuntu 20.04

### Issue
I'm using the simple-git clone method with heavy repositories.

When I configure the timeout plugin a timeout error is thrown because the cloning process takes a long time, but the server has really responded and the stdout (or stderr) pocess is receiving content.
However when I configure the timeout plugin and progress plugin the error is not thrown

```js

// this works
const { gitP } = require('simple-git');
const url = 'https://github.com/nodejs/node';

const progress = ({ method, stage, progress }) => {
  console.log(`git.${method} ${stage} stage ${progress}% complete`);
};

const options = {
  baseDir: process.cwd(),
  binary: 'git',
  timeout: {
    block: 5 * 1000,
  },
  progress,
};
try {
  const git = gitP(options);
  git.clone(url);
} catch (err) {
  if (err instanceof GitPluginError && err.plugin === 'timeout') {
    console.error(err);
  }

  const error = typeof err.toString === 'function' ? err.toString() : '';
  console.error(error);
}
```

```js
// this does not work

const { gitP } = require('simple-git');
const url = 'https://github.com/nodejs/node';

const options = {
  baseDir: process.cwd(),
  binary: 'git',
  timeout: {
    block: 5 * 1000,
  },
};
try {
  const git = gitP(options);
  git.clone(url);
} catch (err) {
  if (err instanceof GitPluginError && err.plugin === 'timeout') {
    console.error(err);
  }

  const error = typeof err.toString === 'function' ? err.toString() : '';
  console.error(error);
}
```

**Comment by steveukx** [comment]
Hi, thank you for the detailed description of the issue.

The timeout plugin was created to kill processes that have appeared to hang, so resets the block timeout whenever data is received on the stdout/stderr from the underlying git process. When using progress plugin to read progress updates from git, they are repeatedly written to stderr, meaning the data never stops arriving so the timeout plugin never kills the process.

I've added a feature to the timeout plugin that allows it to be configured to ignore data being received on the stdout, stderr or both streams meaning you can now use the plugin to work on just stdout (as a way to kill hanging processes while still getting the progress updates), or neither stream to work as an absolute timeout.

Examples of both of these are now in the timeout plugin docs, for use with simple-git version 3.17.0 which is now available on npm:

https://github.com/steveukx/git-js/blob/main/docs/PLUGIN-TIMEOUT.md
