### ISSUE TITLE
Concurrency issue

### ISSUE THREAD

**Issue by mattfysh** [steveukx/git-js#905]
Hi steve , thanks for this great library!

I may have found an issue when running commands concurrently on the same instance. I have a `getFileMap` function that essentially reads files from a specific commit and subpath into memory:

```ts
async getFileMap(hash: string, subpath: string) {
  const files: FileMap = {}

  const onEntry = async (entry: ReadEntry) => {
    const source = await text(entry.pipe(new PassThrough()))
    if (!entry.path.endsWith('/')) {
      const relative = path.relative(subpath, entry.path)
      files[relative] = source
    }
  }

  await new Promise<void>((resolve, reject) => {
    try {
      this.git
        .outputHandler((_, stdout) =>
          stdout.pipe(new Parse()).on('entry', onEntry)
        )
        .raw('archive', hash, subpath)
        .then(() => resolve())
        .catch(reject)
    } catch (e) {
      reject(e)
    }
  })

  return files
}
```

If I use it as such, everything works fine because the for loop is run serially:

```ts
for (const { hash: commit } of commits) {
  await this.getFileMap(commit, subpath)
}
```

but when running concurrently in a map function, only one of the commits is populated:

```ts
commits.map(async ({ hash: commit }) => {
  await this.getFileMap(commit, subpath)
})
```

Any ideas what might be causing this? is it a simple-git limitation, or is my implementation of `getFileMap` the culprit - cheers!

**Comment by steveukx** [comment]
Hi, thank you for the detailed issue.

The concurrency problem stems from `simple-git` using a single `outputHandler` per instance, but here you would need the `outputHandler` to relate to the specific use of `git.raw`.

How many commits are you running this across? There are a couple of options:

- parse the return from `git.raw` by splitting the string, this is usually sufficiently performant and allows `simple-git` to manage the number of git child processes launched concurrently.
- keep using the `outputHandler` to parse responses line by line, but use a new instance of `simple-git` for each commit (note - if you are running this across _many_ commits in a tight loop, spawning a large number of child processes, you may need to use your own scheduling/rate limiting to ensure node passes data back to the handlers correctly).
