### ISSUE TITLE
Question: Is there a way to check if simple-git is currently running any operation?

### ISSUE THREAD

**Issue by AyeOne** [steveukx/git-js#915]
Hi there,

I'm using simple-git in my Node.js application, and I need to know if a simple-git instance is currently running any operation, such as a clone, fetch, pull, or push.

I've searched the documentation and the codebase, but I couldn't find any method or property that provides this information.

Is there a recommended way to check if a simple-git instance is currently running any operation? If not, would it be possible to add such a feature to the library in a future version?

Thank you for your help and for maintaining this great library.

**Comment by steveukx** [comment]
Hi, there isn't anything that explicitly does this at the moment, but you could use the `outputHandler` to cache the number of running processes though. 

I've added an example in https://github.com/steveukx/git-js/pull/916 which should be merged.

**Comment by AyeOne** [comment]
Thanks a lot!
