### ISSUE TITLE
[Question] How would you go about contstructing this "git log --since="2023-04-01" $(git describe --tags --abbrev=0)..HEAD"?

### ISSUE THREAD

**Issue by konradgusz** [steveukx/git-js#918]
Hi, 

As an example I tried to use your lib to do the above using advanced syntax
`git log --since="2023-04-01" $(git describe --tags --abbrev=0)..HEAD`

e.g.
```
    const commands = ['log', '--since', '2023-04-01', '$(git describe --tags --abbrev=0)..HEAD'];
    simpleGit(`${folder_location}`).raw(commands)
        .then(
            data => console.log(data)
            
        )
        .catch(
            err => console.log(err)
        )
```
        
 And I get an error like this:
 
> GitError: fatal: ambiguous argument '$(git describe --tags --abbrev=0)..HEAD': unknown revision or path not in the working tree.
> Use '--' to separate paths from revisions, like this:
> 'git <command> [<revision>...] -- [<file>...]'

While I can run this command in git repository and it actually produces results.
`git log --since="2023-04-06" $(git describe --tags --abbrev=0)..HEAD |grep "JIRA" | sort | uniq`

```
Merged in feature-JIRA-123-name (pull request #200)
[JIRA-123] commit message
```

**Comment by steveukx** [comment]
Arguments passed to the git binary by `simple-git` are always passed as strings, meaning the inline evaluation with backticks is not possible. Instead you would need to split the two operations out, for example:

```typescript
const git = simpleGit(folder_location);
const from = await git.raw('describe', '--tags', '--abbrev=0');
const log = await git.raw('log', '--since', '2023-04-01', `${ from.trim() }..HEAD' );
```

If you would like to use `git.log` method for typed responses, you can inline the `describe` as follows:

```
const git = newSimpleGit();
const log = await git.log({
   'from': (await git.raw('describe', '--tags', '--abbrev=0')).trim(),
   'to': 'HEAD',
   '--since': '2023-01-01',
});
```
