### ISSUE TITLE
Git clone using HTTP access token in header doesn't work

### ISSUE THREAD

**Issue by tabramczyk** [steveukx/git-js#919]
Hello,

I'm trying achieve something like this:
```
this.client = simpleGit();
await this.client.raw(['clone', '-c', `http.extraHeader=Authorization: Bearer ${this.bitbucketAccessToken}`, repoPath, localPath])
```
using your native API:
```
this.client = simpleGit();
await this.client.clone(repoPath, localPath, {'-c': `http.extraHeader=Authorization: Bearer ${this.bitbucketAccessToken}`});
```
but in second code i've got error:
`error: bogus config parameter: =http.extraHeader=Authorization: Bearer *************************`

I see that there is additional `=` in message and this is probably reason of the error.

Am I doing something wrong or there is a bug?

PS: Thank you for the lib :)

**Comment by steveukx** [comment]
Hello, the usual way to include `-c` style config options is to add them to the `simple-git` instance rather than to the task itself.

https://github.com/steveukx/git-js#per-command-configuration

**Comment by tabramczyk** [comment]
OK, thanks. It works now.
