### ISSUE TITLE
Documentation too vague?

### ISSUE THREAD

**Issue by FruitJamUK** [steveukx/git-js#92]
I've been picking through the code, to be sure the functions do what I expect them to do, and surprisingly I'm finding that the descriptions are somewhat misleading, particularly when they involve a number of parameters (`mergeFromTo`, `pull`, etc), as the git commands being used use the parameters in a different way to what's described in the documentation.

For example, `mergeFromTo` seems to indicate that it merges `from` into `to` (or vice versa?), but the git documentation indicates that it merges both into the current branch. Additionally, `pull` indicates that it pulls a remote branch, which I'd assumed would pull the remote branch to the tracking branch, but actually, if you're not on the tracking branch, pull acts like a merge. It wouldn't surprise me if someone used this expecting some background checking out or something to merge the two specified branches.

At the very least, it might be worth linking to the relevant git docs for each function for transparency regarding both the function parameters and any option flags.

**Comment by steveukx** [comment]
The docs have grown a bit organically as the functions of the library grew. Please create a pull request with any changes you think you would be worthwhile and I will happily merge them.
