### ISSUE TITLE
Outdated CHANGELOG.md

### ISSUE THREAD

**Issue by EndBug** [steveukx/git-js#923]
Hi 👋🏻 
I noticed that there's a changelog file but it hasn't been updated since v3.1.1

Should this be kept up-to-date, or has it been replaced be release descriptions?

**Comment by steveukx** [comment]
Hello, the changelog in the root represents the monorepo as a whole. 

The `simple-git` library changelog can be found in the package directory itself at https://github.com/steveukx/git-js/blob/main/simple-git/CHANGELOG.md

**Comment by EndBug** [comment]
Oh, got it! Sorry, my bad 😅
