### ISSUE TITLE
It seems that git.diffSummary['master'] cannot work

### ISSUE THREAD

**Issue by xinhaizhixue** [steveukx/git-js#926]
I want to use ‘git diff master --stat’ to get the files modified relative to master in the current workspace，so I thought of using git.diffSummary['master']，but it seems not work，can you tell me what should I do to achieve my goal，or this is a bug？

**Comment by steveukx** [comment]
Hello, to look into this for you, please can you include the fill code you are using to load the diffSummary? Thanks

**Comment by xinhaizhixue** [comment]
oh, I have resolve this problem, it's my mistake,  I confuse the local branch and the remote branch, and pass the remote master branch as a parameter, so the results obtained are inconsistent with expectations. I'm so sorry for taking up your time because of my mistake
