### ISSUE TITLE
Bug: path splitter gets removed if no path spec exists 

### ISSUE THREAD

**Issue by thomaszub** [steveukx/git-js#929]
Hi,

I have currently the issue, that the path splitter `--` is removed if no path spec exists, e.g. `git checkout -f dev --` becomes `git checkout -f dev`.
This can be an issue if for example in a repository with a file `dev`, no local branch `dev` and a remote branch `origin/dev`. The checkout command can not decide which operation to perform (create local branch or restore file) and quits with an error.
This can be reproduced in the repository: https://github.com/thomaszub/simple-git-co-bug

I make a PR.

Kind regards
Thomas

**Comment by steveukx** [comment]
Hi, thank you for the pull request. You can now use this feature as part of the 3.19.1 release which is available on npm now.
