### ISSUE TITLE
How to handle credentials?

### ISSUE THREAD

**Issue by JimmyHodgson** [steveukx/git-js#94]
Is there any way to have different credentials? can you set what credentials to use for a git call? For example, repository 1 uses my personal credentials while repository 2 uses my work credentials. Is this possible?

**Comment by steveukx** [comment]
As the `git-js` library just wraps the `git` command line, you could use standard [git config](https://git-scm.com/docs/gitcredentials) for setting credentials per repo, or you can use the `.addConfig` method to set local configuration values before using any of the other git commands.

**Comment by steveukx** [comment]
With no update, closing issue
