### ISSUE TITLE
 npm ERR! code ETARGET

### ISSUE THREAD

**Issue by NimmiW** [steveukx/git-js#941]
Can somebody help me to fix this installation error?

```
npm install simple-git

npm ERR! code ETARGET
npm ERR! notarget No matching version found for depcheck@1.3.4.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in: /Users/nimmi/.npm/_logs/2023-08-07T20_24_52_803Z-debug-0.log
```

**Comment by steveukx** [comment]
The `simple-git` library doesn't depend on `depcheck` so the error is most likely showing because of another package.

You can check your project for presence of a module with the [npm ls](https://docs.npmjs.com/cli/v7/commands/npm-ls) command.
