### ISSUE TITLE
SSH agent/socket support

### ISSUE THREAD

**Issue by cyl3x** [steveukx/git-js#943]
Recently I wanted to add SSH agent support to [obsidian-git](https://github.com/denolehov/obsidian-git) and found that this library is being used. [Looking at the code](https://github.com/denolehov/obsidian-git/blob/master/src/gitManager/simpleGit.ts#L458) from obsidian-git, everything looks fine to me, env with the desired `SSH_AUTH_SOCK` is passed to simple-git.

Unfortunately it doesn't work, simple-git (or rather git) still asks for my ssh key password. Since this library is more or less a git cli wrapper, why doesn't git pick up the ssh agent like in a normal shell?

EDIT: Sure, obsidian-git is not the easiest example, something like this doesn't work with an ssh agent either:
```js
import simpleGit from 'simple-git';

(new simpleGit()).env(process.env).push();
```

**Comment by steveukx** [comment]
Hi, did you manage to resolve this issue?

I'd recommend enabling the [verbose logging](https://github.com/steveukx/git-js/blob/main/docs/DEBUG-LOGGING-GUIDE.md) and add git's own verbosity environment variables `GIT_TRACE=true` and `GIT_CURL_VERBOSE=true` to see more info on why this isn't working for you. As you say - `simple-git` is just a wrapper for the `git` binary on the host machine, so there's no reason it would be explicitly blocking the `push`.

**Comment by cyl3x** [comment]
I never found the reason, but what definitely worked was adding this to my `~/.ssh/config`:
```
Host *
  IdentityAgent <socket-path>
 ```
