### ISSUE TITLE
Git Push Error 400

### ISSUE THREAD

**Issue by internpoon** [steveukx/git-js#945]
I tried to manually do a git push, i am able to push but no luck programmatically. So i suspect its the Auth, but i have already added the Personal Access Token(PAT) in the config.

```
  const repository = git(file, {
    config: [
      `http.extraheader=Authorization: Basic ${GITHUB_TOKEN}`
    ]
  });
  await repository.init();
  await repository.add('./*');
  await repository.commit("First Commit !");
  await repository.addRemote('origin', remoteRepo);
  
  try {
    await repository.push(['-u', 'origin', 'main'], () => console.log('done'));
  } catch (e) {
    console.log(e);
  }
```

GitError: Pushing to https://github.com/x/test.git
fatal: unable to access 'https://github.com/x/test.git/': The requested URL returned error: 400

  task: {
    commands: [ 'push', '-u', 'origin', 'main', '--verbose', '--porcelain' ],
    format: 'utf-8',
    parser: [Function: parsePushResult]
  }

**Comment by steveukx** [comment]
Hi, the code does look correct - is the `GITHUB_TOKEN` present and base64 encoded (ie: not the raw string starting `ghp...`)?
