### ISSUE TITLE
Unexpected behavior of simpleGit.log when trying to get commits before a tag

### ISSUE THREAD

**Issue by maxxxxxdlp** [steveukx/git-js#956]
I expected this to return list of commits between the first commit in the repository and the v1.0.0 tag:

```ts
await simpleGit.log({
  from: undefined,
  to: 'v1.0.0',
  symmetric: false,
});
```

In reality, it does not return any results.

That is because the above is translated into a git command like this:

```sh
git log ..v1.0.0
```
(which might be interpreted by git as `Show me the commits that are in v1.0.0 but not in the current HEAD` - meaningless most of the time)

to get the expected results (`Show me all the commits from the beginning of the repository's history up to the v1.0.0 tag.`), the command should look like this:

```sh
git log v1.0.0
```

Bug occurs on this line - https://github.com/steveukx/git-js/blob/main/simple-git/src/lib/tasks/log.ts#L126

## Workaround

Until this is fixed, I use the following workaround to get expected results:
```ts
await simpleGit.log({
  'v1.0.0': null
});
```

which looks harmlessly simple in this tiny example, but is quite ugly in my actual code:
```ts
await git.log({
  ...(isFirst
    ? tag === undefined
      ? {}
      : { [tag]: null }
    : {
        from: tags[index - 1],
        to: isLast ? undefined : tag,
        symmetric: false,
      }),
});
```

in comparison, if this bug is fixed, the above would just look like this:

```ts
await git.log({
  from: isFirst ? undefined : tags[index - 1],
  to: isLast ? undefined : tag,
  symmetric: false,
});
```

## Version

Simple Git version: 3.20.0
Git version: 2.40.1

**Comment by steveukx** [comment]
Hi, thanks for opening the detailed issue.

The `from` and `to` fields aren't intended to work as you had expected, which is why the confusion here. The library is designed to use the `from` and `to` fields along with `symmetric` to create the either double or triple dot separated version range.

To explicitly set the bounds of the log, use `rev-list` to first find the commit hash of the initial commit, then use default values in the call to `git.log`

```typescript
const git = simpleGit({ trimmed: true });
const initialCommit = await git.raw('rev-list', '--max-parents=0', 'HEAD');

await git.log({
  from: from ?? initialCommit,
  to: to ?? 'HEAD',
  symmetric: false,
});
```

**Comment by maxxxxxdlp** [comment]
Thank you for the suggestion. This works great!

> The library is designed to use the from and to fields along with symmetric

(optional) Consider adding a warning when not all attributes are provided (or using TypeScript typing to require correct behavior)

**Comment by steveukx** [comment]
As of version 3.21.0 (on npm now) you can get the initial commit hash with `await git.firstCommit()` which will further simplify your code.
