### ISSUE TITLE
Unexpected behavior of simpleGit.log when getting commit details

### ISSUE THREAD

**Issue by sahilshahane** [steveukx/git-js#957]
git-version : `git version 2.42.0`

```tsx
const SGit = simpleGit({
baseDir: <bare repo path>
}); 

 const log = await SGit.log({
      format: {
        hash: true,
        author_email: true,
        author_name: true,
        date: true,
        message: true
      }
    })

  const data = log.latest;

  console.log({ data });
```

Actual Output :
![image](https://github.com/steveukx/git-js/assets/57249267/dcded03f-6fff-4fd2-966a-d3d891c99c22)

Expected Output : 
![image](https://github.com/steveukx/git-js/assets/57249267/ed2a6367-f66a-470d-813d-568b72fdf127)

When i remove the `format`  key from the LogOptions it works as expected

**Comment by steveukx** [comment]
Hi, please see the docs for [git log](https://github.com/steveukx/git-js#git-log) - the format object should be comprised of keys that are the property names used on the returned object, and values that are the format string from [pretty formats](https://git-scm.com/docs/pretty-formats#Documentation/pretty-formats.txt).

By passing `true` as the values in the object, you are requesting that the returned object have the literal string `'true'`.
