### ISSUE TITLE
status() hangs + never returns on repository with hundreds of untracked files. 

### ISSUE THREAD

**Issue by benhylak** [steveukx/git-js#961]
git status from cli returns instantly.

const customStatus = await git.customBinary('git').raw([
  'status',
  '--short'
]);

this also returns instantly, but adding the ignored flag causes it to hang indefinitely again.

any pointers to solving this?

**Comment by steveukx** [comment]
When you add ignored on the command line, how many files are returned?

The parsers currently buffer all content to be manipulated once the git command has completed, so it could be down to memory usage if you have a really large node_modules directory ignored for example.
