### ISSUE TITLE
Ability to provide a command instead of a binary (WSL support)

### ISSUE THREAD

**Issue by meyfa** [steveukx/git-js#973]
Currently, it is possible to specify the path to a Git binary to use instead of the default `git` command (that must be on the path):

```js
const git = simpleGit({
  binary: './path/to/git.exe'
})
```

However, when running on Windows with WSL (Windows Subsystem for Linux) enabled, my use case requires that I use Git via the WSL. This works by running `wsl git` inside a terminal on Windows. For example: `wsl git branch -vv`. Since `wsl git` is not a single binary but instead a command (`wsl`) followed by an argument (`git`), it is not possible to use the existing `binary` option within this library.

My proposal: Allow providing an array as the `binary` argument, or providing an object with keys `command` and `arguments`:

```js
// option 1
const git = simpleGit({
  binary: ['wsl', 'git']
})

// option 2
const git = simpleGit({
  binary: {
    command: 'wsl',
    arguments: ['git']
  }
})
```

**Comment by steveukx** [comment]
Hi, thank you for the detailed issue. You should be able to use the latest version `3.24.0` to provide the two strings for the `binary` config.

```typescript
simpleGit({ binary: ['wsl', 'git'] })
```

Documentation: https://github.com/steveukx/git-js/blob/main/docs/PLUGIN-CUSTOM-BINARY.md

**Comment by meyfa** [comment]
Hey @steveukx, it works like a charm, thank you so much for implementing this!
