### ISSUE TITLE
Add flatpak environment support

### ISSUE THREAD

**Issue by jeffmaury** [steveukx/git-js#978]
In a flatpak environment, git cannot be executed directly but through flatpak-spawn

Flatpak environment is determined by environment variable FLATPAK_ID

**Comment by steveukx** [comment]
Is the intention here to prefix all spawned processes with `flatpak-spawn git` instead of just `git`?

**Comment by steveukx** [comment]
You may be able to use the new functionality for `binary` config to support flatpak:

https://github.com/steveukx/git-js/blob/main/docs/PLUGIN-CUSTOM-BINARY.md
