### ISSUE TITLE
Is it Possible to Use Git Commands in Subdirectories without a .git Folder?

### ISSUE THREAD

**Issue by togetherwelove** [steveukx/git-js#979]
I am currently in the process of integrating Git features into a software project, and I have chosen to use the simple-git library due to its robust and user-friendly interface. During the course of this integration, a question arose that I couldn't find a clear answer to in the existing documentation. I hope this message finds you well. currently the simple-git library seems to work based on the existence of a .git directory. Starting from the current working directory received as an argument to the object, it checks the directories by moving up until it finds the .git folder, then executes the command. However, sometimes you need to call the git command from a subpath of the directory containing .git. Does this feature or method exist? I would appreciate it if you could provide an example or a how-to guide.

**Comment by steveukx** [comment]
Hi, as the `simple-git` library is a wrapper of the command line `git` binary, you can use it in any working directory within a `git` cloned git repo in the same way you would when running commands in terminal.

If you are seeing an exception when using `simple-git`, please ensure you have enabled [verbose logging](https://github.com/steveukx/git-js/blob/main/docs/DEBUG-LOGGING-GUIDE.md) and include the logs along with your issue.

**Comment by togetherwelove** [comment]
For instance, when executing the git status command in a subdirectory, it returns information about the changes in the current directory and its subdirectories, rather than the state of the entire repository. This is particularly useful for checking the status of the directory you are currently working in, offering an individualized query. However, I am uncertain how to achieve this using the git module. When I call the status command through the git module with a subdirectory of the repository (root directory) as an argument, it seems to return the same results as if it were executed from the root directory. Yet, when checked via bash, the results are clearly different. Could you please inform me how to obtain similar results through the module? Thank you.

![image](https://github.com/steveukx/git-js/assets/70801530/282bab2f-a92c-43e2-8182-31992556b2c6)

**Comment by steveukx** [comment]
Thank you for the screenshot.

In order to look into this for you, please include an extract of your code, ensure you have enabled [verbose logging](https://github.com/steveukx/git-js/blob/main/docs/DEBUG-LOGGING-GUIDE.md) and include the logs along with your issue.
