### ISSUE TITLE
submodule init

### ISSUE THREAD

**Issue by finneym** [steveukx/git-js#99]
I'm not sure if I just completely missed something but I can't find a implementation of submodule init

**Comment by steveukx** [comment]
This is currently covered by the generic `subModule` function:

```
simpleGit()
   .subModule(['init'], function (err, data) { ... })
```

If you would like to add a custom function for this as a pull request, you can use the existing `submoduleUpdate` function for an example of how it would be implemented.

**Comment by finneym** [comment]
Thanks for getting back, was just in the process of adding it in! Just testing it at the moment.

**Comment by steveukx** [comment]
No problem. After replying I noticed the generic function isn't actually in the documentation, I'll add it in shortly.
