### ISSUE TITLE
Renamed files with `git diff --name-status`

### ISSUE THREAD

**Issue by adamsol** [steveukx/git-js#991]
With this call:

```js
simpleGit().diffSummary([hash1, hash2, '--name-status']);
```

I'm getting only the new file path for renamed files. Is there a way to get also the previous path?

With `--stat` or `--numstat`, I can get file renames in a format like this: `src/{foo.txt => bar.txt}`, but it's not easy to parse, and I'd like to have file statuses as well.

**Comment by steveukx** [comment]
Thank you for the issue report - in the next version you will be able to check the `from` property of the file in the `DiffResult.files` array.
