### ISSUE TITLE
Defaults override supplies values

### ISSUE THREAD

**Issue by rhys-vdw** [steveukx/git-js#995]
```ts
args
  .option("from", "The version to start from")
  .option("to", "The version to end on", "HEAD")
  .option("out", "The path to prepend the changelog to. Otherwise the change will be sent to stdout.")
  .option("suppress-errors", "Suppress error logs from invalid changelogs", false)

async function main() {
  const options = args.parse(process.argv);
  console.log(options);
 ```
 
 ```sh
 $ npm start -- --from=61 --to=64 --suppress-errors

> es-changelog@0.0.1 start
> ts-node index.ts --from=61 --to=64 --suppress-errors

{
  t: 'HEAD',
  to: 'HEAD',
  s: true,
  suppressErrors: true,
  f: 61,
  from: 61
}
```

However if I remove the default it works.

Notably the `supress-errors` option is respected despite having a default.

**Comment by steveukx** [comment]
Hello, this looks like an example of using something like [commander](https://npmjs.com/package/commander) rather than [simple-git](https://www.npmjs.com/package/simple-git).

If this is relating to `simple-git` please supply the code example showing how you're using `simple-git`

**Comment by rhys-vdw** [comment]
Whoops hahaha. I'm sorry, it does indeed seem like I posted this issue to the entirely wrong repo...
